-- VL Bookers: mid-upper USA + Middle East demand desks (BUYER LEADs)
-- Cities US: NYC LA Miami Chicago SF Boston DC Vegas Seattle Austin Dallas
-- Cities ME: Dubai Abu Dhabi Riyadh Jeddah Doha Bahrain

DO $$
DECLARE
  v_hosp uuid := '8724134a-2249-4d87-83aa-167db279aab8';
  v_conc uuid := 'e857fe35-436d-49c1-a520-38ac9a199ea6';
  v_admin uuid := 'b3105232-0857-4eed-b022-d8147683c059';
  r record;
  v_org uuid;
  inserted int := 0;
  skipped int := 0;
BEGIN
  FOR r IN SELECT * FROM (VALUES
    ('The Ludlow Hotel Desk','The Ludlow Hotel','US','https://www.ludlowhotel.com/',NULL,'reservations@ludlowhotel.com','+12124321700',NULL,'Lower East Side','New York','New York','US',40.7215,-73.9878,'180 Ludlow Street, New York, NY 10002','BOOKER_DEMAND US NYC mid HOSPITALITY LES',v_hosp),
    ('The Marlton Hotel Desk','The Marlton Hotel','US','https://www.marltonhotel.com/',NULL,'reservations@marltonhotel.com','+12123248020',NULL,'Greenwich Village','New York','New York','US',40.7308,-73.9993,'5 West 8th Street, New York, NY 10011','BOOKER_DEMAND US NYC mid HOSPITALITY Village',v_hosp),
    ('The High Line Hotel Desk','The High Line Hotel','US','https://www.thehighlinehotel.com/',NULL,'reservations@thehighlinehotel.com','+12129299293',NULL,'Chelsea','New York','New York','US',40.7463,-74.0048,'180 Tenth Avenue, New York, NY 10011','BOOKER_DEMAND US NYC mid HOSPITALITY Chelsea',v_hosp),
    ('Ace Hotel New York Desk','Ace Hotel New York','US','https://www.acehotel.com/newyork/',NULL,'reservations.ny@acehotel.com','+12126792222',NULL,'Nomad','New York','New York','US',40.7456,-73.9884,'20 West 29th Street, New York, NY 10001','BOOKER_DEMAND US NYC mid HOSPITALITY Nomad',v_hosp),
    ('The James New York SoHo Desk','The James New York – SoHo','US','https://www.jameshotels.com/new-york-soho/',NULL,'reservations.soho@jameshotels.com','+12122558588',NULL,'SoHo','New York','New York','US',40.7224,-74.0045,'27 Grand Street, New York, NY 10013','BOOKER_DEMAND US NYC mid HOSPITALITY SoHo',v_hosp),
    ('Freehand New York Desk','Freehand New York','US','https://freehandhotels.com/new-york/',NULL,'ny@freehandhotels.com','+12124751921',NULL,'Gramercy','New York','New York','US',40.739,-73.9847,'23 Lexington Avenue, New York, NY 10010','BOOKER_DEMAND US NYC mid HOSPITALITY Gramercy',v_hosp),
    ('The Hoxton Williamsburg Desk','The Hoxton Williamsburg','US','https://thehoxton.com/williamsburg/',NULL,'williamsburg@thehoxton.com','+17184864000',NULL,'Williamsburg','New York','New York','US',40.7214,-73.958,'97 Wythe Avenue, Brooklyn, NY 11249','BOOKER_DEMAND US NYC mid HOSPITALITY Williamsburg',v_hosp),
    ('Arlo Nomad Desk','Arlo Nomad','US','https://www.arlohotels.com/nomad/',NULL,'nomad@arlohotels.com','+12122438000',NULL,'Nomad','New York','New York','US',40.7451,-73.989,'11 East 31st Street, New York, NY 10016','BOOKER_DEMAND US NYC mid HOSPITALITY Nomad',v_hosp),
    ('CitizenM New York Bowery Desk','citizenM New York Bowery','US','https://www.citizenm.com/hotels/new-york/new-york-bowery',NULL,'newyork.bowery@citizenm.com','+12129251000',NULL,'Bowery','New York','New York','US',40.7205,-73.9936,'189 Bowery, New York, NY 10002','BOOKER_DEMAND US NYC mid HOSPITALITY Bowery',v_hosp),
    ('Hotel 50 Bowery Desk','Hotel 50 Bowery','US','https://www.hotel50bowery.com/',NULL,'reservations@hotel50bowery.com','+12125098000',NULL,'Bowery','New York','New York','US',40.7163,-73.9958,'50 Bowery, New York, NY 10013','BOOKER_DEMAND US NYC mid HOSPITALITY Bowery',v_hosp),
    ('Walker Hotel Greenwich Village Desk','Walker Hotel Greenwich Village','US','https://www.walkerhotelgv.com/',NULL,'reservations@walkerhotelnyc.com','+12122537000',NULL,'Greenwich Village','New York','New York','US',40.7337,-73.9998,'52 West 13th Street, New York, NY 10011','BOOKER_DEMAND US NYC mid HOSPITALITY Village',v_hosp),
    ('The Standard East Village Desk','The Standard East Village','US','https://www.standardhotels.com/new-york/properties/east-village',NULL,'reservations.eastvillage@standardhotels.com','+12124741900',NULL,'East Village','New York','New York','US',40.7278,-73.991,'25 Cooper Square, New York, NY 10003','BOOKER_DEMAND US NYC mid HOSPITALITY East Village',v_hosp),
    ('Moxy NYC Times Square Desk','Moxy NYC Times Square','US','https://moxy-hotels.marriott.com/en/hotels/new-york-moxy-nyc-times-square',NULL,'moxysales.ts@marriott.com','+12123960000',NULL,'Times Square','New York','New York','US',40.759,-73.9845,'485 Seventh Avenue, New York, NY 10018','BOOKER_DEMAND US NYC mid HOSPITALITY Midtown',v_hosp),
    ('Pod 39 Midtown Desk','Pod 39','US','https://www.thepodhotel.com/pod-39/',NULL,'reservations@thepodhotel.com','+12128655700',NULL,'Murray Hill','New York','New York','US',40.7488,-73.9764,'145 East 39th Street, New York, NY 10016','BOOKER_DEMAND US NYC mid HOSPITALITY Midtown',v_hosp),
    ('Public Hotel Lower East Side Desk','PUBLIC','US','https://www.publichotels.com/newyork',NULL,'reservations.nyc@publichotels.com','+12122721500',NULL,'Lower East Side','New York','New York','US',40.72,-73.9875,'215 Chrystie Street, New York, NY 10002','BOOKER_DEMAND US NYC mid HOSPITALITY LES',v_hosp),
    ('Sixty SoHo Concierge','Sixty SoHo','US','https://www.sixtyhotels.com/soho/',NULL,'soho@sixtyhotels.com','+12124318860',NULL,'SoHo','New York','New York','US',40.7245,-74.003,'60 Thompson Street, New York, NY 10012','BOOKER_DEMAND US NYC mid CONCIERGE SoHo',v_conc),
    ('The LINE LA Desk','The LINE LA','US','https://www.thelinehotel.com/la/',NULL,'reservations.la@thelinehotel.com','+12133817411',NULL,'Koreatown','Los Angeles','California','US',34.0622,-118.3089,'3515 Wilshire Boulevard, Los Angeles, CA 90010','BOOKER_DEMAND US LA mid HOSPITALITY Koreatown',v_hosp),
    ('Ace Hotel Downtown LA Desk','Ace Hotel Downtown Los Angeles','US','https://www.acehotel.com/losangeles/',NULL,'reservations.la@acehotel.com','+12136233233',NULL,'Downtown','Los Angeles','California','US',34.0416,-118.2568,'929 South Broadway, Los Angeles, CA 90015','BOOKER_DEMAND US LA mid HOSPITALITY Downtown',v_hosp),
    ('Hotel Figueroa Desk','Hotel Figueroa','US','https://www.hotelfigueroa.com/',NULL,'reservations@hotelfigueroa.com','+12136278481',NULL,'Downtown','Los Angeles','California','US',34.0431,-118.2675,'939 South Figueroa Street, Los Angeles, CA 90015','BOOKER_DEMAND US LA mid HOSPITALITY Downtown',v_hosp),
    ('Freehand Los Angeles Desk','Freehand Los Angeles','US','https://freehandhotels.com/los-angeles/',NULL,'la@freehandhotels.com','+12136292000',NULL,'Downtown','Los Angeles','California','US',34.0439,-118.2558,'416 West 8th Street, Los Angeles, CA 90014','BOOKER_DEMAND US LA mid HOSPITALITY Downtown',v_hosp),
    ('Hollywood Roosevelt Desk','The Hollywood Roosevelt','US','https://www.thehollywoodroosevelt.com/',NULL,'reservations@thehollywoodroosevelt.com','+13238561970',NULL,'Hollywood','Los Angeles','California','US',34.101,-118.3417,'7000 Hollywood Boulevard, Los Angeles, CA 90028','BOOKER_DEMAND US LA mid HOSPITALITY Hollywood',v_hosp),
    ('Mama Shelter Los Angeles Desk','Mama Shelter Los Angeles','US','https://www.mamashelter.com/en/los-angeles',NULL,'reservations.la@mamashelter.com','+13235222111',NULL,'Hollywood','Los Angeles','California','US',34.1016,-118.3265,'6500 Selma Avenue, Los Angeles, CA 90028','BOOKER_DEMAND US LA mid HOSPITALITY Hollywood',v_hosp),
    ('Kimpton La Peer Hotel Desk','Kimpton La Peer Hotel','US','https://www.lapeerhotel.com/',NULL,'reservations@lapeerhotel.com','+13106585040',NULL,'West Hollywood','Los Angeles','California','US',34.0837,-118.384,'627 North La Peer Drive, West Hollywood, CA 90069','BOOKER_DEMAND US LA mid HOSPITALITY WeHo',v_hosp),
    ('Palihotel Melrose Desk','Palihotel Melrose','US','https://www.palisociety.com/hotels/melrose/',NULL,'melrose@palisociety.com','+13236551111',NULL,'Melrose','Los Angeles','California','US',34.0837,-118.3445,'7950 Melrose Avenue, Los Angeles, CA 90046','BOOKER_DEMAND US LA mid HOSPITALITY Melrose',v_hosp),
    ('The Hoxton Downtown LA Desk','The Hoxton Downtown LA','US','https://thehoxton.com/downtown-la/',NULL,'downtownla@thehoxton.com','+12136232323',NULL,'Downtown','Los Angeles','California','US',34.0478,-118.2535,'1060 South Broadway, Los Angeles, CA 90015','BOOKER_DEMAND US LA mid HOSPITALITY Downtown',v_hosp),
    ('NoMad Los Angeles Desk','NoMad Los Angeles','US','https://www.thenomadhotel.com/los-angeles',NULL,'reservations.la@thenomadhotel.com','+12136236000',NULL,'Downtown','Los Angeles','California','US',34.0445,-118.256,'649 South Olive Street, Los Angeles, CA 90014','BOOKER_DEMAND US LA mid HOSPITALITY Downtown',v_hosp),
    ('Kimpton Everly Hotel Desk','Kimpton Everly Hotel Hollywood','US','https://www.everlyhotel.com/',NULL,'reservations@everlyhotel.com','+13238026000',NULL,'Hollywood','Los Angeles','California','US',34.1018,-118.326,'1800 Orchid Avenue, Los Angeles, CA 90028','BOOKER_DEMAND US LA mid HOSPITALITY Hollywood',v_hosp),
    ('Hotel June West LA Desk','Hotel June','US','https://www.hoteljune.com/',NULL,'reservations@hoteljune.com','+13104781000',NULL,'West Los Angeles','Los Angeles','California','US',34.0345,-118.4505,'12032 Wilshire Boulevard, Los Angeles, CA 90025','BOOKER_DEMAND US LA mid HOSPITALITY West LA',v_hosp),
    ('Shade Hotel Manhattan Beach Desk','Shade Hotel Manhattan Beach','US','https://www.shadehotel.com/',NULL,'reservations@shadehotel.com','+13105464444',NULL,'Manhattan Beach','Los Angeles','California','US',33.8847,-118.4109,'1221 North Valley Drive, Manhattan Beach, CA 90266','BOOKER_DEMAND US LA mid HOSPITALITY South Bay',v_hosp),
    ('Viceroy Santa Monica Concierge','Viceroy Santa Monica','US','https://www.viceroyhotelsandresorts.com/santa-monica',NULL,'santamonica@viceroyhotel.com','+13102606666',NULL,'Santa Monica','Los Angeles','California','US',34.0125,-118.4955,'1819 Ocean Avenue, Santa Monica, CA 90401','BOOKER_DEMAND US LA mid CONCIERGE Santa Monica',v_conc),
    ('Freehand Miami Desk','Freehand Miami','US','https://freehandhotels.com/miami/',NULL,'miami@freehandhotels.com','+13055312720',NULL,'Miami Beach','Miami','Florida','US',25.7907,-80.13,'2727 Indian Creek Drive, Miami Beach, FL 33140','BOOKER_DEMAND US Miami mid HOSPITALITY Miami Beach',v_hosp),
    ('The Confidante Miami Beach Desk','The Confidante Miami Beach','US','https://www.theconfidantehotel.com/',NULL,'reservations@theconfidantehotel.com','+13058651000',NULL,'Mid-Beach','Miami','Florida','US',25.8115,-80.1235,'4041 Collins Avenue, Miami Beach, FL 33140','BOOKER_DEMAND US Miami mid HOSPITALITY Mid-Beach',v_hosp),
    ('Kimpton Surfcomber Desk','Kimpton Surfcomber','US','https://www.surfcomber.com/',NULL,'reservations@surfcomber.com','+13055315800',NULL,'Mid-Beach','Miami','Florida','US',25.805,-80.1245,'1717 Collins Avenue, Miami Beach, FL 33139','BOOKER_DEMAND US Miami mid HOSPITALITY Mid-Beach',v_hosp),
    ('Nautilus by Arlo Desk','Nautilus by Arlo','US','https://www.arlohotels.com/nautilus/',NULL,'nautilus@arlohotels.com','+13055685500',NULL,'Mid-Beach','Miami','Florida','US',25.802,-80.125,'1825 Collins Avenue, Miami Beach, FL 33139','BOOKER_DEMAND US Miami mid HOSPITALITY Mid-Beach',v_hosp),
    ('The Gale South Beach Desk','The Gale South Beach','US','https://www.thegalehotel.com/',NULL,'reservations@thegalehotel.com','+13056730000',NULL,'South Beach','Miami','Florida','US',25.7905,-80.1295,'1690 Collins Avenue, Miami Beach, FL 33139','BOOKER_DEMAND US Miami mid HOSPITALITY South Beach',v_hosp),
    ('Hotel Greystone South Beach Desk','Hotel Greystone','US','https://www.greystonehotel.com/',NULL,'reservations@greystonehotel.com','+13055311819',NULL,'South Beach','Miami','Florida','US',25.788,-80.1305,'1920 Collins Avenue, Miami Beach, FL 33139','BOOKER_DEMAND US Miami mid HOSPITALITY South Beach',v_hosp),
    ('Catalina Hotel South Beach Desk','Catalina Hotel & Beach Club','US','https://www.catalinahotel.com/',NULL,'reservations@catalinahotel.com','+13053241399',NULL,'South Beach','Miami','Florida','US',25.79,-80.1302,'1732 Collins Avenue, Miami Beach, FL 33139','BOOKER_DEMAND US Miami mid HOSPITALITY South Beach',v_hosp),
    ('Circa 39 Hotel Desk','Circa 39 Hotel','US','https://www.circa39.com/',NULL,'reservations@circa39.com','+13055381737',NULL,'Mid-Beach','Miami','Florida','US',25.813,-80.123,'3900 Collins Avenue, Miami Beach, FL 33140','BOOKER_DEMAND US Miami mid HOSPITALITY Mid-Beach',v_hosp),
    ('1 Hotel South Beach Desk','1 Hotel South Beach','US','https://www.1hotels.com/south-beach',NULL,'reservations.southbeach@1hotels.com','+13056055300',NULL,'South Beach','Miami','Florida','US',25.7945,-80.128,'2341 Collins Avenue, Miami Beach, FL 33139','BOOKER_DEMAND US Miami mid HOSPITALITY South Beach',v_hosp),
    ('Marriott Stanton South Beach Desk','Marriott Stanton South Beach','US','https://www.marriott.com/hotels/travel/miasb-marriott-stanton-south-beach/',NULL,'miasb.reservations@marriott.com','+13055343234',NULL,'South Beach','Miami','Florida','US',25.781,-80.1315,'161 Ocean Drive, Miami Beach, FL 33139','BOOKER_DEMAND US Miami mid HOSPITALITY South Beach',v_hosp),
    ('East Miami Brickell Desk','EAST Miami','US','https://www.east-miami.com/',NULL,'reservations.miami@east-hotels.com','+13055799999',NULL,'Brickell','Miami','Florida','US',25.7605,-80.192,'788 Brickell Plaza, Miami, FL 33131','BOOKER_DEMAND US Miami mid HOSPITALITY Brickell',v_hosp),
    ('SLS Brickell Concierge','SLS Brickell','US','https://www.slshotels.com/brickell',NULL,'brickell@slshotels.com','+13056016000',NULL,'Brickell','Miami','Florida','US',25.7655,-80.1915,'1300 South Miami Avenue, Miami, FL 33130','BOOKER_DEMAND US Miami mid CONCIERGE Brickell',v_conc),
    ('The Robey Chicago Desk','The Robey','US','https://www.therobey.com/',NULL,'reservations@therobey.com','+18777362393',NULL,'Wicker Park','Chicago','Illinois','US',41.9105,-87.6775,'2018 West North Avenue, Chicago, IL 60647','BOOKER_DEMAND US Chicago mid HOSPITALITY Wicker Park',v_hosp),
    ('Freehand Chicago Desk','Freehand Chicago','US','https://freehandhotels.com/chicago/',NULL,'chicago@freehandhotels.com','+13125290000',NULL,'River North','Chicago','Illinois','US',41.8935,-87.6255,'19 East Ohio Street, Chicago, IL 60611','BOOKER_DEMAND US Chicago mid HOSPITALITY River North',v_hosp),
    ('Ace Hotel Chicago Desk','Ace Hotel Chicago','US','https://www.acehotel.com/chicago/',NULL,'reservations.chicago@acehotel.com','+13127544444',NULL,'West Loop','Chicago','Illinois','US',41.8855,-87.6485,'311 North Morgan Street, Chicago, IL 60607','BOOKER_DEMAND US Chicago mid HOSPITALITY West Loop',v_hosp),
    ('Hotel Lincoln Chicago Desk','Hotel Lincoln','US','https://www.hotellincolnchicago.com/',NULL,'reservations@hotellincolnchicago.com','+13126648000',NULL,'Lincoln Park','Chicago','Illinois','US',41.9215,-87.6385,'1816 North Clark Street, Chicago, IL 60614','BOOKER_DEMAND US Chicago mid HOSPITALITY Lincoln Park',v_hosp),
    ('The Hoxton Chicago Desk','The Hoxton Chicago','US','https://thehoxton.com/chicago/',NULL,'chicago@thehoxton.com','+13127544000',NULL,'West Loop','Chicago','Illinois','US',41.8845,-87.648,'200 North Green Street, Chicago, IL 60607','BOOKER_DEMAND US Chicago mid HOSPITALITY West Loop',v_hosp),
    ('Kimpton Gray Chicago Desk','Kimpton Gray Hotel','US','https://www.grayhotelchicago.com/',NULL,'reservations@grayhotelchicago.com','+13127507200',NULL,'Loop','Chicago','Illinois','US',41.8805,-87.6285,'122 West Monroe Street, Chicago, IL 60603','BOOKER_DEMAND US Chicago mid HOSPITALITY Loop',v_hosp),
    ('Virgin Hotels Chicago Desk','Virgin Hotels Chicago','US','https://virginhotels.com/chicago/',NULL,'reservations.chicago@virginhotels.com','+13122448161',NULL,'Near South Side','Chicago','Illinois','US',41.8665,-87.6245,'203 North Wabash Avenue, Chicago, IL 60601','BOOKER_DEMAND US Chicago mid HOSPITALITY Downtown',v_hosp),
    ('The Godfrey Hotel Chicago Desk','The Godfrey Hotel Chicago','US','https://www.godfreyhotelchicago.com/',NULL,'reservations@godfreyhotelchicago.com','+13126491000',NULL,'River North','Chicago','Illinois','US',41.8905,-87.628,'127 West Huron Street, Chicago, IL 60654','BOOKER_DEMAND US Chicago mid HOSPITALITY River North',v_hosp),
    ('Hotel Zachary Chicago Desk','Hotel Zachary','US','https://www.hotelzachary.com/',NULL,'reservations@hotelzachary.com','+17736971000',NULL,'Wrigleyville','Chicago','Illinois','US',41.9485,-87.6565,'3636 North Sheffield Avenue, Chicago, IL 60613','BOOKER_DEMAND US Chicago mid HOSPITALITY Wrigleyville',v_hosp),
    ('Pendry Chicago Desk','Pendry Chicago','US','https://www.pendry.com/chicago/',NULL,'reservations.chicago@pendry.com','+13124968000',NULL,'River North','Chicago','Illinois','US',41.89,-87.6245,'230 North Michigan Avenue, Chicago, IL 60601','BOOKER_DEMAND US Chicago mid HOSPITALITY River North',v_hosp),
    ('Thompson Chicago Desk','Thompson Chicago','US','https://www.thompsonhotels.com/hotels/chicago',NULL,'reservations.chicago@thompsonhotels.com','+13122661000',NULL,'Gold Coast','Chicago','Illinois','US',41.9005,-87.6275,'85 East Wacker Place, Chicago, IL 60601','BOOKER_DEMAND US Chicago mid HOSPITALITY River North',v_hosp),
    ('Soho House Chicago Concierge','Soho House Chicago','US','https://www.sohohouse.com/houses/soho-house-chicago',NULL,'chicago@sohohouse.com','+13125212000',NULL,'West Loop','Chicago','Illinois','US',41.8835,-87.6485,'113 North Green Street, Chicago, IL 60607','BOOKER_DEMAND US Chicago mid CONCIERGE West Loop',v_conc),
    ('Hotel Zetta Desk','Hotel Zetta','US','https://www.viceroyhotelsandresorts.com/zetta',NULL,'reservations@hotelzetta.com','+14155438555',NULL,'SoMa','San Francisco','California','US',37.7835,-122.4075,'55 Fifth Street, San Francisco, CA 94103','BOOKER_DEMAND US SF mid HOSPITALITY SoMa',v_hosp),
    ('Hotel Kabuki Desk','Hotel Kabuki','US','https://www.jdvhotels.com/hotels/california/san-francisco/hotel-kabuki',NULL,'reservations@hotelkabuki.com','+14159225500',NULL,'Japantown','San Francisco','California','US',37.7855,-122.4305,'1625 Post Street, San Francisco, CA 94115','BOOKER_DEMAND US SF mid HOSPITALITY Japantown',v_hosp),
    ('Proper Hotel San Francisco Desk','Proper Hotel San Francisco','US','https://www.properhotel.com/san-francisco/',NULL,'sf@properhotel.com','+14157367777',NULL,'Tenderloin','San Francisco','California','US',37.787,-122.4165,'45 McAllister Street, San Francisco, CA 94102','BOOKER_DEMAND US SF mid HOSPITALITY Civic Center',v_hosp),
    ('Hotel Nikko San Francisco Desk','Hotel Nikko San Francisco','US','https://www.hotelnikkosf.com/',NULL,'reservations@hotelnikkosf.com','+14153941111',NULL,'Union Square','San Francisco','California','US',37.7858,-122.4105,'222 Mason Street, San Francisco, CA 94102','BOOKER_DEMAND US SF mid HOSPITALITY Union Square',v_hosp),
    ('Hotel Vitale Desk','Hotel Vitale','US','https://www.hotelvitale.com/',NULL,'reservations@hotelvitale.com','+14152787900',NULL,'Embarcadero','San Francisco','California','US',37.7935,-122.3915,'8 Mission Street, San Francisco, CA 94105','BOOKER_DEMAND US SF mid HOSPITALITY Embarcadero',v_hosp),
    ('Argonaut Hotel Desk','Argonaut Hotel','US','https://www.argonauthotel.com/',NULL,'reservations@argonauthotel.com','+14155630800',NULL,'Fishermans Wharf','San Francisco','California','US',37.8075,-122.4205,'495 Jefferson Street, San Francisco, CA 94109','BOOKER_DEMAND US SF mid HOSPITALITY Wharf',v_hosp),
    ('Hotel Zelos Desk','Hotel Zelos San Francisco','US','https://www.viceroyhotelsandresorts.com/zelos',NULL,'reservations@hotelzelos.com','+14153481234',NULL,'SoMa','San Francisco','California','US',37.7865,-122.4045,'12 Fourth Street, San Francisco, CA 94103','BOOKER_DEMAND US SF mid HOSPITALITY SoMa',v_hosp),
    ('Clift Royal Sonesta Desk','Clift Royal Sonesta San Francisco','US','https://www.sonesta.com/royal-sonesta/ca/san-francisco/clift-royal-sonesta-hotel',NULL,'clift.reservations@sonesta.com','+14157754700',NULL,'Union Square','San Francisco','California','US',37.7868,-122.4115,'495 Geary Street, San Francisco, CA 94102','BOOKER_DEMAND US SF mid HOSPITALITY Union Square',v_hosp),
    ('Beacon Grand Desk','Beacon Grand A Historic Hotel','US','https://www.beacongrand.com/',NULL,'reservations@beacongrand.com','+14157711400',NULL,'Union Square','San Francisco','California','US',37.7875,-122.4095,'450 Powell Street, San Francisco, CA 94102','BOOKER_DEMAND US SF mid HOSPITALITY Union Square',v_hosp),
    ('Hotel Emblem Desk','Hotel Emblem San Francisco','US','https://www.hotelemblem.com/',NULL,'reservations@hotelemblem.com','+14156737000',NULL,'Union Square','San Francisco','California','US',37.7872,-122.4125,'562 Sutter Street, San Francisco, CA 94102','BOOKER_DEMAND US SF mid HOSPITALITY Union Square',v_hosp),
    ('Hotel Zoe Fisherman Wharf Desk','Hotel Zoe Fishermans Wharf','US','https://www.hotelzoesf.com/',NULL,'reservations@hotelzoesf.com','+14155611100',NULL,'Fishermans Wharf','San Francisco','California','US',37.8078,-122.4155,'425 North Point Street, San Francisco, CA 94133','BOOKER_DEMAND US SF mid HOSPITALITY Wharf',v_hosp),
    ('The Marker San Francisco Concierge','The Marker San Francisco','US','https://www.themarkersanfrancisco.com/',NULL,'reservations@themarkersanfrancisco.com','+14152929600',NULL,'Union Square','San Francisco','California','US',37.786,-122.4085,'501 Geary Street, San Francisco, CA 94102','BOOKER_DEMAND US SF mid CONCIERGE Union Square',v_conc),
    ('The Verb Hotel Desk','The Verb Hotel','US','https://www.theverbhotel.com/',NULL,'reservations@theverbhotel.com','+16175661000',NULL,'Fenway','Boston','Massachusetts','US',42.3455,-71.0985,'1271 Boylston Street, Boston, MA 02215','BOOKER_DEMAND US Boston mid HOSPITALITY Fenway',v_hosp),
    ('Hotel Commonwealth Desk','Hotel Commonwealth','US','https://www.hotelcommonwealth.com/',NULL,'reservations@hotelcommonwealth.com','+16179335000',NULL,'Kenmore','Boston','Massachusetts','US',42.3485,-71.0955,'500 Commonwealth Avenue, Boston, MA 02215','BOOKER_DEMAND US Boston mid HOSPITALITY Kenmore',v_hosp),
    ('The Godfrey Hotel Boston Desk','The Godfrey Hotel Boston','US','https://www.godfreyhotelboston.com/',NULL,'reservations@godfreyhotelboston.com','+16174510000',NULL,'Downtown','Boston','Massachusetts','US',42.3545,-71.0615,'505 Washington Street, Boston, MA 02111','BOOKER_DEMAND US Boston mid HOSPITALITY Downtown',v_hosp),
    ('Kimpton Nine Zero Desk','Kimpton Nine Zero','US','https://www.ninezero.com/',NULL,'reservations@ninezero.com','+16173585800',NULL,'Downtown','Boston','Massachusetts','US',42.3565,-71.061,'90 Tremont Street, Boston, MA 02108','BOOKER_DEMAND US Boston mid HOSPITALITY Downtown',v_hosp),
    ('The Boxer Boston Desk','The Boxer','US','https://www.theboxerboston.com/',NULL,'reservations@theboxerboston.com','+16176247500',NULL,'West End','Boston','Massachusetts','US',42.3645,-71.0665,'107 Merrimac Street, Boston, MA 02114','BOOKER_DEMAND US Boston mid HOSPITALITY West End',v_hosp),
    ('The Revolution Hotel Desk','The Revolution Hotel','US','https://www.revolutionhotelboston.com/',NULL,'reservations@revolutionhotelboston.com','+16173485000',NULL,'South End','Boston','Massachusetts','US',42.3435,-71.0705,'78 Charles Street South, Boston, MA 02116','BOOKER_DEMAND US Boston mid HOSPITALITY South End',v_hosp),
    ('Hotel Indigo Boston Garden Desk','Hotel Indigo Boston-Garden','US','https://www.ihg.com/hotelindigo/hotels/us/en/boston/bosid/hoteldetail',NULL,'reservations.bosid@ihg.com','+16172222222',NULL,'West End','Boston','Massachusetts','US',42.3655,-71.0635,'250 Causeway Street, Boston, MA 02114','BOOKER_DEMAND US Boston mid HOSPITALITY West End',v_hosp),
    ('The Charlesmark Hotel Desk','The Charlesmark Hotel','US','https://www.charlesmarkhotel.com/',NULL,'reservations@charlesmarkhotel.com','+16172471220',NULL,'Back Bay','Boston','Massachusetts','US',42.3495,-71.0805,'655 Boylston Street, Boston, MA 02116','BOOKER_DEMAND US Boston mid HOSPITALITY Back Bay',v_hosp),
    ('Hotel Marlowe Cambridge Desk','Hotel Marlowe','US','https://www.hotelmarlowe.com/',NULL,'reservations@hotelmarlowe.com','+16178688000',NULL,'East Cambridge','Cambridge','Massachusetts','US',42.3685,-71.0755,'25 Edwin Land Boulevard, Cambridge, MA 02141','BOOKER_DEMAND US Boston mid HOSPITALITY Cambridge',v_hosp),
    ('XV Beacon Concierge','XV Beacon','US','https://www.xvbeacon.com/',NULL,'reservations@xvbeacon.com','+16176701500',NULL,'Beacon Hill','Boston','Massachusetts','US',42.3585,-71.0625,'15 Beacon Street, Boston, MA 02108','BOOKER_DEMAND US Boston mid CONCIERGE Beacon Hill',v_conc),
    ('The LINE DC Desk','The LINE DC','US','https://www.thelinehotel.com/dc/',NULL,'reservations.dc@thelinehotel.com','+12025888000',NULL,'Adams Morgan','Washington','District of Columbia','US',38.9215,-77.0425,'1770 Kalorama Road NW, Washington, DC 20009','BOOKER_DEMAND US DC mid HOSPITALITY Adams Morgan',v_hosp),
    ('Kimpton Hotel Monaco DC Desk','Kimpton Hotel Monaco Washington DC','US','https://www.monaco-dc.com/',NULL,'reservations@monaco-dc.com','+12026287170',NULL,'Penn Quarter','Washington','District of Columbia','US',38.8965,-77.0225,'700 F Street NW, Washington, DC 20004','BOOKER_DEMAND US DC mid HOSPITALITY Penn Quarter',v_hosp),
    ('Eaton DC Desk','Eaton DC','US','https://www.eatonworkshop.com/washington-dc',NULL,'dc@eatonworkshop.com','+12029312500',NULL,'Downtown','Washington','District of Columbia','US',38.9055,-77.0325,'1201 K Street NW, Washington, DC 20005','BOOKER_DEMAND US DC mid HOSPITALITY Downtown',v_hosp),
    ('Riggs Washington DC Desk','Riggs Washington DC','US','https://www.riggsdc.com/',NULL,'reservations@riggsdc.com','+12026383000',NULL,'Penn Quarter','Washington','District of Columbia','US',38.8985,-77.0235,'900 F Street NW, Washington, DC 20004','BOOKER_DEMAND US DC mid HOSPITALITY Penn Quarter',v_hosp),
    ('The Darcy Hotel Desk','The Darcy Hotel','US','https://www.thedarcyhotel.com/',NULL,'reservations@thedarcyhotel.com','+12022976000',NULL,'Dupont Circle','Washington','District of Columbia','US',38.9105,-77.0435,'1515 Rhode Island Avenue NW, Washington, DC 20005','BOOKER_DEMAND US DC mid HOSPITALITY Dupont',v_hosp),
    ('Hotel Hive Desk','Hotel Hive','US','https://www.hotelhive.com/',NULL,'reservations@hotelhive.com','+12028030000',NULL,'Foggy Bottom','Washington','District of Columbia','US',38.9015,-77.0505,'2224 F Street NW, Washington, DC 20037','BOOKER_DEMAND US DC mid HOSPITALITY Foggy Bottom',v_hosp),
    ('The Graham Georgetown Desk','The Graham Georgetown','US','https://www.thegrahamgeorgetown.com/',NULL,'reservations@thegrahamgeorgetown.com','+12023371600',NULL,'Georgetown','Washington','District of Columbia','US',38.9055,-77.0625,'1075 Thomas Jefferson Street NW, Washington, DC 20007','BOOKER_DEMAND US DC mid HOSPITALITY Georgetown',v_hosp),
    ('The Dupont Circle Hotel Desk','The Dupont Circle Hotel','US','https://www.doylecollection.com/hotels/the-dupont-circle-hotel',NULL,'dupontcircle@doylecollection.com','+12024836000',NULL,'Dupont Circle','Washington','District of Columbia','US',38.91,-77.043,'1500 New Hampshire Avenue NW, Washington, DC 20036','BOOKER_DEMAND US DC mid HOSPITALITY Dupont',v_hosp),
    ('Hotel Lombardy Desk','Hotel Lombardy','US','https://www.hotellombardy.com/',NULL,'reservations@hotellombardy.com','+12028281300',NULL,'Foggy Bottom','Washington','District of Columbia','US',38.9005,-77.0485,'2019 Pennsylvania Avenue NW, Washington, DC 20006','BOOKER_DEMAND US DC mid HOSPITALITY Foggy Bottom',v_hosp),
    ('Mason & Rook Concierge','Mason & Rook Hotel','US','https://www.masonandrookhotel.com/',NULL,'reservations@masonandrookhotel.com','+12022955555',NULL,'Logan Circle','Washington','District of Columbia','US',38.9085,-77.0325,'1430 Rhode Island Avenue NW, Washington, DC 20005','BOOKER_DEMAND US DC mid CONCIERGE Logan Circle',v_conc),
    ('Virgin Hotels Las Vegas Desk','Virgin Hotels Las Vegas','US','https://virginhotels.com/las-vegas/',NULL,'reservations.vegas@virginhotels.com','+17024140000',NULL,'Strip East','Las Vegas','Nevada','US',36.1095,-115.1535,'4455 Paradise Road, Las Vegas, NV 89169','BOOKER_DEMAND US Vegas mid HOSPITALITY Strip East',v_hosp),
    ('The Cromwell Las Vegas Desk','The Cromwell','US','https://www.caesars.com/cromwell',NULL,'cromwell.reservations@caesars.com','+17027773777',NULL,'Las Vegas Strip','Las Vegas','Nevada','US',36.115,-115.1725,'3595 Las Vegas Boulevard South, Las Vegas, NV 89109','BOOKER_DEMAND US Vegas mid HOSPITALITY Strip',v_hosp),
    ('NoMad Las Vegas Desk','NoMad Las Vegas','US','https://www.thenomadhotel.com/las-vegas',NULL,'reservations.vegas@thenomadhotel.com','+17026309000',NULL,'Park MGM','Las Vegas','Nevada','US',36.1045,-115.1765,'3770 Las Vegas Boulevard South, Las Vegas, NV 89109','BOOKER_DEMAND US Vegas mid HOSPITALITY Strip',v_hosp),
    ('Circa Resort Desk','Circa Resort & Casino','US','https://www.circalasvegas.com/',NULL,'reservations@circalasvegas.com','+17022472274',NULL,'Downtown','Las Vegas','Nevada','US',36.1715,-115.1455,'8 Fremont Street, Las Vegas, NV 89101','BOOKER_DEMAND US Vegas mid HOSPITALITY Downtown',v_hosp),
    ('Downtown Grand Desk','Downtown Grand Hotel & Casino','US','https://www.downtowngrand.com/',NULL,'reservations@downtowngrand.com','+17027195100',NULL,'Downtown','Las Vegas','Nevada','US',36.1695,-115.1425,'206 North 3rd Street, Las Vegas, NV 89101','BOOKER_DEMAND US Vegas mid HOSPITALITY Downtown',v_hosp),
    ('The LINQ Hotel Desk','The LINQ Hotel + Experience','US','https://www.caesars.com/linq',NULL,'linq.reservations@caesars.com','+18006346444',NULL,'Las Vegas Strip','Las Vegas','Nevada','US',36.1175,-115.1715,'3535 Las Vegas Boulevard South, Las Vegas, NV 89109','BOOKER_DEMAND US Vegas mid HOSPITALITY Strip',v_hosp),
    ('Artisan Hotel Boutique Desk','Artisan Hotel Boutique','US','https://www.artisanhotel.com/',NULL,'reservations@artisanhotel.com','+17022141414',NULL,'West of Strip','Las Vegas','Nevada','US',36.1425,-115.1855,'1501 West Sahara Avenue, Las Vegas, NV 89102','BOOKER_DEMAND US Vegas mid HOSPITALITY West Strip',v_hosp),
    ('Plaza Hotel Downtown Vegas Desk','Plaza Hotel & Casino','US','https://www.plazahotelcasino.com/',NULL,'reservations@plazahotelcasino.com','+17023863511',NULL,'Downtown','Las Vegas','Nevada','US',36.1725,-115.1465,'1 Main Street, Las Vegas, NV 89101','BOOKER_DEMAND US Vegas mid HOSPITALITY Downtown',v_hosp),
    ('Sahara Las Vegas Desk','Sahara Las Vegas','US','https://www.saharalasvegas.com/',NULL,'reservations@saharalasvegas.com','+17027372111',NULL,'North Strip','Las Vegas','Nevada','US',36.1425,-115.1565,'2535 Las Vegas Boulevard South, Las Vegas, NV 89109','BOOKER_DEMAND US Vegas mid HOSPITALITY North Strip',v_hosp),
    ('Delano Las Vegas Concierge','Delano Las Vegas','US','https://www.delanolasvegas.com/',NULL,'delano.reservations@mgmresorts.com','+17026329000',NULL,'South Strip','Las Vegas','Nevada','US',36.0935,-115.1765,'3940 Las Vegas Boulevard South, Las Vegas, NV 89119','BOOKER_DEMAND US Vegas mid CONCIERGE South Strip',v_conc),
    ('Hotel Theodore Seattle Desk','Hotel Theodore','US','https://www.hoteltheodore.com/',NULL,'reservations@hoteltheodore.com','+12066211000',NULL,'Downtown','Seattle','Washington','US',47.6095,-122.3345,'1531 Seventh Avenue, Seattle, WA 98101','BOOKER_DEMAND US Seattle mid HOSPITALITY Downtown',v_hosp),
    ('The State Hotel Desk','The State Hotel','US','https://www.thestatehotel.com/',NULL,'reservations@thestatehotel.com','+12064822000',NULL,'Pioneer Square','Seattle','Washington','US',47.6015,-122.334,'486 Howell Street, Seattle, WA 98101','BOOKER_DEMAND US Seattle mid HOSPITALITY Pioneer Square',v_hosp),
    ('Kimpton Hotel Monaco Seattle Desk','Kimpton Hotel Monaco Seattle','US','https://www.monaco-seattle.com/',NULL,'reservations@monaco-seattle.com','+12066218900',NULL,'Downtown','Seattle','Washington','US',47.6085,-122.3335,'1101 Fourth Avenue, Seattle, WA 98101','BOOKER_DEMAND US Seattle mid HOSPITALITY Downtown',v_hosp),
    ('Hotel Andra Seattle Desk','Hotel Ändra','US','https://www.hotelandra.com/',NULL,'reservations@hotelandra.com','+12064488600',NULL,'Belltown','Seattle','Washington','US',47.6135,-122.3405,'2000 Fourth Avenue, Seattle, WA 98121','BOOKER_DEMAND US Seattle mid HOSPITALITY Belltown',v_hosp),
    ('The Edgewater Hotel Desk','The Edgewater','US','https://www.edgewaterhotel.com/',NULL,'reservations@edgewaterhotel.com','+12067284000',NULL,'Waterfront','Seattle','Washington','US',47.6125,-122.3525,'2411 Alaskan Way, Seattle, WA 98121','BOOKER_DEMAND US Seattle mid HOSPITALITY Waterfront',v_hosp),
    ('Motif Seattle Desk','Motif Seattle','US','https://www.motifseattle.com/',NULL,'reservations@motifseattle.com','+12062821000',NULL,'Downtown','Seattle','Washington','US',47.608,-122.333,'1415 Fifth Avenue, Seattle, WA 98101','BOOKER_DEMAND US Seattle mid HOSPITALITY Downtown',v_hosp),
    ('Palihotel Seattle Desk','Palihotel Seattle','US','https://www.palisociety.com/hotels/seattle/',NULL,'seattle@palisociety.com','+12066231111',NULL,'Downtown','Seattle','Washington','US',47.6088,-122.3355,'107 Spring Street, Seattle, WA 98104','BOOKER_DEMAND US Seattle mid HOSPITALITY Downtown',v_hosp),
    ('Hotel Max Seattle Desk','Hotel Max','US','https://www.hotelmaxseattle.com/',NULL,'reservations@hotelmaxseattle.com','+12064844411',NULL,'Downtown','Seattle','Washington','US',47.6125,-122.3375,'620 Stewart Street, Seattle, WA 98101','BOOKER_DEMAND US Seattle mid HOSPITALITY Downtown',v_hosp),
    ('Ace Hotel Seattle Desk','Ace Hotel Seattle','US','https://www.acehotel.com/seattle/',NULL,'reservations.seattle@acehotel.com','+12062026100',NULL,'Belltown','Seattle','Washington','US',47.6145,-122.3455,'2423 First Avenue, Seattle, WA 98121','BOOKER_DEMAND US Seattle mid HOSPITALITY Belltown',v_hosp),
    ('The Charter Hotel Concierge','The Charter Hotel Seattle','US','https://www.thecharterhotel.com/',NULL,'reservations@thecharterhotel.com','+12062565000',NULL,'Downtown','Seattle','Washington','US',47.6075,-122.3335,'808 Howell Street, Seattle, WA 98101','BOOKER_DEMAND US Seattle mid CONCIERGE Downtown',v_conc),
    ('The LINE Austin Desk','The LINE Austin','US','https://www.thelinehotel.com/austin/',NULL,'reservations.austin@thelinehotel.com','+15124747000',NULL,'Downtown','Austin','Texas','US',30.2695,-97.7405,'111 East Cesar Chavez Street, Austin, TX 78701','BOOKER_DEMAND US Austin mid HOSPITALITY Downtown',v_hosp),
    ('Hotel Magdalena Desk','Hotel Magdalena','US','https://www.hotelmagdalena.com/',NULL,'reservations@hotelmagdalena.com','+15124723000',NULL,'Zilker','Austin','Texas','US',30.2645,-97.7725,'1101 South Lamar Boulevard, Austin, TX 78704','BOOKER_DEMAND US Austin mid HOSPITALITY Zilker',v_hosp),
    ('Carpenter Hotel Desk','Carpenter Hotel','US','https://www.carpenterhotel.com/',NULL,'reservations@carpenterhotel.com','+15128725000',NULL,'South Lamar','Austin','Texas','US',30.2505,-97.7695,'400 Josephine Street, Austin, TX 78704','BOOKER_DEMAND US Austin mid HOSPITALITY South Lamar',v_hosp),
    ('Hotel Van Zandt Desk','Kimpton Hotel Van Zandt','US','https://www.hotelvanzandt.com/',NULL,'reservations@hotelvanzandt.com','+15125425400',NULL,'Rainey Street','Austin','Texas','US',30.2595,-97.7385,'605 Davis Street, Austin, TX 78701','BOOKER_DEMAND US Austin mid HOSPITALITY Rainey',v_hosp),
    ('South Congress Hotel Desk','South Congress Hotel','US','https://www.southcongresshotel.com/',NULL,'reservations@southcongresshotel.com','+15129208000',NULL,'South Congress','Austin','Texas','US',30.2505,-97.7495,'1603 South Congress Avenue, Austin, TX 78704','BOOKER_DEMAND US Austin mid HOSPITALITY SoCo',v_hosp),
    ('Austin Proper Hotel Desk','Austin Proper Hotel','US','https://www.properhotel.com/austin/',NULL,'austin@properhotel.com','+15124785000',NULL,'Downtown','Austin','Texas','US',30.269,-97.7425,'600 West Second Street, Austin, TX 78701','BOOKER_DEMAND US Austin mid HOSPITALITY Downtown',v_hosp),
    ('Hotel Ella Desk','Hotel Ella','US','https://www.hotelella.com/',NULL,'reservations@hotelella.com','+15124754500',NULL,'West Campus','Austin','Texas','US',30.2855,-97.7435,'1900 Rio Grande Street, Austin, TX 78705','BOOKER_DEMAND US Austin mid HOSPITALITY West Campus',v_hosp),
    ('Hotel San Jose Desk','Hotel San José','US','https://www.sanjosehotel.com/',NULL,'reservations@sanjosehotel.com','+15124447323',NULL,'South Congress','Austin','Texas','US',30.2495,-97.749,'1316 South Congress Avenue, Austin, TX 78704','BOOKER_DEMAND US Austin mid HOSPITALITY SoCo',v_hosp),
    ('Commodore Perry Estate Desk','Commodore Perry Estate','US','https://www.auberge.com/commodore-perry/',NULL,'reservations@commodoreperryestate.com','+15123878000',NULL,'North Central','Austin','Texas','US',30.3075,-97.7275,'4100 Red River Street, Austin, TX 78751','BOOKER_DEMAND US Austin mid HOSPITALITY Hyde Park',v_hosp),
    ('Austin Motel Concierge','Austin Motel','US','https://www.austinmotel.com/',NULL,'reservations@austinmotel.com','+15124411158',NULL,'South Congress','Austin','Texas','US',30.249,-97.7495,'1220 South Congress Avenue, Austin, TX 78704','BOOKER_DEMAND US Austin mid CONCIERGE SoCo',v_conc),
    ('The Joule Dallas Desk','The Joule','US','https://www.thejouledallas.com/',NULL,'reservations@thejouledallas.com','+12147488000',NULL,'Downtown','Dallas','Texas','US',32.7805,-96.7985,'1530 Main Street, Dallas, TX 75201','BOOKER_DEMAND US Dallas mid HOSPITALITY Downtown',v_hosp),
    ('Virgin Hotels Dallas Desk','Virgin Hotels Dallas','US','https://virginhotels.com/dallas/',NULL,'reservations.dallas@virginhotels.com','+12142305000',NULL,'Design District','Dallas','Texas','US',32.7905,-96.8255,'1445 Stemmons Freeway, Dallas, TX 75207','BOOKER_DEMAND US Dallas mid HOSPITALITY Design District',v_hosp),
    ('Kimpton Pittman Hotel Desk','Kimpton Pittman Hotel','US','https://www.pittmanhoteldallas.com/',NULL,'reservations@pittmanhoteldallas.com','+12142225000',NULL,'Deep Ellum','Dallas','Texas','US',32.7845,-96.7835,'2551 Elm Street, Dallas, TX 75226','BOOKER_DEMAND US Dallas mid HOSPITALITY Deep Ellum',v_hosp),
    ('Hotel Zaza Dallas Desk','Hotel ZaZa Dallas','US','https://www.hotelzaza.com/dallas/',NULL,'dallas@hotelzaza.com','+12144688300',NULL,'Uptown','Dallas','Texas','US',32.8015,-96.8055,'2332 Leonard Street, Dallas, TX 75201','BOOKER_DEMAND US Dallas mid HOSPITALITY Uptown',v_hosp),
    ('The Adolphus Dallas Desk','The Adolphus','US','https://www.hoteladolphus.com/',NULL,'reservations@hoteladolphus.com','+12147428200',NULL,'Downtown','Dallas','Texas','US',32.78,-96.7995,'1321 Commerce Street, Dallas, TX 75202','BOOKER_DEMAND US Dallas mid HOSPITALITY Downtown',v_hosp),
    ('Hall Arts Hotel Desk','Hall Arts Hotel Autograph Collection','US','https://www.hallartshotel.com/',NULL,'reservations@hallartshotel.com','+12141155000',NULL,'Arts District','Dallas','Texas','US',32.7895,-96.7985,'1015 Elm Street, Dallas, TX 75202','BOOKER_DEMAND US Dallas mid HOSPITALITY Arts District',v_hosp),
    ('Thompson Dallas Desk','Thompson Dallas','US','https://www.thompsonhotels.com/hotels/dallas',NULL,'reservations.dallas@thompsonhotels.com','+12142425000',NULL,'Uptown','Dallas','Texas','US',32.7885,-96.8005,'209 Browder Street, Dallas, TX 75201','BOOKER_DEMAND US Dallas mid HOSPITALITY Downtown',v_hosp),
    ('Canopy Dallas Uptown Desk','Canopy by Hilton Dallas Uptown','US','https://www.hilton.com/en/hotels/dalupcy-canopy-dallas-uptown/',NULL,'dalupcy_reservations@hilton.com','+12144158000',NULL,'Uptown','Dallas','Texas','US',32.801,-96.805,'2950 North Harwood Street, Dallas, TX 75201','BOOKER_DEMAND US Dallas mid HOSPITALITY Uptown',v_hosp),
    ('Graduate Dallas Desk','Graduate Dallas','US','https://graduatehotels.com/dallas/',NULL,'dallas@graduatehotels.com','+12146315000',NULL,'Downtown','Dallas','Texas','US',32.7795,-96.7975,'1401 Commerce Street, Dallas, TX 75201','BOOKER_DEMAND US Dallas mid HOSPITALITY Downtown',v_hosp),
    ('Hotel Crescent Court Concierge','Hotel Crescent Court','US','https://www.crescentcourt.com/',NULL,'reservations@crescentcourt.com','+12148713200',NULL,'Uptown','Dallas','Texas','US',32.7945,-96.8035,'400 Crescent Court, Dallas, TX 75201','BOOKER_DEMAND US Dallas mid CONCIERGE Uptown',v_conc),
    ('Rove Downtown Dubai Desk','Rove Downtown Dubai','AE','https://www.rovehotels.com/hotels/downtown-dubai/',NULL,'downtown@rovehotels.com','+97143299900',NULL,'Downtown Dubai','Dubai','Dubai','AE',25.1972,55.2744,'Financial Center Road, Downtown Dubai','BOOKER_DEMAND AE Dubai mid HOSPITALITY Downtown',v_hosp),
    ('Rove City Walk Desk','Rove City Walk','AE','https://www.rovehotels.com/hotels/city-walk/',NULL,'citywalk@rovehotels.com','+97142479900',NULL,'City Walk','Dubai','Dubai','AE',25.2075,55.2635,'Al Safa Street, City Walk, Dubai','BOOKER_DEMAND AE Dubai mid HOSPITALITY City Walk',v_hosp),
    ('Vida Downtown Dubai Desk','Vida Downtown Dubai','AE','https://www.vidahotels.com/en/vida-downtown',NULL,'reservations.vidadowntown@emaar.com','+97148886888',NULL,'Downtown Dubai','Dubai','Dubai','AE',25.1955,55.2765,'Sheikh Mohammed bin Rashid Boulevard, Dubai','BOOKER_DEMAND AE Dubai mid HOSPITALITY Downtown',v_hosp),
    ('Zabeel House The Greens Desk','Zabeel House by Jumeirah The Greens','AE','https://www.jumeirah.com/en/stay/dubai/zabeel-house-the-greens',NULL,'zhreservations@jumeirah.com','+97145838888',NULL,'The Greens','Dubai','Dubai','AE',25.0935,55.1715,'Street 1, The Greens, Dubai','BOOKER_DEMAND AE Dubai mid HOSPITALITY The Greens',v_hosp),
    ('La Ville Hotel City Walk Desk','La Ville Hotel & Suites City Walk','AE','https://www.lavillehotel.com/',NULL,'reservations@lavillehotel.com','+97144038888',NULL,'City Walk','Dubai','Dubai','AE',25.2085,55.2625,'Al Wasl Road, City Walk, Dubai','BOOKER_DEMAND AE Dubai mid HOSPITALITY City Walk',v_hosp),
    ('Media One Hotel Desk','Media One Hotel','AE','https://www.mediaonehotel.com/',NULL,'reservations@mediaonehotel.com','+97144271000',NULL,'Dubai Media City','Dubai','Dubai','AE',25.0945,55.1565,'Dubai Media City, Dubai','BOOKER_DEMAND AE Dubai mid HOSPITALITY Media City',v_hosp),
    ('Manzil Downtown Dubai Desk','Manzil Downtown Dubai','AE','https://www.vida-hotels.com/en/manzil-downtown',NULL,'reservations.manzil@emaar.com','+97144285888',NULL,'Downtown Dubai','Dubai','Dubai','AE',25.1965,55.2755,'Sheikh Mohammed bin Rashid Boulevard, Dubai','BOOKER_DEMAND AE Dubai mid HOSPITALITY Downtown',v_hosp),
    ('Hotel Indigo Dubai Downtown Desk','Hotel Indigo Dubai Downtown','AE','https://www.ihg.com/hotelindigo/hotels/gb/en/dubai/dxbdt/hoteldetail',NULL,'reservations.dxbdt@ihg.com','+97145270000',NULL,'Downtown Dubai','Dubai','Dubai','AE',25.1885,55.2705,'Trade Centre Area, Dubai','BOOKER_DEMAND AE Dubai mid HOSPITALITY Downtown',v_hosp),
    ('The H Dubai Desk','The H Dubai','AE','https://www.hhhotelgroup.com/the-h-dubai',NULL,'reservations@thehhotel.com','+97145018888',NULL,'Sheikh Zayed Road','Dubai','Dubai','AE',25.2245,55.2825,'1 Sheikh Zayed Road, Dubai','BOOKER_DEMAND AE Dubai mid HOSPITALITY SZR',v_hosp),
    ('Pullman Dubai Downtown Desk','Pullman Dubai Downtown','AE','https://all.accor.com/hotel/9182/index.en.shtml',NULL,'H9182@accor.com','+97143181111',NULL,'Business Bay','Dubai','Dubai','AE',25.1855,55.2655,'Business Bay, Dubai','BOOKER_DEMAND AE Dubai mid HOSPITALITY Business Bay',v_hosp),
    ('TRYP Dubai Desk','TRYP by Wyndham Dubai','AE','https://www.wyndhamhotels.com/tryp/dubai-united-arab-emirates/tryp-by-wyndham-dubai',NULL,'reservations.trypdubai@wyndham.com','+97144500000',NULL,'Barsha Heights','Dubai','Dubai','AE',25.0985,55.1755,'Barsha Heights, Dubai','BOOKER_DEMAND AE Dubai mid HOSPITALITY Barsha Heights',v_hosp),
    ('Address Dubai Mall Concierge','Address Dubai Mall','AE','https://www.addresshotels.com/en/hotels/address-dubai-mall/',NULL,'reservations.addm@emaar.com','+97144388888',NULL,'Downtown Dubai','Dubai','Dubai','AE',25.1978,55.2795,'Downtown Dubai, Dubai','BOOKER_DEMAND AE Dubai mid CONCIERGE Downtown',v_conc),
    ('Aloft Abu Dhabi Desk','Aloft Abu Dhabi','AE','https://www.marriott.com/hotels/travel/auhxa-aloft-abu-dhabi/',NULL,'auhxa.reservations@marriott.com','+97126548888',NULL,'Al Zahiyah','Abu Dhabi','Abu Dhabi','AE',24.4945,54.3775,'Abu Dhabi Mall Area, Abu Dhabi','BOOKER_DEMAND AE Abu Dhabi mid HOSPITALITY Al Zahiyah',v_hosp),
    ('Centro Yas Island Desk','Centro Yas Island by Rotana','AE','https://www.rotana.com/centrorotana/unitedarabemirates/abudhabi/centroyasisland',NULL,'centro.yasisland@rotana.com','+97126564444',NULL,'Yas Island','Abu Dhabi','Abu Dhabi','AE',24.4915,54.6065,'Yas Island, Abu Dhabi','BOOKER_DEMAND AE Abu Dhabi mid HOSPITALITY Yas Island',v_hosp),
    ('Crowne Plaza Yas Island Desk','Crowne Plaza Abu Dhabi Yas Island','AE','https://www.ihg.com/crowneplaza/hotels/gb/en/abu-dhabi/auhyi/hoteldetail',NULL,'reservations.auhyi@ihg.com','+97126563000',NULL,'Yas Island','Abu Dhabi','Abu Dhabi','AE',24.4955,54.6055,'Yas Island, Abu Dhabi','BOOKER_DEMAND AE Abu Dhabi mid HOSPITALITY Yas Island',v_hosp),
    ('Novotel Abu Dhabi Al Bustan Desk','Novotel Abu Dhabi Al Bustan','AE','https://all.accor.com/hotel/6542/index.en.shtml',NULL,'H6542@accor.com','+97126333355',NULL,'Al Bustan','Abu Dhabi','Abu Dhabi','AE',24.4625,54.3855,'Sultan Bin Zayed the First Street, Abu Dhabi','BOOKER_DEMAND AE Abu Dhabi mid HOSPITALITY Al Bustan',v_hosp),
    ('Beach Rotana Abu Dhabi Desk','Beach Rotana','AE','https://www.rotana.com/rotanahotelandresorts/unitedarabemirates/abudhabi/beachrotana',NULL,'beach.hotel@rotana.com','+97126977777',NULL,'Al Zahiyah','Abu Dhabi','Abu Dhabi','AE',24.494,54.3835,'Tourist Club Area, Abu Dhabi','BOOKER_DEMAND AE Abu Dhabi mid HOSPITALITY Corniche',v_hosp),
    ('Traders Qaryat Al Beri Desk','Traders Hotel Qaryat Al Beri','AE','https://www.shangri-la.com/abudhabi/traders/',NULL,'slab@shangri-la.com','+97126978888',NULL,'Qaryat Al Beri','Abu Dhabi','Abu Dhabi','AE',24.4185,54.4955,'Qaryat Al Beri, Abu Dhabi','BOOKER_DEMAND AE Abu Dhabi mid HOSPITALITY Al Maqtaa',v_hosp),
    ('The WB Abu Dhabi Desk','The WB Abu Dhabi Curio Collection','AE','https://www.hilton.com/en/hotels/auhwbci-the-wb-abu-dhabi/',NULL,'auhwbci_reservations@hilton.com','+97124922000',NULL,'Yas Island','Abu Dhabi','Abu Dhabi','AE',24.4885,54.6085,'Yas Island, Abu Dhabi','BOOKER_DEMAND AE Abu Dhabi mid HOSPITALITY Yas Island',v_hosp),
    ('Grand Millennium Al Wahda Concierge','Grand Millennium Al Wahda','AE','https://www.millenniumhotels.com/en/abu-dhabi/grand-millennium-al-wahda/',NULL,'reservations.gmaw@millenniumhotels.com','+97124439999',NULL,'Al Wahda','Abu Dhabi','Abu Dhabi','AE',24.4695,54.3705,'Hazza Bin Zayed the First Street, Abu Dhabi','BOOKER_DEMAND AE Abu Dhabi mid CONCIERGE Al Wahda',v_conc),
    ('Narcissus Hotel Riyadh Desk','Narcissus Hotel & Spa','SA','https://www.narcissushotel.com/',NULL,'reservations@narcissushotel.com','+966114600000',NULL,'Olaya','Riyadh','Riyadh Province','SA',24.6945,46.6855,'King Fahd Road, Olaya, Riyadh','BOOKER_DEMAND SA Riyadh mid HOSPITALITY Olaya',v_hosp),
    ('Courtyard Riyadh Olaya Desk','Courtyard by Marriott Riyadh Olaya','SA','https://www.marriott.com/hotels/travel/ruhcy-courtyard-riyadh-olaya/',NULL,'ruhcy.reservations@marriott.com','+966112111111',NULL,'Olaya','Riyadh','Riyadh Province','SA',24.6915,46.685,'Olaya Street, Riyadh','BOOKER_DEMAND SA Riyadh mid HOSPITALITY Olaya',v_hosp),
    ('Mövenpick Hotel Riyadh Desk','Mövenpick Hotel Riyadh','SA','https://www.movenpick.com/en/middle-east/saudi-arabia/riyadh/hotel-riyadh/',NULL,'hotel.riyadh@movenpick.com','+966112111000',NULL,'Diplomatic Quarter','Riyadh','Riyadh Province','SA',24.6805,46.6255,'Diplomatic Quarter, Riyadh','BOOKER_DEMAND SA Riyadh mid HOSPITALITY DQ',v_hosp),
    ('Crowne Plaza Riyadh RDC Desk','Crowne Plaza Riyadh RDC Hotel & Convention','SA','https://www.ihg.com/crowneplaza/hotels/gb/en/riyadh/ruhcp/hoteldetail',NULL,'reservations.ruhcp@ihg.com','+966114800000',NULL,'Al Hada','Riyadh','Riyadh Province','SA',24.7205,46.6755,'King Abdullah Road, Riyadh','BOOKER_DEMAND SA Riyadh mid HOSPITALITY North',v_hosp),
    ('Hyatt Place Riyadh Sulaimania Desk','Hyatt Place Riyadh Sulaimania','SA','https://www.hyatt.com/en-US/hotel/saudi-arabia/hyatt-place-riyadh-sulaimania/ruhzs',NULL,'riyadh.sulaimania@hyatt.com','+966112100000',NULL,'Sulaimania','Riyadh','Riyadh Province','SA',24.7005,46.6955,'Prince Sultan Bin Abdulaziz Road, Riyadh','BOOKER_DEMAND SA Riyadh mid HOSPITALITY Sulaimania',v_hosp),
    ('Centro Waha Riyadh Desk','Centro Waha by Rotana','SA','https://www.rotana.com/centrorotana/saudiarabia/riyadh/centrowaha',NULL,'centro.waha@rotana.com','+966114800800',NULL,'Al Olaya','Riyadh','Riyadh Province','SA',24.7105,46.6705,'Northern Ring Road, Riyadh','BOOKER_DEMAND SA Riyadh mid HOSPITALITY North',v_hosp),
    ('Braira Olaya Desk','Braira Olaya Hotel','SA','https://www.braira.com/hotels/braira-olaya',NULL,'olaya@braira.com','+966112100800',NULL,'Olaya','Riyadh','Riyadh Province','SA',24.6935,46.6825,'Olaya District, Riyadh','BOOKER_DEMAND SA Riyadh mid HOSPITALITY Olaya',v_hosp),
    ('Frasers Suites Riyadh Concierge','Frasers Suites Riyadh','SA','https://www.frasershospitality.com/en/saudi-arabia/riyadh/frasers-suites-riyadh/',NULL,'reservations.riyadh@frasershospitality.com','+966112199999',NULL,'Olaya','Riyadh','Riyadh Province','SA',24.6925,46.6845,'Olaya, Riyadh','BOOKER_DEMAND SA Riyadh mid CONCIERGE Olaya',v_conc),
    ('Mövenpick City Star Jeddah Desk','Mövenpick Hotel City Star Jeddah','SA','https://www.movenpick.com/en/middle-east/saudi-arabia/jeddah/hotel-city-star-jeddah/',NULL,'hotel.citystar.jeddah@movenpick.com','+966126600000',NULL,'Al Andalus','Jeddah','Makkah Province','SA',21.5655,39.1555,'King Abdullah Road, Jeddah','BOOKER_DEMAND SA Jeddah mid HOSPITALITY Al Andalus',v_hosp),
    ('Crowne Plaza Jeddah Desk','Crowne Plaza Jeddah','SA','https://www.ihg.com/crowneplaza/hotels/gb/en/jeddah/jedcp/hoteldetail',NULL,'reservations.jedcp@ihg.com','+966126600800',NULL,'Al Hamra','Jeddah','Makkah Province','SA',21.5405,39.1655,'Palestine Road, Jeddah','BOOKER_DEMAND SA Jeddah mid HOSPITALITY Al Hamra',v_hosp),
    ('Shada Hotel Jeddah Desk','Shada Hotel','SA','https://www.shadahotel.com/',NULL,'reservations@shadahotel.com','+966126600111',NULL,'Al Rawdah','Jeddah','Makkah Province','SA',21.5555,39.1455,'Prince Sultan Road, Jeddah','BOOKER_DEMAND SA Jeddah mid HOSPITALITY Al Rawdah',v_hosp),
    ('Radisson Blu Jeddah Al Salam Desk','Radisson Blu Hotel Jeddah Al Salam','SA','https://www.radissonhotels.com/en-us/hotels/radisson-blu-jeddah-al-salam',NULL,'info.jeddahalsalam@radissonblu.com','+966126600222',NULL,'Al Salamah','Jeddah','Makkah Province','SA',21.5755,39.1355,'King Abdulaziz Road, Jeddah','BOOKER_DEMAND SA Jeddah mid HOSPITALITY Al Salamah',v_hosp),
    ('Golden Tulip Alhamra Desk','Golden Tulip Jeddah Alhamra','SA','https://www.goldentulip.com/en-us/hotels/golden-tulip-jeddah-alhamra',NULL,'info@goldentulipjeddah.com','+966126600333',NULL,'Al Hamra','Jeddah','Makkah Province','SA',21.5425,39.1625,'Corniche Road, Jeddah','BOOKER_DEMAND SA Jeddah mid HOSPITALITY Al Hamra',v_hosp),
    ('Swissotel Living Jeddah Concierge','Swissôtel Living Jeddah','SA','https://www.swissotel.com/hotels/jeddah-living/',NULL,'reservations.jeddah@swissotel.com','+966126600444',NULL,'Obhur','Jeddah','Makkah Province','SA',21.7205,39.1055,'Obhur, Jeddah','BOOKER_DEMAND SA Jeddah mid CONCIERGE Obhur',v_conc),
    ('Mövenpick West Bay Doha Desk','Mövenpick Hotel West Bay Doha','QA','https://www.movenpick.com/en/middle-east/qatar/doha/hotel-west-bay-doha/',NULL,'hotel.westbay.doha@movenpick.com','+97444966666',NULL,'West Bay','Doha','Doha','QA',25.3255,51.5305,'West Bay, Doha','BOOKER_DEMAND QA Doha mid HOSPITALITY West Bay',v_hosp),
    ('Ascott Doha Desk','Ascott Doha','QA','https://www.the-ascott.com/en/qatar/doha/ascott-doha/',NULL,'enquiry.doha@the-ascott.com','+97444228888',NULL,'West Bay','Doha','Doha','QA',25.3205,51.5285,'Omar Al Mukhtar Street, West Bay, Doha','BOOKER_DEMAND QA Doha mid HOSPITALITY West Bay',v_hosp),
    ('Retaj Al Rayyan Desk','Retaj Al Rayyan Hotel','QA','https://www.retaj.com/al-rayyan/',NULL,'reservations.alrayyan@retaj.com','+97444448888',NULL,'Al Rayyan','Doha','Doha','QA',25.2905,51.4505,'Al Rayyan, Doha','BOOKER_DEMAND QA Doha mid HOSPITALITY Al Rayyan',v_hosp),
    ('Ezdan Hotel Doha Desk','Ezdan Hotel Towers','QA','https://www.ezdanhotels.com/',NULL,'reservations@ezdanhotels.com','+97444969999',NULL,'West Bay','Doha','Doha','QA',25.3185,51.5255,'West Bay Lagoon, Doha','BOOKER_DEMAND QA Doha mid HOSPITALITY West Bay',v_hosp),
    ('Mercure Grand Doha Desk','Mercure Grand Hotel Doha City Centre','QA','https://all.accor.com/hotel/B0K8/index.en.shtml',NULL,'HB0K8@accor.com','+97444253333',NULL,'Al Sadd','Doha','Doha','QA',25.2805,51.5105,'Al Sadd, Doha','BOOKER_DEMAND QA Doha mid HOSPITALITY Al Sadd',v_hosp),
    ('Crowne Plaza Doha West Bay Desk','Crowne Plaza Doha - The Business Park','QA','https://www.ihg.com/crowneplaza/hotels/gb/en/doha/dohcp/hoteldetail',NULL,'reservations.dohcp@ihg.com','+97444070000',NULL,'West Bay','Doha','Doha','QA',25.3225,51.5275,'West Bay, Doha','BOOKER_DEMAND QA Doha mid HOSPITALITY West Bay',v_hosp),
    ('Wyndham Grand Regency Doha Desk','Wyndham Grand Regency Doha','QA','https://www.wyndhamhotels.com/wyndham-grand/doha-qatar/wyndham-grand-regency-doha',NULL,'reservations.doha@wyndham.com','+97444344444',NULL,'Al Sadd','Doha','Doha','QA',25.2855,51.5125,'Al Sadd Street, Doha','BOOKER_DEMAND QA Doha mid HOSPITALITY Al Sadd',v_hosp),
    ('The Curve Hotel Doha Concierge','The Curve Hotel','QA','https://www.thecurvehoteldoha.com/',NULL,'reservations@thecurvehoteldoha.com','+97444446666',NULL,'Lusail','Doha','Doha','QA',25.4105,51.5055,'Lusail, Doha','BOOKER_DEMAND QA Doha mid CONCIERGE Lusail',v_conc),
    ('The Domain Bahrain Desk','The Domain Hotel & Spa','BH','https://www.thedomainhotels.com/',NULL,'reservations@thedomainhotels.com','+97316000000',NULL,'Seef','Manama','Capital Governorate','BH',26.2355,50.5405,'Building 113, Road 2803, Seef, Manama','BOOKER_DEMAND BH Bahrain mid HOSPITALITY Seef',v_hosp),
    ('Ramee Grand Hotel Desk','Ramee Grand Hotel & Spa','BH','https://www.rameehotels.com/ramee-grand-hotel-spa/',NULL,'reservations@rameegrand.com','+97317111111',NULL,'Seef','Manama','Capital Governorate','BH',26.2335,50.5385,'Building 11, Road 2803, Seef District, Manama','BOOKER_DEMAND BH Bahrain mid HOSPITALITY Seef',v_hosp),
    ('Crowne Plaza Bahrain Desk','Crowne Plaza Bahrain','BH','https://www.ihg.com/crowneplaza/hotels/gb/en/manama/bahcp/hoteldetail',NULL,'reservations.bahcp@ihg.com','+97317531122',NULL,'Diplomatic Area','Manama','Capital Governorate','BH',26.2385,50.5855,'Sheikh Khalifa Bin Salman Highway, Manama','BOOKER_DEMAND BH Bahrain mid HOSPITALITY Diplomatic',v_hosp),
    ('Art Rotana Amwaj Desk','Art Rotana Amwaj Islands','BH','https://www.rotana.com/rotanahotelandresorts/bahrain/amwajislands/artrotana',NULL,'art.hotel@rotana.com','+97316036000',NULL,'Amwaj Islands','Manama','Muharraq Governorate','BH',26.2885,50.6655,'Amwaj Islands, Bahrain','BOOKER_DEMAND BH Bahrain mid HOSPITALITY Amwaj',v_hosp),
    ('The Gulf Hotel Bahrain Desk','The Gulf Hotel Bahrain','BH','https://www.gulfhotelbahrain.com/',NULL,'reservations@gulfhotelbahrain.com','+97317713000',NULL,'Adliya','Manama','Capital Governorate','BH',26.2205,50.5805,'Building 11, Road 3801, Adliya, Manama','BOOKER_DEMAND BH Bahrain mid HOSPITALITY Adliya',v_hosp),
    ('Fraser Suites Seef Concierge','Fraser Suites Seef Bahrain','BH','https://www.frasershospitality.com/en/bahrain/manama/fraser-suites-seef-bahrain/',NULL,'reservations.seef@frasershospitality.com','+97317587777',NULL,'Seef','Manama','Capital Governorate','BH',26.2365,50.5425,'Building 2025, Road 1453, Seef, Manama','BOOKER_DEMAND BH Bahrain mid CONCIERGE Seef',v_conc)
  ) AS t(
    display_name, legal_name, country, website_url, website_domain, email, phone, whatsapp,
    base_label, city, region, country_code, lat, lng, formatted_address, note, service_type_id
  )
  LOOP
    IF EXISTS (
      SELECT 1 FROM organizations o WHERE o.archived_at IS NULL AND (
        (lower(o.display_name) = lower(r.display_name) AND o.legal_country_code = r.country)
        OR (r.email IS NOT NULL AND lower(coalesce(o.primary_email, '')) = lower(r.email)
            AND o.notes_public LIKE 'BOOKER_DEMAND%')
      )
    ) THEN
      skipped := skipped + 1;
      CONTINUE;
    END IF;

    INSERT INTO organizations (
      display_name, legal_name, legal_country_code, legal_city, legal_region,
      website_url, website_domain, primary_email, primary_phone_e164, primary_whatsapp_e164,
      notes_public, is_test, created_by_user_id
    ) VALUES (
      r.display_name, r.legal_name, r.country, r.city, r.region,
      r.website_url, r.website_domain, r.email, r.phone, COALESCE(r.whatsapp, r.phone),
      r.note, false, v_admin
    ) RETURNING id INTO v_org;

    INSERT INTO organization_capabilities (organization_id, capability)
    VALUES (v_org, 'BUYER') ON CONFLICT DO NOTHING;
    INSERT INTO partnerships (organization_id, relationship_status, status_changed_at)
    VALUES (v_org, 'LEAD', now());
    INSERT INTO offerings (organization_id, service_type_id, operational_status)
    VALUES (v_org, r.service_type_id, 'UNKNOWN');
    INSERT INTO organization_locations (
      organization_id, label, location_kind, city, region, country_code, lat, lng, formatted_address, is_primary
    ) VALUES (v_org, r.base_label, 'OPS_BASE', r.city, r.region, r.country_code, r.lat, r.lng, r.formatted_address, true);
    INSERT INTO organization_contacts (
      organization_id, full_name, contact_type, title, email, phone_e164, is_primary
    ) VALUES (
      v_org, 'Guest / Concierge desk', 'Other', 'Bookings desk', r.email, r.phone, true
    );
    inserted := inserted + 1;
  END LOOP;
  RAISE NOTICE 'US+ME mid bookers: inserted=% skipped=%', inserted, skipped;
END $$;
