-- VL Bookers: mid-upper Asia-Pacific desks + secondary spillover cities
-- Not ultra-flagship, not budget 3★ — boutique / solid 4★ booking desks

DO $$
DECLARE
  v_hosp uuid := '8724134a-2249-4d87-83aa-167db279aab8';
  v_conc uuid := 'e857fe35-436d-49c1-a520-38ac9a199ea6';
  v_admin uuid := 'b3105232-0857-4eed-b022-d8147683c059';
  r record;
  v_org uuid;
  inserted int := 0;
  skipped int := 0;
BEGIN
  FOR r IN SELECT * FROM (VALUES
    -- ========== SINGAPORE ==========
    ('PARKROYAL Collection Pickering Desk','PARKROYAL COLLECTION Pickering','SG','https://www.panpacific.com/en/hotels-and-resorts/pr-collection-pickering.html',NULL,'reserve.prsps@parkroyalcollection.com','+6568098888',NULL,'Upper Pickering','Singapore','Singapore','SG',1.285,103.846,'3 Upper Pickering Street, Singapore 058289','BOOKER_DEMAND APAC Singapore mid HOSPITALITY Chinatown',v_hosp),
    ('PARKROYAL on Beach Road Desk','PARKROYAL on Beach Road','SG','https://www.panpacific.com/en/hotels-and-resorts/pr-beach-road.html',NULL,'reserve.prsin@parkroyalhotels.com','+6565081188',NULL,'Beach Road','Singapore','Singapore','SG',1.300,103.860,'7500 Beach Road, Singapore 199591','BOOKER_DEMAND APAC Singapore mid HOSPITALITY Beach Road',v_hosp),
    ('Carlton Hotel Singapore Desk','Carlton Hotel Singapore','SG','https://www.carltonhotel.sg/',NULL,'reservations@carltonhotel.sg','+6563388333',NULL,'Bras Basah','Singapore','Singapore','SG',1.296,103.853,'76 Bras Basah Road, Singapore 189558','BOOKER_DEMAND APAC Singapore mid HOSPITALITY Civic District',v_hosp),
    ('Orchard Hotel Singapore Desk','Orchard Hotel Singapore','SG','https://www.millenniumhotels.com/en/singapore/orchard-hotel-singapore/',NULL,'reservations.orchard@millenniumhotels.com','+6567347766',NULL,'Orchard','Singapore','Singapore','SG',1.305,103.832,'442 Orchard Road, Singapore 238879','BOOKER_DEMAND APAC Singapore mid HOSPITALITY Orchard',v_hosp),
    ('Grand Copthorne Waterfront Desk','Grand Copthorne Waterfront','SG','https://www.millenniumhotels.com/en/singapore/grand-copthorne-waterfront/',NULL,'reservations.gcw@millenniumhotels.com','+6567330880',NULL,'Havelock','Singapore','Singapore','SG',1.289,103.837,'392 Havelock Road, Singapore 169663','BOOKER_DEMAND APAC Singapore mid HOSPITALITY River Valley',v_hosp),
    ('Naumi Hotel Singapore Desk','Naumi Hotel Singapore','SG','https://www.naumihotels.com/singapore/',NULL,'reservations.sg@naumihotels.com','+6564095777',NULL,'Bencoolen','Singapore','Singapore','SG',1.299,103.851,'41 Seah Street, Singapore 188396','BOOKER_DEMAND APAC Singapore mid HOSPITALITY Bugis',v_hosp),
    ('The Quincy Hotel Desk','The Quincy Hotel by Far East Hospitality','SG','https://www.stayfareast.com/en/hotels/the-quincy-hotel',NULL,'quincy.reservation@fareasthospitality.com','+6567396000',NULL,'Mount Elizabeth','Singapore','Singapore','SG',1.305,103.837,'22 Mount Elizabeth, Singapore 228517','BOOKER_DEMAND APAC Singapore mid HOSPITALITY Orchard',v_hosp),
    ('Hotel Indigo Singapore Katong Desk','Hotel Indigo Singapore Katong','SG','https://www.ihg.com/hotelindigo/hotels/us/en/singapore/sinka/hoteldetail',NULL,'sinka.reservations@ihg.com','+6567259088',NULL,'Katong','Singapore','Singapore','SG',1.306,103.904,'86 East Coast Road, Singapore 428788','BOOKER_DEMAND APAC Singapore mid HOSPITALITY East Coast',v_hosp),
    ('M Social Singapore Desk','M Social Singapore','SG','https://www.millenniumhotels.com/en/singapore/m-social-singapore/',NULL,'reservations.msocialsg@millenniumhotels.com','+6562300888',NULL,'Robertson Quay','Singapore','Singapore','SG',1.291,103.838,'90 Robertson Quay, Singapore 238259','BOOKER_DEMAND APAC Singapore mid HOSPITALITY Robertson Quay',v_hosp),
    ('The Warehouse Hotel Desk','The Warehouse Hotel','SG','https://www.thewarehousehotel.com/',NULL,'reservations@thewarehousehotel.com','+6562247101',NULL,'Robertson Quay','Singapore','Singapore','SG',1.290,103.837,'320 Havelock Road, Singapore 169619','BOOKER_DEMAND APAC Singapore mid HOSPITALITY Robertson Quay',v_hosp),
    ('Amara Singapore Desk','Amara Singapore','SG','https://singapore.amarahotels.com/',NULL,'singapore@amarahotels.com','+6568772777',NULL,'Tanjong Pagar','Singapore','Singapore','SG',1.275,103.844,'165 Tanjong Pagar Road, Singapore 088539','BOOKER_DEMAND APAC Singapore mid HOSPITALITY Tanjong Pagar',v_hosp),
    ('York Hotel Singapore Desk','York Hotel Singapore','SG','https://www.yorkhotel.com.sg/',NULL,'enquiry@yorkhotel.com.sg','+6567370511',NULL,'Mount Elizabeth','Singapore','Singapore','SG',1.305,103.836,'21 Mount Elizabeth, Singapore 228516','BOOKER_DEMAND APAC Singapore mid HOSPITALITY Orchard',v_hosp),
    ('Village Hotel Bugis Desk','Village Hotel Bugis','SG','https://www.stayfareast.com/en/hotels/village-hotel-bugis',NULL,'bugis.reservation@fareasthospitality.com','+6562972828',NULL,'Bugis','Singapore','Singapore','SG',1.301,103.856,'390 Victoria Street, Singapore 188061','BOOKER_DEMAND APAC Singapore mid HOSPITALITY Bugis',v_hosp),
    ('Hotel Jen Orchardgateway Desk','Hotel Jen Orchardgateway Singapore','SG','https://www.hoteljen.com/singapore/orchardgateway/',NULL,'reservations.jensgog@hoteljen.com','+6566348888',NULL,'Orchard','Singapore','Singapore','SG',1.301,103.839,'277 Orchard Road, Singapore 238858','BOOKER_DEMAND APAC Singapore mid HOSPITALITY Orchard',v_hosp),
    ('Sofitel Singapore City Centre Desk','Sofitel Singapore City Centre','SG','https://all.accor.com/hotel/8736/index.en.shtml',NULL,'H8736@accor.com','+6567098888',NULL,'Tanjong Pagar','Singapore','Singapore','SG',1.275,103.845,'9 Wallich Street, Singapore 078885','BOOKER_DEMAND APAC Singapore mid HOSPITALITY CBD',v_hosp),
    ('Novotel Singapore on Kitchener Desk','Novotel Singapore on Kitchener','SG','https://all.accor.com/hotel/6010/index.en.shtml',NULL,'H6010@accor.com','+6562970333',NULL,'Lavender','Singapore','Singapore','SG',1.311,103.858,'181 Kitchener Road, Singapore 208533','BOOKER_DEMAND APAC Singapore mid HOSPITALITY Little India',v_hosp),
    ('Mercure Singapore Bugis Desk','Mercure Singapore Bugis','SG','https://all.accor.com/hotel/B0X3/index.en.shtml',NULL,'HB0X3@accor.com','+6565282888',NULL,'Bugis','Singapore','Singapore','SG',1.299,103.855,'122 Middle Road, Singapore 188973','BOOKER_DEMAND APAC Singapore mid HOSPITALITY Bugis',v_hosp),
    ('InterContinental Robertson Quay Desk','InterContinental Singapore Robertson Quay','SG','https://www.ihg.com/intercontinental/hotels/us/en/singapore/sinkr/hoteldetail',NULL,'sinkr.reservations@ihg.com','+6568237600',NULL,'Robertson Quay','Singapore','Singapore','SG',1.290,103.838,'1 Nanson Road, Singapore 238909','BOOKER_DEMAND APAC Singapore mid HOSPITALITY Robertson Quay',v_hosp),
    ('Oasia Hotel Downtown Desk','Oasia Hotel Downtown Singapore','SG','https://www.stayfareast.com/en/hotels/oasia-hotel-downtown',NULL,'oasiadowntown.reservation@fareasthospitality.com','+6560223333',NULL,'Tanjong Pagar','Singapore','Singapore','SG',1.276,103.844,'100 Peck Seah Street, Singapore 079333','BOOKER_DEMAND APAC Singapore mid HOSPITALITY CBD',v_hosp),
    ('Rendezvous Hotel Singapore Desk','Rendezvous Hotel Singapore','SG','https://www.stayfareast.com/en/hotels/rendezvous-hotel-singapore',NULL,'rendezvous.reservation@fareasthospitality.com','+6563360220',NULL,'Bras Basah','Singapore','Singapore','SG',1.298,103.849,'9 Bras Basah Road, Singapore 189559','BOOKER_DEMAND APAC Singapore mid HOSPITALITY Museum District',v_hosp),
    ('The Outpost Hotel Sentosa Concierge','The Outpost Hotel Sentosa by Far East Hospitality','SG','https://www.stayfareast.com/en/hotels/the-outpost-hotel',NULL,'outpost.reservation@fareasthospitality.com','+6567222211',NULL,'Sentosa','Singapore','Singapore','SG',1.251,103.821,'30 Beach View, Sentosa, Singapore 098727','BOOKER_DEMAND APAC Singapore mid CONCIERGE Sentosa',v_conc),

    -- ========== HONG KONG ==========
    ('Hotel ICON Tsim Sha Tsui Desk','Hotel ICON','HK','https://www.hotel-icon.com/',NULL,'reservations@hotel-icon.com','+85234001000',NULL,'Tsim Sha Tsui','Hong Kong','Hong Kong','HK',22.297,114.179,'17 Science Museum Road, Tsim Sha Tsui East, Hong Kong','BOOKER_DEMAND APAC Hong Kong mid HOSPITALITY TST East',v_hosp),
    ('The Fleming Wan Chai Desk','The Fleming','HK','https://www.thefleming.com/',NULL,'reservations@thefleming.com','+85236072288',NULL,'Wan Chai','Hong Kong','Hong Kong','HK',22.278,114.173,'41 Fleming Road, Wan Chai, Hong Kong','BOOKER_DEMAND APAC Hong Kong mid HOSPITALITY Wan Chai',v_hosp),
    ('Hotel Jen Hong Kong Desk','Hotel Jen Hong Kong by Shangri-La','HK','https://www.hoteljen.com/hongkong/harbour/',NULL,'reservations.hjhk@hoteljen.com','+85229740228',NULL,'Kennedy Town','Hong Kong','Hong Kong','HK',22.282,114.128,'508 Queen''s Road West, Western District, Hong Kong','BOOKER_DEMAND APAC Hong Kong mid HOSPITALITY Western',v_hosp),
    ('Cordis Hong Kong Desk','Cordis Hong Kong','HK','https://www.cordishotels.com/en/hong-kong',NULL,'reservations.hongkong@cordishotels.com','+85235568828',NULL,'Mong Kok','Hong Kong','Hong Kong','HK',22.318,114.169,'555 Shanghai Street, Mong Kok, Hong Kong','BOOKER_DEMAND APAC Hong Kong mid HOSPITALITY Mong Kok',v_hosp),
    ('Dorsett Wanchai Desk','Dorsett Wanchai Hong Kong','HK','https://www.dorsetthotels.com/dorsett-wanchai-hong-kong/',NULL,'reservations.wanchai@dorsetthotels.com','+85235521111',NULL,'Wan Chai','Hong Kong','Hong Kong','HK',22.277,114.176,'387-397 Queen''s Road East, Wan Chai, Hong Kong','BOOKER_DEMAND APAC Hong Kong mid HOSPITALITY Wan Chai',v_hosp),
    ('Ovolo Southside Desk','Ovolo Southside','HK','https://ovolohotels.com/ovolo/southside/',NULL,'southside@ovolohotels.com','+85221652888',NULL,'Wong Chuk Hang','Hong Kong','Hong Kong','HK',22.248,114.167,'64 Wong Chuk Hang Road, Aberdeen, Hong Kong','BOOKER_DEMAND APAC Hong Kong mid HOSPITALITY Southside',v_hosp),
    ('Ovolo Central Desk','Ovolo Central','HK','https://ovolohotels.com/ovolo/central/',NULL,'central@ovolohotels.com','+85221653188',NULL,'Central','Hong Kong','Hong Kong','HK',22.283,114.155,'2 Arbuthnot Road, Central, Hong Kong','BOOKER_DEMAND APAC Hong Kong mid HOSPITALITY Central',v_hosp),
    ('Little Tai Hang Desk','Little Tai Hang','HK','https://www.littletaihang.com/',NULL,'reservations@littletaihang.com','+85239188688',NULL,'Tai Hang','Hong Kong','Hong Kong','HK',22.279,114.193,'98 Tung Lo Wan Road, Tai Hang, Hong Kong','BOOKER_DEMAND APAC Hong Kong mid HOSPITALITY Tai Hang',v_hosp),
    ('The Pottinger Hong Kong Desk','The Pottinger Hong Kong','HK','https://www.thepottinger.com/',NULL,'reservations@thepottinger.com','+85223030888',NULL,'Central','Hong Kong','Hong Kong','HK',22.283,114.155,'74 Queen''s Road Central, Hong Kong','BOOKER_DEMAND APAC Hong Kong mid HOSPITALITY Central',v_hosp),
    ('Butterfly on Prat Desk','Butterfly on Prat','HK','https://www.butterflyhk.com/prat/',NULL,'reservations@butterflyhk.com','+85239628888',NULL,'Tsim Sha Tsui','Hong Kong','Hong Kong','HK',22.298,114.173,'21 Prat Avenue, Tsim Sha Tsui, Hong Kong','BOOKER_DEMAND APAC Hong Kong mid HOSPITALITY TST',v_hosp),
    ('Hotel Indigo Hong Kong Island Desk','Hotel Indigo Hong Kong Island','HK','https://www.ihg.com/hotelindigo/hotels/us/en/hong-kong/hkgid/hoteldetail',NULL,'hkgid.reservations@ihg.com','+85239263888',NULL,'Wan Chai','Hong Kong','Hong Kong','HK',22.277,114.176,'246 Queen''s Road East, Wan Chai, Hong Kong','BOOKER_DEMAND APAC Hong Kong mid HOSPITALITY Wan Chai',v_hosp),
    ('Novotel Citygate Hong Kong Desk','Novotel Citygate Hong Kong','HK','https://all.accor.com/hotel/3146/index.en.shtml',NULL,'H3146@accor.com','+85236028888',NULL,'Tung Chung','Hong Kong','Hong Kong','HK',22.289,113.941,'51 Man Tung Road, Tung Chung, Lantau, Hong Kong','BOOKER_DEMAND APAC Hong Kong mid HOSPITALITY Lantau',v_hosp),
    ('Regal Hongkong Hotel Desk','Regal Hongkong Hotel','HK','https://www.regalhotel.com/regal-hongkong-hotel/',NULL,'rhk.info@regalhotel.com','+85228906633',NULL,'Causeway Bay','Hong Kong','Hong Kong','HK',22.280,114.186,'88 Yee Wo Street, Causeway Bay, Hong Kong','BOOKER_DEMAND APAC Hong Kong mid HOSPITALITY Causeway Bay',v_hosp),
    ('Regal Kowloon Hotel Desk','Regal Kowloon Hotel','HK','https://www.regalhotel.com/regal-kowloon-hotel/',NULL,'rkh.info@regalhotel.com','+85227221818',NULL,'Tsim Sha Tsui','Hong Kong','Hong Kong','HK',22.301,114.176,'71 Mody Road, Tsim Sha Tsui East, Hong Kong','BOOKER_DEMAND APAC Hong Kong mid HOSPITALITY TST East',v_hosp),
    ('Silka Tsuen Wan Desk','Silka Tsuen Wan Hong Kong','HK','https://www.silkahotels.com/en/silka-tsuen-wan/',NULL,'stw.reservations@silkahotels.com','+85224929383',NULL,'Tsuen Wan','Hong Kong','Hong Kong','HK',22.371,114.114,'119 Wo Yi Hop Road, Kwai Chung, Hong Kong','BOOKER_DEMAND APAC Hong Kong mid HOSPITALITY New Territories',v_hosp),
    ('Empire Hotel Kowloon Desk','Empire Hotel Kowloon','HK','https://www.empirehotel.com.hk/kowloon/',NULL,'kowloon@empirehotel.com.hk','+85226853300',NULL,'Tsim Sha Tsui','Hong Kong','Hong Kong','HK',22.299,114.173,'62 Kimberley Road, Tsim Sha Tsui, Hong Kong','BOOKER_DEMAND APAC Hong Kong mid HOSPITALITY TST',v_hosp),
    ('The Jervois Concierge','The Jervois','HK','https://www.thejervois.com/',NULL,'reservations@thejervois.com','+85239948000',NULL,'Sheung Wan','Hong Kong','Hong Kong','HK',22.286,114.150,'89 Jervois Street, Sheung Wan, Hong Kong','BOOKER_DEMAND APAC Hong Kong mid CONCIERGE Sheung Wan',v_conc),
    ('Nina Hotel Tsuen Wan Desk','Nina Hotel Tsuen Wan West','HK','https://www.ninahotelgroup.com/en/nina-hotel-tsuen-wan-west',NULL,'ntw.reservation@ninahotelgroup.com','+85229456000',NULL,'Tsuen Wan','Hong Kong','Hong Kong','HK',22.368,114.110,'8 Yeung Uk Road, Tsuen Wan, Hong Kong','BOOKER_DEMAND APAC Hong Kong mid HOSPITALITY Tsuen Wan',v_hosp),

    -- ========== TOKYO ==========
    ('Hotel Gracery Shinjuku Desk','Hotel Gracery Shinjuku','JP','https://shinjuku.gracery.com/',NULL,'shinjuku@gracery.com','+81368333339',NULL,'Shinjuku','Tokyo','Tokyo','JP',35.695,139.701,'1-19-1 Kabukicho, Shinjuku-ku, Tokyo 160-0021','BOOKER_DEMAND APAC Tokyo mid HOSPITALITY Shinjuku',v_hosp),
    ('Keio Plaza Hotel Tokyo Desk','Keio Plaza Hotel Tokyo','JP','https://www.keioplaza.com/',NULL,'reservation@keioplaza.co.jp','+81333440111',NULL,'Shinjuku','Tokyo','Tokyo','JP',35.690,139.697,'2-2-1 Nishi-Shinjuku, Shinjuku-ku, Tokyo 160-8330','BOOKER_DEMAND APAC Tokyo mid HOSPITALITY Nishi-Shinjuku',v_hosp),
    ('Hotel Metropolitan Tokyo Ikebukuro Desk','Hotel Metropolitan Tokyo Ikebukuro','JP','https://www.hotel-metropolitan-ikebukuro.tokyo/',NULL,'reservation@hotel-metropolitan-ikebukuro.tokyo','+81339801111',NULL,'Ikebukuro','Tokyo','Tokyo','JP',35.730,139.710,'1-6-1 Nishi-Ikebukuro, Toshima-ku, Tokyo 171-8505','BOOKER_DEMAND APAC Tokyo mid HOSPITALITY Ikebukuro',v_hosp),
    ('Shinjuku Granbell Hotel Desk','Shinjuku Granbell Hotel','JP','https://www.granbellhotel.jp/shinjuku/',NULL,'info-shinjuku@granbellhotel.jp','+81352872888',NULL,'Shinjuku','Tokyo','Tokyo','JP',35.692,139.703,'2-14-5 Kabukicho, Shinjuku-ku, Tokyo 160-0021','BOOKER_DEMAND APAC Tokyo mid HOSPITALITY Kabukicho',v_hosp),
    ('Hotel Century Southern Tower Desk','Hotel Century Southern Tower','JP','https://www.southerntower.co.jp/',NULL,'rsv@southerntower.co.jp','+81353540100',NULL,'Shinjuku','Tokyo','Tokyo','JP',35.688,139.700,'2-2-1 Yoyogi, Shibuya-ku, Tokyo 151-0053','BOOKER_DEMAND APAC Tokyo mid HOSPITALITY Shinjuku South',v_hosp),
    ('The Royal Park Hotel Tokyo Haneda Desk','The Royal Park Hotel Tokyo Haneda','JP','https://www.rph-the.jp/haneda/',NULL,'haneda@rph-the.jp','+81368308888',NULL,'Haneda','Tokyo','Tokyo','JP',35.549,139.772,'2-7-1 Haneda-kuko, Ota-ku, Tokyo 144-0041','BOOKER_DEMAND APAC Tokyo mid HOSPITALITY Haneda',v_hosp),
    ('Hotel Villa Fontaine Grand Haneda Desk','Hotel Villa Fontaine Grand Haneda Airport','JP','https://www.hvf.jp/eng/haneda-airport/',NULL,'haneda-airport@hvf.jp','+81357087770',NULL,'Haneda','Tokyo','Tokyo','JP',35.549,139.765,'2-7-1 Haneda-kuko, Ota-ku, Tokyo 144-0041','BOOKER_DEMAND APAC Tokyo mid HOSPITALITY Haneda',v_hosp),
    ('Mitsui Garden Hotel Ginza Premier Desk','Mitsui Garden Hotel Ginza Premier','JP','https://www.gardenhotels.co.jp/eng/ginza-premier/',NULL,'ginzapremier@gardenhotels.co.jp','+81335431131',NULL,'Ginza','Tokyo','Tokyo','JP',35.670,139.762,'8-13-1 Ginza, Chuo-ku, Tokyo 104-0061','BOOKER_DEMAND APAC Tokyo mid HOSPITALITY Ginza',v_hosp),
    ('Mitsui Garden Hotel Toyosu Desk','Mitsui Garden Hotel Toyosu Bay Side Cross','JP','https://www.gardenhotels.co.jp/eng/toyosu/',NULL,'toyosu@gardenhotels.co.jp','+81366338811',NULL,'Toyosu','Tokyo','Tokyo','JP',35.649,139.796,'6-5-1 Toyosu, Koto-ku, Tokyo 135-0061','BOOKER_DEMAND APAC Tokyo mid HOSPITALITY Toyosu',v_hosp),
    ('Hotel Niwa Tokyo Desk','Hotel Niwa Tokyo','JP','https://www.hotelniwa.jp/',NULL,'reservation@hotelniwa.jp','+81332993050',NULL,'Jimbocho','Tokyo','Tokyo','JP',35.697,139.757,'1-1-16 Misaki-cho, Chiyoda-ku, Tokyo 101-0061','BOOKER_DEMAND APAC Tokyo mid HOSPITALITY Jimbocho',v_hosp),
    ('The Gate Hotel Kaminarimon Desk','The Gate Hotel Kaminarimon by HULIC','JP','https://www.gate-hotel.jp/en/kaminarimon/',NULL,'reservation.kaminarimon@gate-hotel.jp','+81358268777',NULL,'Asakusa','Tokyo','Tokyo','JP',35.711,139.796,'2-16-11 Kaminarimon, Taito-ku, Tokyo 111-0034','BOOKER_DEMAND APAC Tokyo mid HOSPITALITY Asakusa',v_hosp),
    ('The Gate Hotel Tokyo Desk','The Gate Hotel Tokyo by HULIC','JP','https://www.gate-hotel.jp/en/tokyo/',NULL,'reservation.tokyo@gate-hotel.jp','+81357300000',NULL,'Ginza','Tokyo','Tokyo','JP',35.671,139.766,'2-2-3 Ginza, Chuo-ku, Tokyo 104-0061','BOOKER_DEMAND APAC Tokyo mid HOSPITALITY Ginza',v_hosp),
    ('Sequence Miyashita Park Desk','sequence MIYASHITA PARK','JP','https://www.sequencehotels.com/miyashita-park/',NULL,'miyashita@sequencehotels.com','+81354685700',NULL,'Shibuya','Tokyo','Tokyo','JP',35.661,139.702,'6-20-10 Jingumae, Shibuya-ku, Tokyo 150-0001','BOOKER_DEMAND APAC Tokyo mid HOSPITALITY Shibuya',v_hosp),
    ('Shibuya Stream Excel Hotel Tokyu Desk','Shibuya Stream Excel Hotel Tokyu','JP','https://www.tokyuhotelsjapan.com/global/stream-e/',NULL,'stream-e.rsv@tokyuhotels.co.jp','+81367127222',NULL,'Shibuya','Tokyo','Tokyo','JP',35.657,139.703,'3-21-3 Shibuya, Shibuya-ku, Tokyo 150-0002','BOOKER_DEMAND APAC Tokyo mid HOSPITALITY Shibuya',v_hosp),
    ('Remm Roppongi Desk','Remm Roppongi','JP','https://www.remm.jp/en/roppongi/',NULL,'roppongi@remm.jp','+81354194471',NULL,'Roppongi','Tokyo','Tokyo','JP',35.663,139.731,'7-14-4 Roppongi, Minato-ku, Tokyo 106-0032','BOOKER_DEMAND APAC Tokyo mid HOSPITALITY Roppongi',v_hosp),
    ('Remm Akihabara Desk','Remm Akihabara','JP','https://www.remm.jp/en/akihabara/',NULL,'akihabara@remm.jp','+81332543350',NULL,'Akihabara','Tokyo','Tokyo','JP',35.698,139.773,'1-6-5 Kanda-Sakumacho, Chiyoda-ku, Tokyo 101-0025','BOOKER_DEMAND APAC Tokyo mid HOSPITALITY Akihabara',v_hosp),
    ('Hotel Ryumeikan Tokyo Desk','Hotel Ryumeikan Tokyo','JP','https://www.ryumeikan-honten.jp/',NULL,'info@ryumeikan-honten.jp','+81332712081',NULL,'Nihonbashi','Tokyo','Tokyo','JP',35.684,139.774,'1-3-22 Yaesu, Chuo-ku, Tokyo 103-0028','BOOKER_DEMAND APAC Tokyo mid HOSPITALITY Nihonbashi',v_hosp),
    ('Tokyo Station Hotel Desk','The Tokyo Station Hotel','JP','https://www.tokyostationhotel.jp/',NULL,'reservation@tokyostationhotel.jp','+81352201311',NULL,'Marunouchi','Tokyo','Tokyo','JP',35.681,139.767,'1-9-1 Marunouchi, Chiyoda-ku, Tokyo 100-0005','BOOKER_DEMAND APAC Tokyo mid HOSPITALITY Marunouchi',v_hosp),
    ('Celestine Hotel Shiba Desk','Celestine Hotel Tokyo Shiba','JP','https://www.celestinehotel.com/',NULL,'reservation@celestinehotel.com','+81354414111',NULL,'Shiba','Tokyo','Tokyo','JP',35.652,139.748,'3-23-1 Shiba, Minato-ku, Tokyo 105-0014','BOOKER_DEMAND APAC Tokyo mid HOSPITALITY Shiba',v_hosp),
    ('Hotel Okura Tokyo Bay Desk','Hotel Okura Tokyo Bay','JP','https://www.okura-tokyo-bay.com/',NULL,'reservation@okura-tokyo-bay.com','+81473551211',NULL,'Maihama','Tokyo','Chiba','JP',35.629,139.884,'1-8 Maihama, Urayasu-shi, Chiba 279-8585','BOOKER_DEMAND APAC Tokyo mid HOSPITALITY Maihama',v_hosp),
    ('Candeo Hotels Tokyo Roppongi Desk','Candeo Hotels Tokyo Roppongi','JP','https://www.candeohotels.com/en/roppongi/',NULL,'roppongi@candeohotels.com','+81357861400',NULL,'Roppongi','Tokyo','Tokyo','JP',35.662,139.731,'6-7-12 Roppongi, Minato-ku, Tokyo 106-0032','BOOKER_DEMAND APAC Tokyo mid HOSPITALITY Roppongi',v_hosp),
    ('The Royal Park Canvas Ginza Concierge','THE ROYAL PARK CANVAS Ginza 8','JP','https://www.canvas.royalparkhotels.co.jp/ginza8/',NULL,'ginza8@canvas.royalparkhotels.co.jp','+81362639000',NULL,'Ginza','Tokyo','Tokyo','JP',35.668,139.763,'8-8-20 Ginza, Chuo-ku, Tokyo 104-0061','BOOKER_DEMAND APAC Tokyo mid CONCIERGE Ginza',v_conc),

    -- ========== BANGKOK ==========
    ('Kimpton Maa-Lai Bangkok Desk','Kimpton Maa-Lai Bangkok','TH','https://www.ihg.com/kimptonhotels/hotels/us/en/bangkok/bkklk/hoteldetail',NULL,'bkklk.reservations@ihg.com','+6620569999',NULL,'Pathumwan','Bangkok','Bangkok','TH',13.741,100.539,'28 Soi Langsuan, Pathumwan, Bangkok 10330','BOOKER_DEMAND APAC Bangkok mid HOSPITALITY Langsuan',v_hosp),
    ('Hotel Indigo Bangkok Wireless Road Desk','Hotel Indigo Bangkok Wireless Road','TH','https://www.ihg.com/hotelindigo/hotels/us/en/bangkok/bkkwi/hoteldetail',NULL,'bkkwi.reservations@ihg.com','+6622094888',NULL,'Wireless Road','Bangkok','Bangkok','TH',13.741,100.547,'81 Wireless Road, Lumpini, Pathumwan, Bangkok 10330','BOOKER_DEMAND APAC Bangkok mid HOSPITALITY Wireless Road',v_hosp),
    ('Novotel Bangkok Sukhumvit 20 Desk','Novotel Bangkok Sukhumvit 20','TH','https://all.accor.com/hotel/B1C6/index.en.shtml',NULL,'HB1C6@accor.com','+6620095888',NULL,'Sukhumvit','Bangkok','Bangkok','TH',13.730,100.563,'19/9 Soi Sukhumvit 20, Bangkok 10110','BOOKER_DEMAND APAC Bangkok mid HOSPITALITY Sukhumvit',v_hosp),
    ('Mercure Bangkok Sukhumvit 24 Desk','Mercure Bangkok Sukhumvit 24','TH','https://all.accor.com/hotel/B0Q3/index.en.shtml',NULL,'HB0Q3@accor.com','+6621192288',NULL,'Sukhumvit','Bangkok','Bangkok','TH',13.724,100.568,'17 Soi Sukhumvit 24, Bangkok 10110','BOOKER_DEMAND APAC Bangkok mid HOSPITALITY Sukhumvit',v_hosp),
    ('Hyatt Regency Bangkok Sukhumvit Desk','Hyatt Regency Bangkok Sukhumvit','TH','https://www.hyatt.com/en-US/hotel/thailand/hyatt-regency-bangkok-sukhumvit/bkkrg',NULL,'bangkok.sukhumvit@hyatt.com','+6626141234',NULL,'Sukhumvit','Bangkok','Bangkok','TH',13.738,100.560,'1 Sukhumvit Soi 13, Bangkok 10110','BOOKER_DEMAND APAC Bangkok mid HOSPITALITY Sukhumvit',v_hosp),
    ('Pullman Bangkok Hotel G Desk','Pullman Bangkok Hotel G','TH','https://all.accor.com/hotel/7455/index.en.shtml',NULL,'H7455@accor.com','+6622381991',NULL,'Silom','Bangkok','Bangkok','TH',13.727,100.532,'188 Silom Road, Bangrak, Bangkok 10500','BOOKER_DEMAND APAC Bangkok mid HOSPITALITY Silom',v_hosp),
    ('Eastin Grand Hotel Sathorn Desk','Eastin Grand Hotel Sathorn','TH','https://www.eastingrandhotelsathorn.com/',NULL,'reservation@eastingrandhotelsathorn.com','+6622108100',NULL,'Sathorn','Bangkok','Bangkok','TH',13.720,100.528,'33/1 South Sathorn Road, Bangkok 10120','BOOKER_DEMAND APAC Bangkok mid HOSPITALITY Sathorn',v_hosp),
    ('Mode Sathorn Hotel Desk','Mode Sathorn Hotel','TH','https://www.modesathorn.com/',NULL,'reservation@modesathorn.com','+6621158888',NULL,'Sathorn','Bangkok','Bangkok','TH',13.719,100.528,'159/17 Naradhiwas Rajanagarindra Road, Bangkok 10120','BOOKER_DEMAND APAC Bangkok mid HOSPITALITY Sathorn',v_hosp),
    ('Chatrium Hotel Riverside Desk','Chatrium Hotel Riverside Bangkok','TH','https://www.chatrium.com/chatriumhotelriverside/',NULL,'reservations.chrb@chatrium.com','+6623078888',NULL,'Riverside','Bangkok','Bangkok','TH',13.713,100.512,'28 Charoenkrung Soi 70, Bangkok 10120','BOOKER_DEMAND APAC Bangkok mid HOSPITALITY Riverside',v_hosp),
    ('Avani+ Riverside Bangkok Desk','Avani+ Riverside Bangkok Hotel','TH','https://www.avanihotels.com/en/riverside-bangkok',NULL,'riverside@avanihotels.com','+6624319100',NULL,'Riverside','Bangkok','Bangkok','TH',13.705,100.504,'257 Charoennakorn Road, Bangkok 10600','BOOKER_DEMAND APAC Bangkok mid HOSPITALITY Riverside',v_hosp),
    ('Amari Watergate Bangkok Desk','Amari Watergate Bangkok','TH','https://www.amari.com/watergate/',NULL,'watergate@amari.com','+6626539000',NULL,'Pratunam','Bangkok','Bangkok','TH',13.753,100.540,'847 Petchburi Road, Bangkok 10400','BOOKER_DEMAND APAC Bangkok mid HOSPITALITY Pratunam',v_hosp),
    ('Amari Bangkok Desk','Amari Bangkok','TH','https://www.amari.com/bangkok/',NULL,'bangkok@amari.com','+6622553000',NULL,'Sukhumvit','Bangkok','Bangkok','TH',13.737,100.558,'832 Soi Thonglor 25, Sukhumvit 55, Bangkok 10110','BOOKER_DEMAND APAC Bangkok mid HOSPITALITY Thonglor',v_hosp),
    ('Centara Grand at CentralWorld Desk','Centara Grand at CentralWorld','TH','https://www.centarahotelsresorts.com/centaragrand/cgcw',NULL,'cgcw@chr.co.th','+6621001234',NULL,'Ratchaprasong','Bangkok','Bangkok','TH',13.747,100.539,'999/99 Rama 1 Road, Pathumwan, Bangkok 10330','BOOKER_DEMAND APAC Bangkok mid HOSPITALITY Ratchaprasong',v_hosp),
    ('Anantara Siam Bangkok Desk','Anantara Siam Bangkok Hotel','TH','https://www.anantara.com/en/siam-bangkok',NULL,'siam@anantara.com','+6621268866',NULL,'Ratchadamri','Bangkok','Bangkok','TH',13.744,100.540,'155 Rajadamri Road, Bangkok 10330','BOOKER_DEMAND APAC Bangkok mid HOSPITALITY Ratchadamri',v_hosp),
    ('The Sukosol Bangkok Desk','The Sukosol','TH','https://www.sukosolhotels.com/the-sukosol/',NULL,'info@thesukosol.com','+6622470123',NULL,'Petchaburi','Bangkok','Bangkok','TH',13.748,100.553,'477 Si Ayutthaya Road, Bangkok 10400','BOOKER_DEMAND APAC Bangkok mid HOSPITALITY Phaya Thai',v_hosp),
    ('Siam Kempinski Bangkok Desk','Siam Kempinski Hotel Bangkok','TH','https://www.kempinski.com/en/bangkok/siam-hotel',NULL,'reservations.siambangkok@kempinski.com','+6621629000',NULL,'Siam','Bangkok','Bangkok','TH',13.746,100.534,'991/9 Rama 1 Road, Pathumwan, Bangkok 10330','BOOKER_DEMAND APAC Bangkok mid HOSPITALITY Siam',v_hosp),
    ('Bangkok Marriott Marquis Queen''s Park Desk','Bangkok Marriott Marquis Queen''s Park','TH','https://www.marriott.com/hotels/travel/bkkqp-bangkok-marriott-marquis-queens-park/',NULL,'bkkqp.reservations@marriott.com','+6620595555',NULL,'Sukhumvit','Bangkok','Bangkok','TH',13.739,100.557,'199 Sukhumvit Soi 22, Bangkok 10110','BOOKER_DEMAND APAC Bangkok mid HOSPITALITY Sukhumvit',v_hosp),
    ('SO Sofitel Bangkok Concierge','SO/ Bangkok','TH','https://all.accor.com/hotel/7994/index.en.shtml',NULL,'H7994@accor.com','+6626240000',NULL,'Sathorn','Bangkok','Bangkok','TH',13.724,100.538,'2 North Sathorn Road, Bangkok 10500','BOOKER_DEMAND APAC Bangkok mid CONCIERGE Sathorn',v_conc),

    -- ========== SYDNEY ==========
    ('QT Sydney Desk','QT Sydney','AU','https://www.qthotels.com/sydney/',NULL,'reservations.qtsydney@evt.com','+61282620000',NULL,'CBD','Sydney','New South Wales','AU',-33.871,151.207,'49 Market Street, Sydney NSW 2000','BOOKER_DEMAND APAC Sydney mid HOSPITALITY CBD',v_hosp),
    ('Ovolo Woolloomooloo Desk','Ovolo Woolloomooloo','AU','https://ovolohotels.com/ovolo/woolloomooloo/',NULL,'woolloomooloo@ovolohotels.com','+61293318888',NULL,'Woolloomooloo','Sydney','New South Wales','AU',-33.869,151.220,'6 Cowper Wharf Roadway, Woolloomooloo NSW 2011','BOOKER_DEMAND APAC Sydney mid HOSPITALITY Woolloomooloo',v_hosp),
    ('Ovolo The Rocks Desk','Ovolo The Rocks','AU','https://ovolohotels.com/ovolo/the-rocks/',NULL,'therocks@ovolohotels.com','+61282176900',NULL,'The Rocks','Sydney','New South Wales','AU',-33.860,151.208,'59 Harrington Street, The Rocks NSW 2000','BOOKER_DEMAND APAC Sydney mid HOSPITALITY The Rocks',v_hosp),
    ('The Grace Hotel Sydney Desk','The Grace Hotel','AU','https://www.gracehotel.com.au/',NULL,'reservations@gracehotel.com.au','+61292726888',NULL,'CBD','Sydney','New South Wales','AU',-33.869,151.206,'77 York Street, Sydney NSW 2000','BOOKER_DEMAND APAC Sydney mid HOSPITALITY CBD',v_hosp),
    ('Vibe Hotel Sydney Desk','Vibe Hotel Sydney','AU','https://www.vibehotels.com/hotel/sydney',NULL,'sydney@vibehotels.com.au','+61282724000',NULL,'Darling Harbour','Sydney','New South Wales','AU',-33.875,151.200,'111 Goulburn Street, Sydney NSW 2000','BOOKER_DEMAND APAC Sydney mid HOSPITALITY CBD South',v_hosp),
    ('Rydges World Square Desk','Rydges World Square Sydney','AU','https://www.rydges.com/accommodation/sydney-nsw/world-square-sydney/',NULL,'reservations_worldsquare@rydges.com','+61282688888',NULL,'World Square','Sydney','New South Wales','AU',-33.878,151.207,'389 Pitt Street, Sydney NSW 2000','BOOKER_DEMAND APAC Sydney mid HOSPITALITY CBD',v_hosp),
    ('Meriton Suites World Tower Desk','Meriton Suites World Tower','AU','https://www.meritonsuites.com.au/world-tower/',NULL,'worldtower@meritonsuites.com.au','+61282638888',NULL,'World Square','Sydney','New South Wales','AU',-33.877,151.207,'95 Liverpool Street, Sydney NSW 2000','BOOKER_DEMAND APAC Sydney mid HOSPITALITY CBD',v_hosp),
    ('Adina Apartment Hotel Sydney Desk','Adina Apartment Hotel Sydney','AU','https://www.adinahotels.com/hotel/sydney/',NULL,'sydney@adinahotels.com.au','+61292468800',NULL,'Surry Hills','Sydney','New South Wales','AU',-33.880,151.212,'511-515 Crown Street, Surry Hills NSW 2010','BOOKER_DEMAND APAC Sydney mid HOSPITALITY Surry Hills',v_hosp),
    ('Little National Hotel Sydney Desk','Little National Hotel Sydney','AU','https://www.littlenationalhotel.com.au/sydney/',NULL,'sydney@littlenationalhotel.com.au','+61282176000',NULL,'CBD','Sydney','New South Wales','AU',-33.866,151.208,'1 Macquarie Place, Sydney NSW 2000','BOOKER_DEMAND APAC Sydney mid HOSPITALITY Circular Quay',v_hosp),
    ('The Old Clare Hotel Desk','The Old Clare Hotel','AU','https://www.theoldclarehotel.com.au/',NULL,'reservations@theoldclarehotel.com.au','+61280969888',NULL,'Chippendale','Sydney','New South Wales','AU',-33.886,151.200,'1 Kensington Street, Chippendale NSW 2008','BOOKER_DEMAND APAC Sydney mid HOSPITALITY Chippendale',v_hosp),
    ('Paramount House Hotel Desk','Paramount House Hotel','AU','https://www.paramounthousehotel.com/',NULL,'reservations@paramounthousehotel.com','+61292111222',NULL,'Surry Hills','Sydney','New South Wales','AU',-33.882,151.211,'80 Commonwealth Street, Surry Hills NSW 2010','BOOKER_DEMAND APAC Sydney mid HOSPITALITY Surry Hills',v_hosp),
    ('Holiday Inn Darling Harbour Desk','Holiday Inn Darling Harbour','AU','https://www.ihg.com/holidayinn/hotels/us/en/sydney/sydha/hoteldetail',NULL,'sydha.reservations@ihg.com','+61292618911',NULL,'Darling Harbour','Sydney','New South Wales','AU',-33.875,151.201,'68 Harbour Street, Sydney NSW 2000','BOOKER_DEMAND APAC Sydney mid HOSPITALITY Darling Harbour',v_hosp),
    ('Novotel Sydney on Darling Harbour Desk','Novotel Sydney on Darling Harbour','AU','https://all.accor.com/hotel/0508/index.en.shtml',NULL,'H0508@accor.com','+61299340900',NULL,'Darling Harbour','Sydney','New South Wales','AU',-33.873,151.199,'100 Murray Street, Pyrmont NSW 2009','BOOKER_DEMAND APAC Sydney mid HOSPITALITY Darling Harbour',v_hosp),
    ('Pullman Sydney Hyde Park Desk','Pullman Sydney Hyde Park','AU','https://all.accor.com/hotel/1804/index.en.shtml',NULL,'H1804@accor.com','+61293618333',NULL,'Hyde Park','Sydney','New South Wales','AU',-33.874,151.212,'36 College Street, Sydney NSW 2000','BOOKER_DEMAND APAC Sydney mid HOSPITALITY Hyde Park',v_hosp),
    ('Manly Pacific Sydney Desk','Manly Pacific Sydney','AU','https://www.manlypacific.com.au/',NULL,'reservations@manlypacific.com.au','+61299776666',NULL,'Manly','Sydney','New South Wales','AU',-33.797,151.287,'55 North Steyne, Manly NSW 2095','BOOKER_DEMAND APAC Sydney mid HOSPITALITY Manly',v_hosp),
    ('Swissotel Sydney Desk','Swissotel Sydney','AU','https://www.swissotel.com/hotels/sydney/',NULL,'sydney@swissotel.com','+61292506100',NULL,'CBD','Sydney','New South Wales','AU',-33.871,151.208,'68 Market Street, Sydney NSW 2000','BOOKER_DEMAND APAC Sydney mid HOSPITALITY CBD',v_hosp),
    ('Establishment Hotel Concierge','Establishment Hotel','AU','https://www.merivale.com.au/stay/establishment-hotel',NULL,'reservations@establishmenthotel.com','+61292403000',NULL,'CBD','Sydney','New South Wales','AU',-33.863,151.209,'5 Bridge Lane, Sydney NSW 2000','BOOKER_DEMAND APAC Sydney mid CONCIERGE CBD',v_conc),
    ('Crystalbrook Riley Sydney Desk','Crystalbrook Riley','AU','https://www.crystalbrookcollection.com/riley',NULL,'riley.reservations@crystalbrookcollection.com','+61280729600',NULL,'Surry Hills','Sydney','New South Wales','AU',-33.883,151.212,'339 Crown Street, Surry Hills NSW 2010','BOOKER_DEMAND APAC Sydney mid HOSPITALITY Surry Hills',v_hosp),

    -- ========== MELBOURNE ==========
    ('QT Melbourne Desk','QT Melbourne','AU','https://www.qthotels.com/melbourne/',NULL,'reservations.qtmelbourne@evt.com','+61386369100',NULL,'CBD','Melbourne','Victoria','AU',-37.814,144.970,'133 Russell Street, Melbourne VIC 3000','BOOKER_DEMAND APAC Melbourne mid HOSPITALITY CBD',v_hosp),
    ('Ovolo Laneways Desk','Ovolo Laneways','AU','https://ovolohotels.com/ovolo/laneways/',NULL,'laneways@ovolohotels.com','+61386920888',NULL,'CBD','Melbourne','Victoria','AU',-37.814,144.967,'19 Little Bourke Street, Melbourne VIC 3000','BOOKER_DEMAND APAC Melbourne mid HOSPITALITY CBD',v_hosp),
    ('The Hotel Windsor Melbourne Desk','The Hotel Windsor','AU','https://www.thehotelwindsor.com.au/',NULL,'reservations@thewindsor.com.au','+61396336000',NULL,'Spring Street','Melbourne','Victoria','AU',-37.811,144.974,'111 Spring Street, Melbourne VIC 3000','BOOKER_DEMAND APAC Melbourne mid HOSPITALITY East End',v_hosp),
    ('Adina Apartment Hotel Melbourne Desk','Adina Apartment Hotel Melbourne','AU','https://www.adinahotels.com/hotel/melbourne/',NULL,'melbourne@adinahotels.com.au','+61386638000',NULL,'CBD','Melbourne','Victoria','AU',-37.817,144.961,'189 Queen Street, Melbourne VIC 3000','BOOKER_DEMAND APAC Melbourne mid HOSPITALITY CBD',v_hosp),
    ('Vibe Hotel Melbourne Desk','Vibe Hotel Melbourne','AU','https://www.vibehotels.com/hotel/melbourne',NULL,'melbourne@vibehotels.com.au','+61386231111',NULL,'CBD','Melbourne','Victoria','AU',-37.816,144.961,'1 Queen Street, Melbourne VIC 3000','BOOKER_DEMAND APAC Melbourne mid HOSPITALITY CBD',v_hosp),
    ('Rydges Melbourne Desk','Rydges Melbourne','AU','https://www.rydges.com/accommodation/melbourne-vic/melbourne/',NULL,'reservations_melbourne@rydges.com','+61396672020',NULL,'Exhibition Street','Melbourne','Victoria','AU',-37.811,144.972,'186 Exhibition Street, Melbourne VIC 3000','BOOKER_DEMAND APAC Melbourne mid HOSPITALITY CBD',v_hosp),
    ('Novotel Melbourne on Collins Desk','Novotel Melbourne on Collins','AU','https://all.accor.com/hotel/0527/index.en.shtml',NULL,'H0527@accor.com','+61396672200',NULL,'Collins Street','Melbourne','Victoria','AU',-37.816,144.966,'270 Collins Street, Melbourne VIC 3000','BOOKER_DEMAND APAC Melbourne mid HOSPITALITY CBD',v_hosp),
    ('Mercure Melbourne Treasury Gardens Desk','Mercure Melbourne Treasury Gardens','AU','https://all.accor.com/hotel/0575/index.en.shtml',NULL,'H0575@accor.com','+61396390599',NULL,'East Melbourne','Melbourne','Victoria','AU',-37.811,144.978,'13 Spring Street, Melbourne VIC 3000','BOOKER_DEMAND APAC Melbourne mid HOSPITALITY East Melbourne',v_hosp),
    ('Pullman Melbourne on the Park Desk','Pullman Melbourne on the Park','AU','https://all.accor.com/hotel/1726/index.en.shtml',NULL,'H1726@accor.com','+61394192000',NULL,'East Melbourne','Melbourne','Victoria','AU',-37.811,144.983,'192 Wellington Parade, East Melbourne VIC 3002','BOOKER_DEMAND APAC Melbourne mid HOSPITALITY East Melbourne',v_hosp),
    ('Crystalbrook Bailey Melbourne Desk','Crystalbrook Bailey','AU','https://www.crystalbrookcollection.com/bailey',NULL,'bailey.reservations@crystalbrookcollection.com','+61391127700',NULL,'Southbank','Melbourne','Victoria','AU',-37.823,144.960,'8 Whiteman Street, Southbank VIC 3006','BOOKER_DEMAND APAC Melbourne mid HOSPITALITY Southbank',v_hosp),
    ('The Langham Melbourne Desk','The Langham Melbourne','AU','https://www.langhamhotels.com/en/the-langham/melbourne/',NULL,'tlmel.info@langhamhotels.com','+61386968888',NULL,'Southbank','Melbourne','Victoria','AU',-37.820,144.965,'1 Southgate Avenue, Southbank VIC 3006','BOOKER_DEMAND APAC Melbourne mid HOSPITALITY Southbank',v_hosp),
    ('Pan Pacific Melbourne Desk','Pan Pacific Melbourne','AU','https://www.panpacific.com/en/hotels-and-resorts/pp-melbourne.html',NULL,'reservations.ppmel@panpacific.com','+61390272000',NULL,'South Wharf','Melbourne','Victoria','AU',-37.825,144.952,'2 Convention Centre Place, South Wharf VIC 3006','BOOKER_DEMAND APAC Melbourne mid HOSPITALITY South Wharf',v_hosp),
    ('Causeway 353 Hotel Desk','Causeway 353 Hotel','AU','https://www.causeway353.com.au/',NULL,'reservations@causeway353.com.au','+61396608888',NULL,'CBD','Melbourne','Victoria','AU',-37.813,144.963,'353 Little Collins Street, Melbourne VIC 3000','BOOKER_DEMAND APAC Melbourne mid HOSPITALITY CBD',v_hosp),
    ('Art Series The Cullen Concierge','The Cullen','AU','https://www.artserieshotels.com.au/cullen/',NULL,'reservations@thecullen.com.au','+61390988200',NULL,'Prahran','Melbourne','Victoria','AU',-37.848,144.993,'164 Commercial Road, Prahran VIC 3181','BOOKER_DEMAND APAC Melbourne mid CONCIERGE Prahran',v_conc),

    -- ========== SPILLOVER: Copenhagen ==========
    ('Hotel SP34 Copenhagen Desk','Hotel SP34','DK','https://www.brochner-hotels.com/hotel-sp34/',NULL,'sp34@brochner-hotels.com','+4533134000',NULL,'Indre By','Copenhagen','Capital Region','DK',55.676,12.568,'Sankt Peders Stræde 34, 1453 Copenhagen','BOOKER_DEMAND EU Copenhagen mid HOSPITALITY Indre By',v_hosp),
    ('Hotel Danmark Copenhagen Desk','Hotel Danmark','DK','https://www.brochner-hotels.com/hotel-danmark/',NULL,'danmark@brochner-hotels.com','+4533114806',NULL,'Indre By','Copenhagen','Capital Region','DK',55.675,12.577,'Vester Voldgade 89, 1552 Copenhagen','BOOKER_DEMAND EU Copenhagen mid HOSPITALITY City Centre',v_hosp),
    ('Absalon Hotel Copenhagen Desk','Absalon Hotel','DK','https://www.absalon-hotel.dk/',NULL,'booking@absalon-hotel.dk','+4533242211',NULL,'Vesterbro','Copenhagen','Capital Region','DK',55.669,12.555,'Helgolandsgade 15, 1653 Copenhagen','BOOKER_DEMAND EU Copenhagen mid HOSPITALITY Vesterbro',v_hosp),
    ('Manon Les Suites Concierge','Manon les Suites','DK','https://www.guldsmedenhotels.com/manon-les-suites/',NULL,'manon@guldsmedenhotels.com','+4533700077',NULL,'Østerbro','Copenhagen','Capital Region','DK',55.699,12.584,'Gyldenløvesgade 19, 1600 Copenhagen','BOOKER_DEMAND EU Copenhagen mid CONCIERGE City Lakes',v_conc),

    -- ========== SPILLOVER: Stockholm ==========
    ('Hotel Rival Stockholm Desk','Hotel Rival','SE','https://www.rival.se/',NULL,'booking@rival.se','+46854578900',NULL,'Södermalm','Stockholm','Stockholm','SE',59.317,18.067,'Mariatorget 3, 118 48 Stockholm','BOOKER_DEMAND EU Stockholm mid HOSPITALITY Södermalm',v_hosp),
    ('Hotel At Six Stockholm Desk','Hotel At Six','SE','https://www.hotelatsix.com/',NULL,'reservations@hotelatsix.com','+46857909000',NULL,'Norrmalm','Stockholm','Stockholm','SE',59.331,18.069,'Brunkebergstorg 6, 111 51 Stockholm','BOOKER_DEMAND EU Stockholm mid HOSPITALITY Norrmalm',v_hosp),
    ('Hobo Hotel Stockholm Desk','Hobo Hotel','SE','https://www.hobo.se/',NULL,'hello@hobo.se','+46857840700',NULL,'Norrmalm','Stockholm','Stockholm','SE',59.332,18.063,'Brunkebergstorg 4, 111 51 Stockholm','BOOKER_DEMAND EU Stockholm mid HOSPITALITY City',v_hosp),
    ('Ett Hem Stockholm Concierge','Ett Hem','SE','https://www.etthem.se/',NULL,'info@etthem.se','+468200590',NULL,'Östermalm','Stockholm','Stockholm','SE',59.342,18.077,'Sköldungagatan 2, 114 27 Stockholm','BOOKER_DEMAND EU Stockholm mid CONCIERGE Östermalm',v_conc),

    -- ========== SPILLOVER: Nice ==========
    ('Hotel Negresco Nice Desk','Hotel Negresco','FR','https://www.hotel-negresco-nice.com/',NULL,'reservations@hotel-negresco.com','+33493164000',NULL,'Promenade des Anglais','Nice','Provence-Alpes-Côte d''Azur','FR',43.695,7.258,'37 Promenade des Anglais, 06000 Nice','BOOKER_DEMAND EU Nice mid HOSPITALITY Promenade',v_hosp),
    ('Boscolo Nice Hotel Desk','Boscolo Nice Hotel & Spa','FR','https://www.boscolohotels.com/en/boscolo-nice/',NULL,'reservations.nice@boscolohotels.com','+33493165500',NULL,'Promenade','Nice','Provence-Alpes-Côte d''Azur','FR',43.695,7.265,'29 Avenue Félix Faure, 06000 Nice','BOOKER_DEMAND EU Nice mid HOSPITALITY Centre',v_hosp),
    ('Hotel Suisse Nice Desk','Hôtel Suisse','FR','https://www.hotels-nice.com/hotel-suisse/',NULL,'suisse@hotels-nice.com','+33493172200',NULL,'Quai Rauba Capeu','Nice','Provence-Alpes-Côte d''Azur','FR',43.696,7.278,'15 Quai Rauba Capeu, 06300 Nice','BOOKER_DEMAND EU Nice mid HOSPITALITY Old Town',v_hosp),
    ('Le Meridien Nice Desk','Le Méridien Nice','FR','https://www.marriott.com/hotels/travel/ncees-le-meridien-nice/',NULL,'ncees.reservations@lemeridien.com','+33492034707',NULL,'Promenade','Nice','Provence-Alpes-Côte d''Azur','FR',43.695,7.266,'1 Promenade des Anglais, 06046 Nice','BOOKER_DEMAND EU Nice mid HOSPITALITY Promenade',v_hosp),

    -- ========== SPILLOVER: Lyon ==========
    ('Hotel Carlton Lyon Desk','Hôtel Carlton Lyon - MGallery','FR','https://all.accor.com/hotel/1292/index.en.shtml',NULL,'H1292@accor.com','+33478425621',NULL,'Presqu''île','Lyon','Auvergne-Rhône-Alpes','FR',45.762,4.836,'4 Rue Jussieu, 69002 Lyon','BOOKER_DEMAND EU Lyon mid HOSPITALITY Presqu''île',v_hosp),
    ('InterContinental Lyon Desk','InterContinental Lyon - Hotel Dieu','FR','https://www.ihg.com/intercontinental/hotels/us/en/lyon/lysha/hoteldetail',NULL,'lysha.reservations@ihg.com','+33426732323',NULL,'Presqu''île','Lyon','Auvergne-Rhône-Alpes','FR',45.758,4.836,'20 Quai Jules Courmont, 69002 Lyon','BOOKER_DEMAND EU Lyon mid HOSPITALITY Bellecour',v_hosp),
    ('OKKO Hotels Lyon Desk','OKKO Hotels Lyon Pont Lafayette','FR','https://www.okkohotels.com/en/hotel/okko-hotels-lyon-pont-lafayette/',NULL,'lyon@okkohotels.com','+33478608800',NULL,'Part-Dieu','Lyon','Auvergne-Rhône-Alpes','FR',45.761,4.846,'14 Bis Quai Général Sarrail, 69006 Lyon','BOOKER_DEMAND EU Lyon mid HOSPITALITY Rhône',v_hosp),
    ('Villa Florentine Lyon Concierge','Villa Florentine','FR','https://www.villaflorentine.com/',NULL,'reservations@villaflorentine.com','+33472569090',NULL,'Fourvière','Lyon','Auvergne-Rhône-Alpes','FR',45.762,4.823,'25-27 Montée Saint-Barthélemy, 69005 Lyon','BOOKER_DEMAND EU Lyon mid CONCIERGE Fourvière',v_conc),

    -- ========== SPILLOVER: Portland ==========
    ('Hotel Lucia Portland Desk','Hotel Lucia','US','https://www.hotellucia.com/',NULL,'reservations@hotellucia.com','+15032258555',NULL,'Downtown','Portland','Oregon','US',45.520,-122.678,'400 SW Broadway, Portland OR 97205','BOOKER_DEMAND US Portland mid HOSPITALITY Downtown',v_hosp),
    ('Hotel deLuxe Portland Desk','Hotel deLuxe','US','https://www.hoteldeluxe.com/',NULL,'reservations@hoteldeluxe.com','+15032196100',NULL,'Downtown','Portland','Oregon','US',45.521,-122.682,'729 SW 15th Avenue, Portland OR 97205','BOOKER_DEMAND US Portland mid HOSPITALITY Downtown',v_hosp),
    ('The Nines Portland Desk','The Nines, a Luxury Collection Hotel','US','https://www.thenines.com/',NULL,'reservations@thenines.com','+15032299999',NULL,'Downtown','Portland','Oregon','US',45.519,-122.678,'525 SW Morrison Street, Portland OR 97204','BOOKER_DEMAND US Portland mid HOSPITALITY Downtown',v_hosp),
    ('Kimpton RiverPlace Portland Desk','Kimpton RiverPlace Hotel','US','https://www.riverplacehotel.com/',NULL,'reservations@riverplacehotel.com','+15032281555',NULL,'RiverPlace','Portland','Oregon','US',45.508,-122.673,'1510 SW Harbor Way, Portland OR 97201','BOOKER_DEMAND US Portland mid HOSPITALITY Waterfront',v_hosp),

    -- ========== SPILLOVER: Denver ==========
    ('The Crawford Hotel Denver Desk','The Crawford Hotel','US','https://www.thecrawfordhotel.com/',NULL,'reservations@thecrawfordhotel.com','+17204605222',NULL,'Union Station','Denver','Colorado','US',39.753,-104.999,'1701 Wynkoop Street, Denver CO 80202','BOOKER_DEMAND US Denver mid HOSPITALITY Union Station',v_hosp),
    ('Hotel Teatro Denver Desk','Hotel Teatro','US','https://www.hotelteatro.com/',NULL,'reservations@hotelteatro.com','+13032921300',NULL,'Downtown','Denver','Colorado','US',39.744,-104.995,'1100 14th Street, Denver CO 80202','BOOKER_DEMAND US Denver mid HOSPITALITY Downtown',v_hosp),
    ('The Maven Hotel Denver Desk','The Maven Hotel at Dairy Block','US','https://www.themavenhotel.com/',NULL,'reservations@themavenhotel.com','+17207030000',NULL,'LoDo','Denver','Colorado','US',39.753,-104.997,'1850 Wazee Street, Denver CO 80202','BOOKER_DEMAND US Denver mid HOSPITALITY LoDo',v_hosp),
    ('Halcyon Cherry Creek Desk','Halcyon, a hotel in Cherry Creek','US','https://www.halcyonhotelcherrycreek.com/',NULL,'reservations@halcyonhotelcherrycreek.com','+17207301000',NULL,'Cherry Creek','Denver','Colorado','US',39.719,-104.953,'245 Columbine Street, Denver CO 80206','BOOKER_DEMAND US Denver mid HOSPITALITY Cherry Creek',v_hosp),

    -- ========== SPILLOVER: Atlanta ==========
    ('Hotel Clermont Atlanta Desk','Hotel Clermont','US','https://www.hotelclermont.com/',NULL,'reservations@hotelclermont.com','+14708897900',NULL,'Poncey-Highland','Atlanta','Georgia','US',33.773,-84.361,'789 Ponce de Leon Avenue NE, Atlanta GA 30306','BOOKER_DEMAND US Atlanta mid HOSPITALITY Poncey-Highland',v_hosp),
    ('The Candler Hotel Atlanta Desk','The Candler Hotel Atlanta, Curio Collection','US','https://www.thecandlerhotel.com/',NULL,'reservations@thecandlerhotel.com','+14049623000',NULL,'Downtown','Atlanta','Georgia','US',33.755,-84.389,'127 Peachtree Street NE, Atlanta GA 30303','BOOKER_DEMAND US Atlanta mid HOSPITALITY Downtown',v_hosp),
    ('Hotel Indigo Atlanta Midtown Desk','Hotel Indigo Atlanta Midtown','US','https://www.ihg.com/hotelindigo/hotels/us/en/atlanta/atlmx/hoteldetail',NULL,'atlmx.reservations@ihg.com','+14048749600',NULL,'Midtown','Atlanta','Georgia','US',33.786,-84.384,'683 Peachtree Street NE, Atlanta GA 30308','BOOKER_DEMAND US Atlanta mid HOSPITALITY Midtown',v_hosp),
    ('Kimpton Over Under Atlanta Concierge','Kimpton Over Under Hotel','US','https://www.overunderhotel.com/',NULL,'reservations@overunderhotel.com','+14048733300',NULL,'Midtown','Atlanta','Georgia','US',33.786,-84.383,'800 West Peachtree Street NW, Atlanta GA 30308','BOOKER_DEMAND US Atlanta mid CONCIERGE Midtown',v_conc)
  ) AS t(
    display_name, legal_name, country, website_url, website_domain, email, phone, whatsapp,
    base_label, city, region, country_code, lat, lng, formatted_address, note, service_type_id
  )
  LOOP
    IF EXISTS (
      SELECT 1 FROM organizations o WHERE o.archived_at IS NULL AND (
        (lower(o.display_name) = lower(r.display_name) AND o.legal_country_code = r.country)
        OR (r.email IS NOT NULL AND lower(coalesce(o.primary_email, '')) = lower(r.email)
            AND o.notes_public LIKE 'BOOKER_DEMAND%')
      )
    ) THEN
      skipped := skipped + 1;
      CONTINUE;
    END IF;

    INSERT INTO organizations (
      display_name, legal_name, legal_country_code, legal_city, legal_region,
      website_url, website_domain, primary_email, primary_phone_e164, primary_whatsapp_e164,
      notes_public, is_test, created_by_user_id
    ) VALUES (
      r.display_name, r.legal_name, r.country, r.city, r.region,
      r.website_url, r.website_domain, r.email, r.phone, COALESCE(r.whatsapp, r.phone),
      r.note, false, v_admin
    ) RETURNING id INTO v_org;

    INSERT INTO organization_capabilities (organization_id, capability)
    VALUES (v_org, 'BUYER') ON CONFLICT DO NOTHING;
    INSERT INTO partnerships (organization_id, relationship_status, status_changed_at)
    VALUES (v_org, 'LEAD', now());
    INSERT INTO offerings (organization_id, service_type_id, operational_status)
    VALUES (v_org, r.service_type_id, 'UNKNOWN');
    INSERT INTO organization_locations (
      organization_id, label, location_kind, city, region, country_code, lat, lng, formatted_address, is_primary
    ) VALUES (v_org, r.base_label, 'OPS_BASE', r.city, r.region, r.country_code, r.lat, r.lng, r.formatted_address, true);
    INSERT INTO organization_contacts (
      organization_id, full_name, contact_type, title, email, phone_e164, is_primary
    ) VALUES (
      v_org, 'Guest / Concierge desk', 'Other', 'Bookings desk', r.email, r.phone, true
    );
    inserted := inserted + 1;
  END LOOP;
  RAISE NOTICE 'APAC mid bookers: inserted=% skipped=%', inserted, skipped;
END $$;
