-- VL Bookers: mid-upper UK (ex-London) + major EU city demand desks
-- Boutique / solid 4★ booking desks — not ultra-flagship, not budget 3★

DO $$
DECLARE
  v_hosp uuid := '8724134a-2249-4d87-83aa-167db279aab8';
  v_conc uuid := 'e857fe35-436d-49c1-a520-38ac9a199ea6';
  v_admin uuid := 'b3105232-0857-4eed-b022-d8147683c059';
  r record;
  v_org uuid;
  inserted int := 0;
  skipped int := 0;
BEGIN
  FOR r IN SELECT * FROM (VALUES
    ('Malmaison Birmingham Desk','Malmaison Birmingham','GB','https://www.malmaison.com/locations/birmingham/',NULL,'birmingham@malmaison.com','+441217943004',NULL,'The Mailbox','Birmingham','England','GB',52.475,-1.906,'The Mailbox, 1 Wharfside St, Birmingham B1 1RD','BOOKER_DEMAND UK Birmingham mid HOSPITALITY',v_hosp),
    ('Hotel du Vin Birmingham Desk','Hotel du Vin Birmingham','GB','https://www.hotelduvin.com/locations/birmingham/',NULL,'info.birmingham@hotelduvin.com','+441217943005',NULL,'Church Street','Birmingham','England','GB',52.481,-1.899,'25 Church Street, Birmingham B3 2NR','BOOKER_DEMAND UK Birmingham mid HOSPITALITY',v_hosp),
    ('Novotel Birmingham Centre Desk','Novotel Birmingham Centre','GB','https://all.accor.com/hotel/1077/index.en.shtml',NULL,'h1077@accor.com','+441216432000',NULL,'Broad Street','Birmingham','England','GB',52.477,-1.913,'70 Broad Street, Birmingham B1 2HT','BOOKER_DEMAND UK Birmingham mid HOSPITALITY',v_hosp),
    ('Malmaison Manchester Deansgate Desk','Malmaison Manchester','GB','https://www.malmaison.com/locations/manchester/',NULL,'manchester.deansgate@malmaison.com','+441618278000',NULL,'Piccadilly','Manchester','England','GB',53.478,-2.233,'1-3 Piccadilly, Manchester M1 1LZ','BOOKER_DEMAND UK Manchester mid HOSPITALITY',v_hosp),
    ('Dakota Manchester Desk','Dakota Manchester','GB','https://dakotahotels.co.uk/manchester/',NULL,'reservations@mcr.dakotahotels.co.uk','+441616749180',NULL,'Ducie Street','Manchester','England','GB',53.48,-2.23,'29 Ducie Street, Manchester M1 2JQ','BOOKER_DEMAND UK Manchester mid HOSPITALITY',v_hosp),
    ('Dakota Manchester Concierge','Dakota Manchester','GB','https://dakotahotels.co.uk/manchester/',NULL,'concierge@mcr.dakotahotels.co.uk','+441616749180',NULL,'Ducie Street','Manchester','England','GB',53.48,-2.23,'29 Ducie Street, Manchester M1 2JQ','BOOKER_DEMAND UK Manchester mid CONCIERGE',v_conc),
    ('The Lowry Hotel Desk','The Lowry Hotel','GB','https://www.thelowryhotel.com/',NULL,'reservations@thelowryhotel.com','+441618271000',NULL,'Salford Quays','Manchester','England','GB',53.483,-2.256,'50 Dearmans Place, Salford M3 5LH','BOOKER_DEMAND UK Manchester mid HOSPITALITY',v_hosp),
    ('Stock Exchange Hotel Desk','Stock Exchange Hotel','GB','https://stockexchangehotel.co.uk/',NULL,'reservations@stockexchangehotel.co.uk','+441612365000',NULL,'Norfolk Street','Manchester','England','GB',53.481,-2.243,'4 Norfolk Street, Manchester M2 1DW','BOOKER_DEMAND UK Manchester mid HOSPITALITY',v_hosp),
    ('King Street Townhouse Desk','King Street Townhouse','GB','https://www.eclectichotels.co.uk/king-street-townhouse/',NULL,'reservations@kingstreettownhouse.co.uk','+441616667000',NULL,'King Street','Manchester','England','GB',53.481,-2.245,'10 Booth Street, Manchester M2 4AW','BOOKER_DEMAND UK Manchester mid HOSPITALITY',v_hosp),
    ('Dakota Edinburgh Desk','Dakota Edinburgh','GB','https://dakotahotels.co.uk/edinburgh/',NULL,'reservations@edb.dakotahotels.co.uk','+441313193690',NULL,'Festival Square','Edinburgh','Scotland','GB',55.947,-3.207,'5 Festival Square, Edinburgh EH3 9SR','BOOKER_DEMAND UK Edinburgh mid HOSPITALITY',v_hosp),
    ('Virgin Hotels Edinburgh Desk','Virgin Hotels Edinburgh','GB','https://virginhotels.com/edinburgh/',NULL,'stay.edinburgh@virginhotels.com','+441315264810',NULL,'Chambers Street','Edinburgh','Scotland','GB',55.947,-3.188,'1 Chambers Street, Edinburgh EH1 1HR','BOOKER_DEMAND UK Edinburgh mid HOSPITALITY',v_hosp),
    ('Virgin Hotels Edinburgh Reservations','Virgin Hotels Edinburgh','GB','https://virginhotels.com/edinburgh/',NULL,'reservations.edinburgh@virginhotels.com','+441315264810',NULL,'Chambers Street','Edinburgh','Scotland','GB',55.947,-3.188,'1 Chambers Street, Edinburgh EH1 1HR','BOOKER_DEMAND UK Edinburgh mid HOSPITALITY',v_hosp),
    ('The Scotsman Hotel Desk','The Scotsman Hotel','GB','https://scotsmanhotel.co.uk/',NULL,'reservations@scotsmancollection.co.uk','+441315565565',NULL,'North Bridge','Edinburgh','Scotland','GB',55.952,-3.187,'20 North Bridge, Edinburgh EH1 1TR','BOOKER_DEMAND UK Edinburgh mid HOSPITALITY',v_hosp),
    ('24 Royal Terrace Desk','24 Royal Terrace','GB','https://24royalterrace.co.uk/',NULL,'reservations@24royalterrace.co.uk','+441312972424',NULL,'Royal Terrace','Edinburgh','Scotland','GB',55.957,-3.175,'24 Royal Terrace, Edinburgh EH7 5AH','BOOKER_DEMAND UK Edinburgh mid HOSPITALITY',v_hosp),
    ('Hotel du Vin Edinburgh Desk','Hotel du Vin Edinburgh','GB','https://www.hotelduvin.com/locations/edinburgh/',NULL,'reception.edinburgh@hotelduvin.com','+441312474900',NULL,'Bristo Place','Edinburgh','Scotland','GB',55.946,-3.189,'11 Bristo Place, Edinburgh EH1 1EZ','BOOKER_DEMAND UK Edinburgh mid HOSPITALITY',v_hosp),
    ('Mercure Edinburgh Haymarket Desk','Mercure Edinburgh Haymarket','GB','https://all.accor.com/hotel/9448/index.en.shtml',NULL,'h9448@accor.com','+441312970480',NULL,'Haymarket','Edinburgh','Scotland','GB',55.946,-3.218,'129 Grosvenor Street, Edinburgh EH12 5EF','BOOKER_DEMAND UK Edinburgh mid HOSPITALITY',v_hosp),
    ('Novotel Edinburgh Centre Desk','Novotel Edinburgh Centre','GB','https://all.accor.com/hotel/3271/index.en.shtml',NULL,'h3271@accor.com','+441316563500',NULL,'Lauriston Place','Edinburgh','Scotland','GB',55.944,-3.198,'80 Lauriston Place, Edinburgh EH3 9DE','BOOKER_DEMAND UK Edinburgh mid HOSPITALITY',v_hosp),
    ('Fingal Hotel Desk','Fingal','GB','https://www.fingal.co.uk/',NULL,'reservations@fingal.co.uk','+441313574999',NULL,'Port of Leith','Edinburgh','Scotland','GB',55.981,-3.174,'Alexandra Dock, Edinburgh EH6 7DX','BOOKER_DEMAND UK Edinburgh mid HOSPITALITY',v_hosp),
    ('The Bonham Edinburgh Desk','The Bonham Hotel','GB','https://thebonham.com/',NULL,'reserve@thebonham.com','+441312266050',NULL,'Drumsheugh Gardens','Edinburgh','Scotland','GB',55.951,-3.214,'35 Drumsheugh Gardens, Edinburgh EH3 7RN','BOOKER_DEMAND UK Edinburgh mid HOSPITALITY',v_hosp),
    ('Kimpton Charlotte Square Desk','Kimpton Charlotte Square Hotel','GB','https://www.kimptoncharlottesquare.com/',NULL,'reservations@kimptoncharlottesquare.com','+441312402500',NULL,'Charlotte Square','Edinburgh','Scotland','GB',55.952,-3.208,'38 Charlotte Square, Edinburgh EH2 4HQ','BOOKER_DEMAND UK Edinburgh mid HOSPITALITY',v_hosp),
    ('Dakota Glasgow Desk','Dakota Glasgow','GB','https://dakotahotels.co.uk/glasgow/',NULL,'reservations@gla.dakotahotels.co.uk','+441414043680',NULL,'West Regent Street','Glasgow','Scotland','GB',55.864,-4.261,'179 West Regent Street, Glasgow G2 4BE','BOOKER_DEMAND UK Glasgow mid HOSPITALITY',v_hosp),
    ('Hotel du Vin Glasgow Desk','Hotel du Vin Glasgow','GB','https://www.hotelduvin.com/locations/glasgow/',NULL,'reception.glasgow@hotelduvin.com','+441413780385',NULL,'One Devonshire Gardens','Glasgow','Scotland','GB',55.88,-4.298,'1 Devonshire Gardens, Glasgow G12 0UX','BOOKER_DEMAND UK Glasgow mid HOSPITALITY',v_hosp),
    ('Glasgow Grosvenor Hotel Desk','Glasgow Grosvenor Hotel','GB','https://www.gghotel.co.uk/',NULL,'reservations@gghotel.co.uk','+441413398811',NULL,'Great Western Road','Glasgow','Scotland','GB',55.877,-4.292,'1-9 Grosvenor Terrace, Glasgow G12 0TA','BOOKER_DEMAND UK Glasgow mid HOSPITALITY',v_hosp),
    ('Mercure Glasgow City Desk','Mercure Glasgow City','GB','https://all.accor.com/hotel/8336/index.en.shtml',NULL,'reservations@mercureglasgow.co.uk','+441414411022',NULL,'Ingram Street','Glasgow','Scotland','GB',55.86,-4.25,'201 Ingram Street, Glasgow G1 1DQ','BOOKER_DEMAND UK Glasgow mid HOSPITALITY',v_hosp),
    ('citizenM Glasgow Desk','citizenM Glasgow','GB','https://www.citizenm.com/hotels/europe/glasgow/glasgow-hotel',NULL,'glasgow@citizenm.com','+441414045530',NULL,'Bothwell Street','Glasgow','Scotland','GB',55.861,-4.262,'60 Bothwell Street, Glasgow G2 6QY','BOOKER_DEMAND UK Glasgow mid HOSPITALITY',v_hosp),
    ('Hotel du Vin Bristol Desk','Hotel du Vin Bristol','GB','https://www.hotelduvin.com/locations/bristol/',NULL,'info.bristol@hotelduvin.com','+441174032979',NULL,'Narrow Lewins Mead','Bristol','England','GB',51.456,-2.595,'The Sugar House, Narrow Lewins Mead, Bristol BS1 2NU','BOOKER_DEMAND UK Bristol mid HOSPITALITY',v_hosp),
    ('Hotel du Vin Bristol Reservations','Hotel du Vin Bristol','GB','https://www.hotelduvin.com/locations/bristol/',NULL,'reservations.bristol@hotelduvin.com','+441174032979',NULL,'Narrow Lewins Mead','Bristol','England','GB',51.456,-2.595,'The Sugar House, Narrow Lewins Mead, Bristol BS1 2NU','BOOKER_DEMAND UK Bristol mid HOSPITALITY',v_hosp),
    ('Mercure Bristol North Desk','Mercure Bristol North the Grange','GB','https://all.accor.com/hotel/8323/index.en.shtml',NULL,'reservations@mercurebristol.co.uk','+441454355012',NULL,'Winterbourne','Bristol','England','GB',51.539,-2.523,'Old Gloucester Road, Winterbourne, Bristol BS36 1RP','BOOKER_DEMAND UK Bristol mid HOSPITALITY',v_hosp),
    ('The Bristol Hotel Desk','The Bristol Hotel','GB','https://www.doylecollection.com/hotels/the-bristol-hotel',NULL,'bristol@doylecollection.com','+441179236000',NULL,'Prince Street','Bristol','England','GB',51.449,-2.598,'Prince Street, Bristol BS1 4QF','BOOKER_DEMAND UK Bristol mid HOSPITALITY',v_hosp),
    ('Dakota Leeds Desk','Dakota Leeds','GB','https://dakotahotels.co.uk/leeds/',NULL,'reservations@lds.dakotahotels.co.uk','+441133226261',NULL,'Russell Street','Leeds','England','GB',53.799,-1.547,'8 Russell Street, Leeds LS1 5RN','BOOKER_DEMAND UK Leeds mid HOSPITALITY',v_hosp),
    ('Dakota Leeds Concierge','Dakota Leeds','GB','https://dakotahotels.co.uk/leeds/',NULL,'events@lds.dakotahotels.co.uk','+441133226261',NULL,'Russell Street','Leeds','England','GB',53.799,-1.547,'8 Russell Street, Leeds LS1 5RN','BOOKER_DEMAND UK Leeds mid CONCIERGE',v_conc),
    ('The Queens Hotel Leeds Desk','The Queens Hotel Leeds','GB','https://www.thequeenshotel.co.uk/',NULL,'reservations@thequeenshotelleeds.co.uk','+441132431323',NULL,'City Square','Leeds','England','GB',53.796,-1.548,'City Square, Leeds LS1 1PJ','BOOKER_DEMAND UK Leeds mid HOSPITALITY',v_hosp),
    ('Malmaison Liverpool Desk','Malmaison Liverpool','GB','https://www.malmaison.com/locations/liverpool/',NULL,'liverpool@malmaison.com','+441512290000',NULL,'William Jessop Way','Liverpool','England','GB',53.405,-2.995,'7 William Jessop Way, Liverpool L3 1QZ','BOOKER_DEMAND UK Liverpool mid HOSPITALITY',v_hosp),
    ('Pullman Liverpool Desk','Pullman Liverpool','GB','https://all.accor.com/hotel/9227/index.en.shtml',NULL,'h9227-fo@accor.com','+441519451000',NULL,'Kings Dock','Liverpool','England','GB',53.396,-2.989,'Kings Dock, Liverpool L3 4FP','BOOKER_DEMAND UK Liverpool mid HOSPITALITY',v_hosp),
    ('Hotel Indigo Liverpool Desk','Hotel Indigo Liverpool','GB','https://www.ihg.com/hotelindigo/hotels/gb/en/liverpool/lplil/hoteldetail',NULL,'reservations@hotelindigoliverpool.com','+441515590111',NULL,'Chapel Street','Liverpool','England','GB',53.408,-2.992,'10 Chapel Street, Liverpool L3 9AG','BOOKER_DEMAND UK Liverpool mid HOSPITALITY',v_hosp),
    ('Hard Days Night Hotel Desk','Hard Days Night Hotel','GB','https://www.harddaysnighthotel.com/',NULL,'reservations@harddaysnighthotel.com','+441512361969',NULL,'North John Street','Liverpool','England','GB',53.406,-2.987,'41 North John Street, Liverpool L2 6RR','BOOKER_DEMAND UK Liverpool mid HOSPITALITY',v_hosp),
    ('Titanic Hotel Liverpool Desk','Titanic Hotel Liverpool','GB','https://www.titanichotelliverpool.com/',NULL,'reservations@titanichotelliverpool.com','+441515590000',NULL,'Stanley Dock','Liverpool','England','GB',53.421,-2.999,'Stanley Dock, Regent Road, Liverpool L3 0AN','BOOKER_DEMAND UK Liverpool mid HOSPITALITY',v_hosp),
    ('Hope Street Hotel Desk','Hope Street Hotel','GB','https://www.hopestreethotel.co.uk/',NULL,'reservations@hopestreethotel.co.uk','+441517091091',NULL,'Hope Street','Liverpool','England','GB',53.401,-2.97,'40 Hope Street, Liverpool L1 9DA','BOOKER_DEMAND UK Liverpool mid HOSPITALITY',v_hosp),
    ('Abbey Hotel Bath Desk','Abbey Hotel Bath','GB','https://www.abbeyhotelbath.co.uk/',NULL,'reservations@abbeyhotelbath.co.uk','+441225461603',NULL,'North Parade','Bath','England','GB',51.38,-2.358,'North Parade, Bath BA1 1LF','BOOKER_DEMAND UK Bath mid HOSPITALITY',v_hosp),
    ('The Queensberry Hotel Desk','The Queensberry Hotel','GB','https://www.thequeensberry.co.uk/',NULL,'reservations@thequeensberry.co.uk','+441225447928',NULL,'Russell Street','Bath','England','GB',51.388,-2.363,'Russell Street, Bath BA1 2QF','BOOKER_DEMAND UK Bath mid HOSPITALITY',v_hosp),
    ('The Royal Crescent Hotel Desk','The Royal Crescent Hotel & Spa','GB','https://www.royalcrescent.co.uk/',NULL,'info@royalcrescent.co.uk','+441225823333',NULL,'Royal Crescent','Bath','England','GB',51.387,-2.368,'16 Royal Crescent, Bath BA1 2LS','BOOKER_DEMAND UK Bath mid HOSPITALITY',v_hosp),
    ('No15 Great Pulteney Desk','No.15 Great Pulteney','GB','https://www.no15greatpulteney.co.uk/',NULL,'reservations@no15greatpulteney.co.uk','+441225316159',NULL,'Great Pulteney Street','Bath','England','GB',51.383,-2.353,'15 Great Pulteney Street, Bath BA2 4BS','BOOKER_DEMAND UK Bath mid HOSPITALITY',v_hosp),
    ('The Gainsborough Bath Spa Desk','The Gainsborough Bath Spa','GB','https://www.thegainsboroughbathspa.co.uk/',NULL,'reservations@thegainsboroughbathspa.co.uk','+441225358888',NULL,'Beau Street','Bath','England','GB',51.38,-2.36,'Beau Street, Bath BA1 1QY','BOOKER_DEMAND UK Bath mid HOSPITALITY',v_hosp),
    ('Malmaison Oxford Desk','Malmaison Oxford','GB','https://www.malmaison.com/locations/oxford/',NULL,'reception.oxford@malmaison.com','+441865268400',NULL,'Oxford Castle','Oxford','England','GB',51.751,-1.263,'3 Oxford Castle, Oxford OX1 1AY','BOOKER_DEMAND UK Oxford mid HOSPITALITY',v_hosp),
    ('Old Bank Hotel Oxford Desk','Old Bank Hotel','GB','https://www.oldbankhotel.co.uk/',NULL,'reservations@oldbankhotel.co.uk','+441865799599',NULL,'High Street','Oxford','England','GB',51.752,-1.255,'92-94 High Street, Oxford OX1 4BJ','BOOKER_DEMAND UK Oxford mid HOSPITALITY',v_hosp),
    ('Old Parsonage Hotel Desk','Old Parsonage Hotel','GB','https://www.oldparsonage-hotel.co.uk/',NULL,'info@oldparsonage-hotel.co.uk','+441865310210',NULL,'Banbury Road','Oxford','England','GB',51.761,-1.26,'1 Banbury Road, Oxford OX2 6NN','BOOKER_DEMAND UK Oxford mid HOSPITALITY',v_hosp),
    ('The Randolph Hotel Desk','The Randolph Hotel','GB','https://www.graduatehotels.com/oxford/',NULL,'reservations.oxford@graduatehotels.com','+441865256400',NULL,'Beaumont Street','Oxford','England','GB',51.755,-1.26,'Beaumont Street, Oxford OX1 2LN','BOOKER_DEMAND UK Oxford mid HOSPITALITY',v_hosp),
    ('Hotel du Vin Cambridge Desk','Hotel du Vin Cambridge','GB','https://www.hotelduvin.com/locations/cambridge/',NULL,'info.cambridge@hotelduvin.com','+441223227330',NULL,'Trumpington Street','Cambridge','England','GB',52.201,-0.119,'15-19 Trumpington Street, Cambridge CB2 1QA','BOOKER_DEMAND UK Cambridge mid HOSPITALITY',v_hosp),
    ('University Arms Cambridge Desk','University Arms','GB','https://www.universityarms.com/',NULL,'reservations@universityarms.com','+441223606066',NULL,'Regent Street','Cambridge','England','GB',52.201,-0.124,'Regent Street, Cambridge CB2 1AD','BOOKER_DEMAND UK Cambridge mid HOSPITALITY',v_hosp),
    ('Hotel du Vin Brighton Desk','Hotel du Vin Brighton','GB','https://www.hotelduvin.com/locations/brighton/',NULL,'reception.brighton@hotelduvin.com','+441273718588',NULL,'Ship Street','Brighton','England','GB',50.821,-0.142,'2 Ship Street, Brighton BN1 1AD','BOOKER_DEMAND UK Brighton mid HOSPITALITY',v_hosp),
    ('Artist Residence Brighton Desk','Artist Residence Brighton','GB','https://www.artistresidence.co.uk/brighton/',NULL,'brighton@artistresidence.co.uk','+441273324302',NULL,'Regency Square','Brighton','England','GB',50.823,-0.154,'33 Regency Square, Brighton BN1 2GG','BOOKER_DEMAND UK Brighton mid HOSPITALITY',v_hosp),
    ('The Grand Brighton Desk','The Grand Brighton','GB','https://www.grandbrighton.co.uk/',NULL,'reservations@grandbrighton.co.uk','+441273224300',NULL,'King''s Road','Brighton','England','GB',50.821,-0.147,'97-99 King''s Road, Brighton BN1 2FW','BOOKER_DEMAND UK Brighton mid HOSPITALITY',v_hosp),
    ('Drakes Brighton Desk','Drakes of Brighton','GB','https://www.drakesofbrighton.com/',NULL,'info@drakesofbrighton.com','+441273696934',NULL,'Marine Parade','Brighton','England','GB',50.819,-0.126,'43-44 Marine Parade, Brighton BN2 1PE','BOOKER_DEMAND UK Brighton mid HOSPITALITY',v_hosp),
    ('The Hoxton Paris Desk','The Hoxton Paris','FR','https://thehoxton.com/paris/',NULL,'book.paris@thehox.com','+33185657500',NULL,'Rue du Sentier','Paris','Île-de-France','FR',48.868,2.348,'30-32 Rue du Sentier, 75002 Paris','BOOKER_DEMAND EU Paris mid HOSPITALITY',v_hosp),
    ('Hotel La Belle Juliette Desk','Hotel & Spa La Belle Juliette','FR','https://www.hotel-belle-juliette-paris.com/',NULL,'reservation@labellejuliette.com','+33142229740',NULL,'Cherche Midi','Paris','Île-de-France','FR',48.849,2.324,'92 Rue du Cherche Midi, 75006 Paris','BOOKER_DEMAND EU Paris mid HOSPITALITY',v_hosp),
    ('Hotel R de Paris Desk','Hotel R de Paris','FR','https://hotelrdeparis.com/',NULL,'reservation@hotelrdeparis.com','+33140823620',NULL,'Rue de Clichy','Paris','Île-de-France','FR',48.881,2.328,'41 Rue de Clichy, 75009 Paris','BOOKER_DEMAND EU Paris mid HOSPITALITY',v_hosp),
    ('9Hotel Opera Paris Desk','9Hotel Opéra','FR','https://www.9-hotel-opera-paris.fr/',NULL,'info@le9hotel-opera.com','+33147707834',NULL,'Rue Papillon','Paris','Île-de-France','FR',48.877,2.346,'14 Rue Papillon, 75009 Paris','BOOKER_DEMAND EU Paris mid HOSPITALITY',v_hosp),
    ('9Hotel Republique Paris Desk','9Hotel République','FR','https://www.9-hotel-republique-paris.fr/',NULL,'info@le9hotel-republique.com','+33140181100',NULL,'Rue Pierre Chausson','Paris','Île-de-France','FR',48.872,2.36,'9 Rue Pierre Chausson, 75010 Paris','BOOKER_DEMAND EU Paris mid HOSPITALITY',v_hosp),
    ('Mercure Paris Gare de Lyon Desk','Mercure Paris Gare de Lyon','FR','https://all.accor.com/hotel/2217/index.en.shtml',NULL,'h2217@accor.com','+33143448484',NULL,'Gare de Lyon','Paris','Île-de-France','FR',48.845,2.374,'2 Place Louis Armand, 75012 Paris','BOOKER_DEMAND EU Paris mid HOSPITALITY',v_hosp),
    ('Mercure Paris Bastille Desk','Mercure Paris Gare de Lyon Opéra Bastille','FR','https://all.accor.com/hotel/B6F9/index.en.shtml',NULL,'hb6f9@accor.com','+33143434152',NULL,'Bastille','Paris','Île-de-France','FR',48.85,2.37,'3 Rue Traversière, 75012 Paris','BOOKER_DEMAND EU Paris mid HOSPITALITY',v_hosp),
    ('Hotel Joyce Starhotels Desk','Hotel Joyce - Starhotels Collezione','FR','https://collezione.starhotels.com/en/our-hotels/hotel-joyce-paris/',NULL,'reservations.joyce@starhotels.com','+33155071515',NULL,'Rue la Bruyère','Paris','Île-de-France','FR',48.879,2.334,'29 Rue la Bruyère, 75009 Paris','BOOKER_DEMAND EU Paris mid HOSPITALITY',v_hosp),
    ('citizenM Paris Gare de Lyon Desk','citizenM Paris Gare de Lyon','FR','https://www.citizenm.com/hotels/europe/paris/paris-gare-de-lyon-hotel',NULL,'paris.garedelyon@citizenm.com','+33186868000',NULL,'Gare de Lyon','Paris','Île-de-France','FR',48.844,2.374,'8 Rue Van Gogh, 75012 Paris','BOOKER_DEMAND EU Paris mid HOSPITALITY',v_hosp),
    ('The Hoxton Amsterdam Desk','The Hoxton Amsterdam','NL','https://thehoxton.com/amsterdam/herengracht/',NULL,'book.amsterdam@thehox.com','+31208885555',NULL,'Herengracht','Amsterdam','North Holland','NL',52.373,4.886,'Herengracht 255, 1016 BJ Amsterdam','BOOKER_DEMAND EU Amsterdam mid HOSPITALITY',v_hosp),
    ('The Hoxton Amsterdam Concierge','The Hoxton Amsterdam','NL','https://thehoxton.com/amsterdam/herengracht/',NULL,'hello.amsterdam@thehox.com','+31208885555',NULL,'Herengracht','Amsterdam','North Holland','NL',52.373,4.886,'Herengracht 255, 1016 BJ Amsterdam','BOOKER_DEMAND EU Amsterdam mid CONCIERGE',v_conc),
    ('Kimpton De Witt Desk','Kimpton De Witt Amsterdam','NL','https://www.kimptondewitthotel.com/',NULL,'reservations@kimptondewitthotel.com','+31205211888',NULL,'Nieuwezijds Voorburgwal','Amsterdam','North Holland','NL',52.376,4.893,'Nieuwezijds Voorburgwal 5, 1012 RC Amsterdam','BOOKER_DEMAND EU Amsterdam mid HOSPITALITY',v_hosp),
    ('Mercure Amsterdam City Desk','Mercure Amsterdam City','NL','https://all.accor.com/hotel/1244/index.en.shtml',NULL,'h1244@accor.com','+31207219176',NULL,'Joan Muyskenweg','Amsterdam','North Holland','NL',52.336,4.918,'Joan Muyskenweg 10, 1096 CJ Amsterdam','BOOKER_DEMAND EU Amsterdam mid HOSPITALITY',v_hosp),
    ('Mercure Amsterdam Sloterdijk Desk','Mercure Amsterdam Sloterdijk Station','NL','https://all.accor.com/hotel/9844/index.en.shtml',NULL,'h9844@accor.com','+31208202999',NULL,'Sloterdijk','Amsterdam','North Holland','NL',52.388,4.834,'Naritaweg 1, 1043 BP Amsterdam','BOOKER_DEMAND EU Amsterdam mid HOSPITALITY',v_hosp),
    ('Hotel Estherea Desk','Hotel Estheréa','NL','https://www.estherea.nl/',NULL,'estherea@estherea.nl','+31206235162',NULL,'Singel','Amsterdam','North Holland','NL',52.373,4.889,'Singel 303-309, 1012 WJ Amsterdam','BOOKER_DEMAND EU Amsterdam mid HOSPITALITY',v_hosp),
    ('Ambassade Hotel Desk','Ambassade Hotel','NL','https://www.ambassade-hotel.nl/',NULL,'info@ambassade-hotel.nl','+31205550222',NULL,'Herengracht','Amsterdam','North Holland','NL',52.367,4.885,'Herengracht 341, 1016 AZ Amsterdam','BOOKER_DEMAND EU Amsterdam mid HOSPITALITY',v_hosp),
    ('citizenM Amsterdam Desk','citizenM Amsterdam','NL','https://www.citizenm.com/hotels/europe/amsterdam/amsterdam-city-hotel',NULL,'amsterdam@citizenm.com','+31208118170',NULL,'Prins Hendrikkade','Amsterdam','North Holland','NL',52.377,4.904,'Prins Hendrikkade 108, 1011 AK Amsterdam','BOOKER_DEMAND EU Amsterdam mid HOSPITALITY',v_hosp),
    ('9Hotel Sablon Desk','9Hotel Sablon','BE','https://www.9-hotel-sablon-brussels.be/',NULL,'info@le9hotel-sablon.com','+3228800701',NULL,'Sablon','Brussels','Brussels','BE',50.84,4.354,'Rue de la Paille 2, 1000 Bruxelles','BOOKER_DEMAND EU Brussels mid HOSPITALITY',v_hosp),
    ('9Hotel Chelton Desk','9Hotel Chelton','BE','https://www.9-hotel-chelton-brussels.be/',NULL,'info@le9hotel-chelton.com','+3227474760',NULL,'Rue Véronèse','Brussels','Brussels','BE',50.836,4.385,'Rue Véronèse 48, 1000 Bruxelles','BOOKER_DEMAND EU Brussels mid HOSPITALITY',v_hosp),
    ('9Hotel Central Brussels Desk','9Hotel Central','BE','https://www.9-hotel-central-brussels.be/',NULL,'info@le9hotel-central.com','+3222190040',NULL,'Centre','Brussels','Brussels','BE',50.847,4.357,'Rue des Colonies 10, 1000 Bruxelles','BOOKER_DEMAND EU Brussels mid HOSPITALITY',v_hosp),
    ('Hotel Le Dixseptieme Desk','Hotel Le Dixseptième','BE','https://www.ledixseptieme.be/',NULL,'info@ledixseptieme.be','+3225171717',NULL,'Rue de la Madeleine','Brussels','Brussels','BE',50.846,4.354,'Rue de la Madeleine 25, 1000 Bruxelles','BOOKER_DEMAND EU Brussels mid HOSPITALITY',v_hosp),
    ('Hotel Amigo Desk','Hotel Amigo','BE','https://www.roccofortehotels.com/hotels-and-resorts/hotel-amigo/',NULL,'reservations.amigo@roccofortehotels.com','+3225474747',NULL,'Rue de l''Amigo','Brussels','Brussels','BE',50.846,4.351,'Rue de l''Amigo 1-3, 1000 Bruxelles','BOOKER_DEMAND EU Brussels mid HOSPITALITY',v_hosp),
    ('The Dominican Brussels Desk','The Dominican','BE','https://www.thedominican.be/',NULL,'info@thedominican.be','+3222030808',NULL,'Rue Léopold','Brussels','Brussels','BE',50.849,4.354,'Rue Léopold 9, 1000 Bruxelles','BOOKER_DEMAND EU Brussels mid HOSPITALITY',v_hosp),
    ('The Dean Dublin Desk','The Dean Dublin','IE','https://thedeanhotels.com/locations/dublin-centre',NULL,'hello.dublin@thedeanhotels.com','+35316078110',NULL,'Harcourt Street','Dublin','Leinster','IE',53.334,-6.263,'33 Harcourt Street, Dublin 2, D02 WC81','BOOKER_DEMAND EU Dublin mid HOSPITALITY',v_hosp),
    ('The Westbury Dublin Desk','The Westbury','IE','https://www.doylecollection.com/hotels/the-westbury-hotel',NULL,'westbury@doylecollection.com','+35316791122',NULL,'Grafton Street','Dublin','Leinster','IE',53.341,-6.261,'Grafton Street, Dublin 2, D02 H248','BOOKER_DEMAND EU Dublin mid HOSPITALITY',v_hosp),
    ('The Croke Park Hotel Desk','The Croke Park','IE','https://www.doylecollection.com/hotels/the-croke-park-hotel',NULL,'crokepark@doylecollection.com','+35318714444',NULL,'Jones''s Road','Dublin','Leinster','IE',53.36,-6.252,'Jones''s Road, Dublin 3, D03 E5Y8','BOOKER_DEMAND EU Dublin mid HOSPITALITY',v_hosp),
    ('The Morrison Dublin Desk','The Morrison Dublin','IE','https://www.morrisonhotel.ie/',NULL,'reservations@morrisonhotel.ie','+35318872400',NULL,'Ormond Quay','Dublin','Leinster','IE',53.347,-6.266,'Ormond Quay Lower, Dublin 1, D01 A9N4','BOOKER_DEMAND EU Dublin mid HOSPITALITY',v_hosp),
    ('Number 31 Dublin Desk','Number 31','IE','https://www.number31.ie/',NULL,'info@number31.ie','+35316765011',NULL,'Leeson Close','Dublin','Leinster','IE',53.333,-6.254,'31 Leeson Close, Dublin 2, D02 XF75','BOOKER_DEMAND EU Dublin mid HOSPITALITY',v_hosp),
    ('Hotel Indigo Barcelona Plaza Espana Desk','Hotel Indigo Barcelona Plaza España','ES','https://www.ihg.com/hotelindigo/hotels/us/en/barcelona/bcndg/hoteldetail',NULL,'reception@indigobarcelonaplazaespana.com','+34933675500',NULL,'Plaza España','Barcelona','Catalonia','ES',41.375,2.149,'Gran Via de les Corts Catalanes 322, 08004 Barcelona','BOOKER_DEMAND EU Barcelona mid HOSPITALITY',v_hosp),
    ('Hotel Indigo Barcelona Catalunya Desk','Hotel Indigo Barcelona Plaza Catalunya','ES','https://www.indigobarcelona.com/',NULL,'info@indigobarcelona.com','+34936026690',NULL,'Plaza Catalunya','Barcelona','Catalonia','ES',41.389,2.168,'Gran Via de les Corts Catalanes 629, 08010 Barcelona','BOOKER_DEMAND EU Barcelona mid HOSPITALITY',v_hosp),
    ('Hotel Casa Fuster Desk','Hotel Casa Fuster','ES','https://www.hotelcasafuster.com/',NULL,'reservas@hotelcasafuster.com','+34932255800',NULL,'Passeig de Gràcia','Barcelona','Catalonia','ES',41.399,2.157,'Passeig de Gràcia 132, 08008 Barcelona','BOOKER_DEMAND EU Barcelona mid HOSPITALITY',v_hosp),
    ('Hotel 1898 Desk','Hotel 1898','ES','https://www.hotel1898.com/',NULL,'info@hotel1898.com','+34935529000',NULL,'La Rambla','Barcelona','Catalonia','ES',41.381,2.174,'La Rambla 109, 08002 Barcelona','BOOKER_DEMAND EU Barcelona mid HOSPITALITY',v_hosp),
    ('Hotel Mercer Barcelona Desk','Hotel Mercer Barcelona','ES','https://www.mercerbarcelona.com/',NULL,'reservas@mercerbarcelona.com','+34933102060',NULL,'Carrer dels Lledó','Barcelona','Catalonia','ES',41.383,2.178,'Carrer dels Lledó 7, 08002 Barcelona','BOOKER_DEMAND EU Barcelona mid HOSPITALITY',v_hosp),
    ('Hotel Brummell Desk','Hotel Brummell','ES','https://www.hotelbrummell.com/',NULL,'hello@hotelbrummell.com','+34934816320',NULL,'Nou de la Rambla','Barcelona','Catalonia','ES',41.374,2.172,'Nou de la Rambla 174, 08004 Barcelona','BOOKER_DEMAND EU Barcelona mid HOSPITALITY',v_hosp),
    ('Casa Camper Barcelona Desk','Casa Camper Barcelona','ES','https://www.casacamper.com/barcelona',NULL,'barcelona@casacamper.com','+34933426280',NULL,'El Raval','Barcelona','Catalonia','ES',41.383,2.168,'Carrer d''Elisabets 11, 08001 Barcelona','BOOKER_DEMAND EU Barcelona mid HOSPITALITY',v_hosp),
    ('Hotel Indigo Madrid Desk','Hotel Indigo Madrid - Gran Vía','ES','https://www.indigomadrid.com/',NULL,'info@indigomadrid.com','+34912008585',NULL,'Gran Vía','Madrid','Madrid','ES',40.421,-3.706,'Calle de Silva 6, 28013 Madrid','BOOKER_DEMAND EU Madrid mid HOSPITALITY',v_hosp),
    ('Hotel Indigo Madrid Sales Desk','Hotel Indigo Madrid - Gran Vía','ES','https://www.indigomadrid.com/',NULL,'sales@indigomadrid.com','+34912008585',NULL,'Gran Vía','Madrid','Madrid','ES',40.421,-3.706,'Calle de Silva 6, 28013 Madrid','BOOKER_DEMAND EU Madrid mid HOSPITALITY',v_hosp),
    ('Hotel Unico Madrid Desk','Hotel Único Madrid','ES','https://www.unicohotelmadrid.com/',NULL,'reservas@unicohotelmadrid.com','+34917807810',NULL,'Salamanca','Madrid','Madrid','ES',40.43,-3.686,'Calle de Claudio Coello 67, 28001 Madrid','BOOKER_DEMAND EU Madrid mid HOSPITALITY',v_hosp),
    ('Only YOU Boutique Madrid Desk','Only YOU Boutique Hotel Madrid','ES','https://www.onlyyouhotels.com/en/hotels/only-you-boutique-hotel-madrid/',NULL,'boutique@onlyyouhotels.com','+34910005200',NULL,'Barquillo','Madrid','Madrid','ES',40.415,-3.698,'Calle del Barquillo 21, 28004 Madrid','BOOKER_DEMAND EU Madrid mid HOSPITALITY',v_hosp),
    ('Hotel Urban Madrid Desk','Hotel Urban','ES','https://www.derbyhotels.com/en/hotel-urban-madrid/',NULL,'urban@derbyhotels.com','+34917877770',NULL,'Carrera de San Jerónimo','Madrid','Madrid','ES',40.416,-3.698,'Carrera de San Jerónimo 34, 28014 Madrid','BOOKER_DEMAND EU Madrid mid HOSPITALITY',v_hosp),
    ('Vincci Soma Desk','Vincci Soma','ES','https://www.vinccihoteles.com/eng/Hotels/Spain/Madrid/Vincci-Soma',NULL,'soma@vinccihoteles.com','+34914360400',NULL,'Goya','Madrid','Madrid','ES',40.43,-3.68,'Calle de Goya 79, 28001 Madrid','BOOKER_DEMAND EU Madrid mid HOSPITALITY',v_hosp),
    ('Hotel Emperador Desk','Hotel Emperador','ES','https://www.emperadorhotel.com/',NULL,'reservas@emperadorhotel.com','+34915472800',NULL,'Gran Vía','Madrid','Madrid','ES',40.422,-3.71,'Gran Vía 53, 28013 Madrid','BOOKER_DEMAND EU Madrid mid HOSPITALITY',v_hosp),
    ('Hotel Indigo Milan Desk','Hotel Indigo Milan - Corso Monforte','IT','https://www.ihg.com/hotelindigo/hotels/us/en/milan/linit/hoteldetail',NULL,'info@indigomilano.it','+390238254500',NULL,'Corso Monforte','Milan','Lombardy','IT',45.467,9.202,'Corso Monforte 27, 20122 Milano','BOOKER_DEMAND EU Milan mid HOSPITALITY',v_hosp),
    ('Hotel Viu Milan Desk','Hotel Viu Milan','IT','https://www.hotelviumilan.com/',NULL,'info@hotelviumilan.com','+3902870781',NULL,'Via Torriani','Milan','Lombardy','IT',45.485,9.203,'Via Torriani 6, 20124 Milano','BOOKER_DEMAND EU Milan mid HOSPITALITY',v_hosp),
    ('Magna Pars Milan Desk','Magna Pars Suites Milano','IT','https://www.magnapars-suitesmilano.it/',NULL,'info@magnapars.it','+3902870831',NULL,'Via Forcella','Milan','Lombardy','IT',45.451,9.174,'Via Forcella 6, 20144 Milano','BOOKER_DEMAND EU Milan mid HOSPITALITY',v_hosp),
    ('Magna Pars Milan Concierge','Magna Pars Suites Milano','IT','https://www.magnapars-suitesmilano.it/',NULL,'concierge@magnapars.it','+3902870831',NULL,'Via Forcella','Milan','Lombardy','IT',45.451,9.174,'Via Forcella 6, 20144 Milano','BOOKER_DEMAND EU Milan mid CONCIERGE',v_conc),
    ('Hotel Milano Scala Desk','Hotel Milano Scala','IT','https://www.hotelmilanoscala.it/',NULL,'info@hotelmilanoscala.it','+3902870871',NULL,'Via dell''Orso','Milan','Lombardy','IT',45.468,9.186,'Via dell''Orso 7, 20121 Milano','BOOKER_DEMAND EU Milan mid HOSPITALITY',v_hosp),
    ('The Yard Milano Desk','The Yard Milano','IT','https://www.theyardmilano.com/',NULL,'info@theyardmilano.com','+39028709500',NULL,'Piazza XXIV Maggio','Milan','Lombardy','IT',45.453,9.183,'Piazza XXIV Maggio 8, 20123 Milano','BOOKER_DEMAND EU Milan mid HOSPITALITY',v_hosp),
    ('Chateau Monfort Desk','Château Monfort','IT','https://www.hotelchateaumonfort.com/',NULL,'info@hotelchateaumonfort.com','+3902761161',NULL,'Corso Concordia','Milan','Lombardy','IT',45.467,9.206,'Corso Concordia 1, 20129 Milano','BOOKER_DEMAND EU Milan mid HOSPITALITY',v_hosp),
    ('9Hotel Cesari Rome Desk','9Hotel Cesàri','IT','https://www.9-hotel-cesari-rome.it/',NULL,'info@9hotelcesari.com','+39066749701',NULL,'Via di Pietra','Rome','Lazio','IT',41.899,12.48,'Via di Pietra 89/A, 00186 Roma','BOOKER_DEMAND EU Rome mid HOSPITALITY',v_hosp),
    ('Hotel Indigo Rome Concierge','Hotel Indigo Rome - St. George','IT','https://www.ihg.com/hotelindigo/hotels/us/en/rome/romsg/hoteldetail',NULL,'concierge@stgeorgerome.com','+3906686611',NULL,'Via Giulia','Rome','Lazio','IT',41.897,12.468,'Via Giulia 62, 00186 Roma','BOOKER_DEMAND EU Rome mid CONCIERGE',v_conc),
    ('Hotel Artemide Desk','Hotel Artemide','IT','https://www.hotelartemide.it/',NULL,'info@hotelartemide.it','+3906489911',NULL,'Via Nazionale','Rome','Lazio','IT',41.901,12.494,'Via Nazionale 22, 00184 Roma','BOOKER_DEMAND EU Rome mid HOSPITALITY',v_hosp),
    ('Hotel Quirinale Desk','Hotel Quirinale','IT','https://www.hotelquirinale.it/',NULL,'info@hotelquirinale.it','+390648953',NULL,'Via Nazionale','Rome','Lazio','IT',41.9,12.494,'Via Nazionale 7, 00184 Roma','BOOKER_DEMAND EU Rome mid HOSPITALITY',v_hosp),
    ('The First Roma Arte Desk','The First Roma Arte','IT','https://www.thefirsthotel.com/',NULL,'arte@thefirsthotel.com','+3906422001',NULL,'Via del Viminale','Rome','Lazio','IT',41.9,12.496,'Via del Viminale 30, 00184 Roma','BOOKER_DEMAND EU Rome mid HOSPITALITY',v_hosp),
    ('Novotel Munich City Desk','Novotel München City','DE','https://all.accor.com/hotel/3280/index.en.shtml',NULL,'h3280@accor.com','+4989661070',NULL,'Hochstraße','Munich','Bavaria','DE',48.129,11.595,'Hochstraße 11, 81669 München','BOOKER_DEMAND EU Munich mid HOSPITALITY',v_hosp),
    ('Novotel Munich Messe Desk','Novotel München Messe','DE','https://all.accor.com/hotel/5563/index.en.shtml',NULL,'h5563@accor.com','+4989994000',NULL,'Willy-Brandt-Allee','Munich','Bavaria','DE',48.134,11.694,'Willy-Brandt-Allee 3, 81829 München','BOOKER_DEMAND EU Munich mid HOSPITALITY',v_hosp),
    ('Hotel Torbraeu Desk','Hotel Torbräu','DE','https://www.torbraeu.de/',NULL,'info@torbraeu.de','+4989242261',NULL,'Tal','Munich','Bavaria','DE',48.136,11.581,'Tal 41, 80331 München','BOOKER_DEMAND EU Munich mid HOSPITALITY',v_hosp),
    ('Louis Hotel Munich Desk','Louis Hotel','DE','https://www.louis-hotel.com/',NULL,'info@louis-hotel.com','+498941114080',NULL,'Viktualienmarkt','Munich','Bavaria','DE',48.135,11.576,'Viktualienmarkt 6, 80331 München','BOOKER_DEMAND EU Munich mid HOSPITALITY',v_hosp),
    ('Hotel Cortiina Desk','Hotel Cortiina','DE','https://www.cortiina.com/',NULL,'info@cortiina.com','+4989242249',NULL,'Ledererstraße','Munich','Bavaria','DE',48.137,11.579,'Ledererstraße 8, 80331 München','BOOKER_DEMAND EU Munich mid HOSPITALITY',v_hosp),
    ('LUME Boutique Hotel Desk','LUME Boutique Hotel','DE','https://lumeboutiquehotel.com/',NULL,'info@lumeboutiquehotel.com','+4969756660',NULL,'Neckarstraße','Frankfurt','Hesse','DE',50.107,8.664,'Neckarstraße 7-13, 60329 Frankfurt am Main','BOOKER_DEMAND EU Frankfurt mid HOSPITALITY',v_hosp),
    ('25hours Frankfurt The Trip Desk','25hours Hotel Frankfurt The Trip','DE','https://25hours-hotels.com/hotels/frankfurt-the-trip/',NULL,'frankfurt@25hours-hotels.com','+4969256820',NULL,'Niddastraße','Frankfurt','Hesse','DE',50.108,8.663,'Niddastraße 58, 60329 Frankfurt am Main','BOOKER_DEMAND EU Frankfurt mid HOSPITALITY',v_hosp),
    ('25hours Frankfurt Reservations','25hours Hotel Frankfurt The Trip','DE','https://25hours-hotels.com/hotels/frankfurt-the-trip/',NULL,'res.frankfurt@25hours-hotels.com','+4969256820',NULL,'Niddastraße','Frankfurt','Hesse','DE',50.108,8.663,'Niddastraße 58, 60329 Frankfurt am Main','BOOKER_DEMAND EU Frankfurt mid HOSPITALITY',v_hosp),
    ('Villa Orange Frankfurt Desk','Villa Orange','DE','https://www.villa-orange.de/',NULL,'info@villa-orange.de','+4969715450',NULL,'Nibelungenallee','Frankfurt','Hesse','DE',50.13,8.692,'Nibelungenallee 3, 60318 Frankfurt am Main','BOOKER_DEMAND EU Frankfurt mid HOSPITALITY',v_hosp),
    ('Roomers Frankfurt Desk','Roomers Frankfurt','DE','https://www.roomers-hotels.com/frankfurt/',NULL,'frankfurt@roomers-hotels.com','+49692713080',NULL,'Gutleutstraße','Frankfurt','Hesse','DE',50.103,8.662,'Gutleutstraße 85, 60329 Frankfurt am Main','BOOKER_DEMAND EU Frankfurt mid HOSPITALITY',v_hosp),
    ('25hours Vienna Desk','25hours Hotel at MuseumsQuartier','AT','https://25hours-hotels.com/hotels/vienna/',NULL,'res.wien@25hours-hotels.com','+431521510',NULL,'MuseumsQuartier','Vienna','Vienna','AT',48.205,16.357,'Lerchenfelder Straße 1-3, 1070 Wien','BOOKER_DEMAND EU Vienna mid HOSPITALITY',v_hosp),
    ('25hours Vienna Concierge','25hours Hotel at MuseumsQuartier','AT','https://25hours-hotels.com/hotels/vienna/',NULL,'wien@25hours-hotels.com','+431521510',NULL,'MuseumsQuartier','Vienna','Vienna','AT',48.205,16.357,'Lerchenfelder Straße 1-3, 1070 Wien','BOOKER_DEMAND EU Vienna mid CONCIERGE',v_conc),
    ('LOVIS Vienna Desk','LOVIS Hotel Vienna','AT','https://www.lovis-vienna.com/',NULL,'reservations@lovis-vienna.com','+436605520688',NULL,'Mariahilfer Straße','Vienna','Vienna','AT',48.198,16.355,'Mariahilfer Straße 32, 1070 Wien','BOOKER_DEMAND EU Vienna mid HOSPITALITY',v_hosp),
    ('Hotel Altstadt Vienna Desk','Hotel Altstadt Vienna','AT','https://www.altstadt.at/',NULL,'hotel@altstadt.at','+4315226666',NULL,'Kirchengasse','Vienna','Vienna','AT',48.201,16.353,'Kirchengasse 41, 1070 Wien','BOOKER_DEMAND EU Vienna mid HOSPITALITY',v_hosp),
    ('Hotel Sans Souci Wien Desk','Hotel Sans Souci Wien','AT','https://www.sanssouci-wien.com/',NULL,'reservation@sanssouci-wien.com','+4315222500',NULL,'Burggasse','Vienna','Vienna','AT',48.204,16.353,'Burggasse 2, 1070 Wien','BOOKER_DEMAND EU Vienna mid HOSPITALITY',v_hosp),
    ('Hotel Topazz Desk','Hotel Topazz','AT','https://www.hoteltopazz.com/',NULL,'office@hoteltopazz.com','+4311536400',NULL,'Spiegelgasse','Vienna','Vienna','AT',48.208,16.372,'Spiegelgasse 8, 1010 Wien','BOOKER_DEMAND EU Vienna mid HOSPITALITY',v_hosp),
    ('Ruby Marie Vienna Desk','Ruby Marie Hotel Vienna','AT','https://www.ruby-hotels.com/en/destinations/vienna/marie',NULL,'marie@ruby-hotels.com','+4313619600',NULL,'Kaiserstraße','Vienna','Vienna','AT',48.198,16.34,'Kaiserstraße 2-4, 1070 Wien','BOOKER_DEMAND EU Vienna mid HOSPITALITY',v_hosp),
    ('25hours Zurich West Desk','25hours Hotel Zurich West','CH','https://all.accor.com/hotel/B145/index.en.shtml',NULL,'res.zuerichwest@25hours-hotels.com','+41445772525',NULL,'Pfingstweidstrasse','Zurich','Zurich','CH',47.391,8.51,'Pfingstweidstrasse 102, 8005 Zürich','BOOKER_DEMAND EU Zurich mid HOSPITALITY',v_hosp),
    ('25hours Zurich West Concierge','25hours Hotel Zurich West','CH','https://25hours-hotels.com/hotels/zurich-west/',NULL,'zuerichwest@25hours-hotels.com','+41445772525',NULL,'Pfingstweidstrasse','Zurich','Zurich','CH',47.391,8.51,'Pfingstweidstrasse 102, 8005 Zürich','BOOKER_DEMAND EU Zurich mid CONCIERGE',v_conc),
    ('25hours Zurich Langstrasse Desk','25hours Hotel Langstrasse','CH','https://25hours-hotels.com/hotels/zurich-langstrasse/',NULL,'res.langstrasse@25hours-hotels.com','+41445765000',NULL,'Langstrasse','Zurich','Zurich','CH',47.38,8.528,'Langstrasse 150, 8004 Zürich','BOOKER_DEMAND EU Zurich mid HOSPITALITY',v_hosp),
    ('Hotel Greulich Desk','Hotel Greulich','CH','https://www.greulich.ch/',NULL,'info@greulich.ch','+41442883535',NULL,'Militärstrasse','Zurich','Zurich','CH',47.378,8.526,'Militärstrasse 84, 8004 Zürich','BOOKER_DEMAND EU Zurich mid HOSPITALITY',v_hosp),
    ('Marktgasse Hotel Desk','Marktgasse Hotel','CH','https://www.marktgassehotel.ch/',NULL,'info@marktgassehotel.ch','+41442663535',NULL,'Marktgasse','Zurich','Zurich','CH',47.373,8.544,'Marktgasse 17, 8001 Zürich','BOOKER_DEMAND EU Zurich mid HOSPITALITY',v_hosp),
    ('Novotel Geneva Centre Desk','Novotel Genève Centre','CH','https://all.accor.com/hotel/3133/index.en.shtml',NULL,'h3133@accor.com','+41229099000',NULL,'Rue de Zurich','Geneva','Geneva','CH',46.21,6.146,'Rue de Zurich 3-5, 1201 Genève','BOOKER_DEMAND EU Geneva mid HOSPITALITY',v_hosp),
    ('9Hotel Paquis Geneva Desk','9Hotel Pâquis','CH','https://www.9-hotel-geneve-paquis.ch/',NULL,'info@9hotelpaquis.com','+41225529095',NULL,'Rue de Berne','Geneva','Geneva','CH',46.211,6.146,'31 Rue de Berne, 1201 Genève','BOOKER_DEMAND EU Geneva mid HOSPITALITY',v_hosp),
    ('Hotel Longemalle Desk','Hôtel Longemalle','CH','https://www.hotel-longemalle.ch/',NULL,'info@hotel-longemalle.ch','+41228186000',NULL,'Place Longemalle','Geneva','Geneva','CH',46.203,6.152,'Place Longemalle 5, 1204 Genève','BOOKER_DEMAND EU Geneva mid HOSPITALITY',v_hosp),
    ('Hotel Tiffany Geneva Desk','Hotel Tiffany','CH','https://www.hotel-tiffany.ch/',NULL,'info@hotel-tiffany.ch','+41227383300',NULL,'Rue de l''Arquebuse','Geneva','Geneva','CH',46.201,6.141,'1 Rue de l''Arquebuse, 1204 Genève','BOOKER_DEMAND EU Geneva mid HOSPITALITY',v_hosp),
    ('9Hotel Mercy Lisbon Desk','9Hotel Mercy','PT','https://www.9-hotel-mercy-lisbon.pt/',NULL,'info@le9hotel-mercy.com','+351212481480',NULL,'Chiado','Lisbon','Lisbon','PT',38.712,-9.144,'Rua da Misericórdia 76, 1200-273 Lisboa','BOOKER_DEMAND EU Lisbon mid HOSPITALITY',v_hosp),
    ('AlmaLusa Baixa Chiado Desk','AlmaLusa Baixa/Chiado','PT','https://www.almalusahotels.com/baixachiado/',NULL,'reservas.bc@almalusahotels.com','+351212697440',NULL,'Praça do Município','Lisbon','Lisbon','PT',38.708,-9.139,'Praça do Município 21, 1100-365 Lisboa','BOOKER_DEMAND EU Lisbon mid HOSPITALITY',v_hosp),
    ('Memmo Alfama Desk','Memmo Alfama','PT','https://www.memmohotels.com/alfama/',NULL,'reservations.alfama@memmohotels.com','+351212425880',NULL,'Alfama','Lisbon','Lisbon','PT',38.711,-9.129,'Travessa das Merceeiras 27, 1100-348 Lisboa','BOOKER_DEMAND EU Lisbon mid HOSPITALITY',v_hosp),
    ('Memmo Principe Real Desk','Memmo Príncipe Real','PT','https://www.memmohotels.com/principe-real/',NULL,'reservations.principedereal@memmohotels.com','+351213514360',NULL,'Príncipe Real','Lisbon','Lisbon','PT',38.717,-9.149,'Rua Dom Pedro V 56, 1250-094 Lisboa','BOOKER_DEMAND EU Lisbon mid HOSPITALITY',v_hosp),
    ('Corpo Santo Lisbon Desk','Corpo Santo Lisbon Historical Hotel','PT','https://www.corposantohotel.com/',NULL,'reservations@corposantohotel.com','+351210403000',NULL,'Cais do Sodré','Lisbon','Lisbon','PT',38.707,-9.144,'Rua do Corpo Santo 4, 1200-129 Lisboa','BOOKER_DEMAND EU Lisbon mid HOSPITALITY',v_hosp),
    ('The Lumiares Desk','The Lumiares Hotel & Spa','PT','https://www.thelumiares.com/',NULL,'reservations@thelumiares.com','+351211160000',NULL,'Bairro Alto','Lisbon','Lisbon','PT',38.714,-9.145,'Rua do Diário de Notícias 142, 1200-146 Lisboa','BOOKER_DEMAND EU Lisbon mid HOSPITALITY',v_hosp),
    ('Hotel Josef Prague Desk','Hotel Josef','CZ','https://www.hoteljosef.com/',NULL,'reservation@hoteljosef.com','+420221700901',NULL,'Rybná','Prague','Prague','CZ',50.089,14.427,'Rybná 20, 110 00 Praha 1','BOOKER_DEMAND EU Prague mid HOSPITALITY',v_hosp),
    ('Hotel Josef Concierge','Hotel Josef','CZ','https://www.hoteljosef.com/',NULL,'concierge@hoteljosef.com','+420221700951',NULL,'Rybná','Prague','Prague','CZ',50.089,14.427,'Rybná 20, 110 00 Praha 1','BOOKER_DEMAND EU Prague mid CONCIERGE',v_conc),
    ('Maximilian Hotel Prague Desk','Maximilian Hotel','CZ','https://www.maximilianhotel.com/',NULL,'reservation@maximilianhotel.com','+420225303111',NULL,'Haštalská','Prague','Prague','CZ',50.091,14.424,'Haštalská 14, 110 00 Praha 1','BOOKER_DEMAND EU Prague mid HOSPITALITY',v_hosp),
    ('Maximilian Hotel Reception','Maximilian Hotel','CZ','https://www.maximilianhotel.com/',NULL,'reception@maximilianhotel.com','+420225303111',NULL,'Haštalská','Prague','Prague','CZ',50.091,14.424,'Haštalská 14, 110 00 Praha 1','BOOKER_DEMAND EU Prague mid HOSPITALITY',v_hosp),
    ('Aria Hotel Prague Desk','Aria Hotel Prague','CZ','https://www.ariahotel.net/',NULL,'reservation@ariahotel.net','+420225334111',NULL,'Tržiště','Prague','Prague','CZ',50.087,14.404,'Tržiště 9, 118 00 Praha 1','BOOKER_DEMAND EU Prague mid HOSPITALITY',v_hosp),
    ('Hotel Paris Prague Desk','Hotel Paris Prague','CZ','https://www.hotel-paris.cz/',NULL,'booking@hotel-paris.cz','+420222195195',NULL,'U Obecního domu','Prague','Prague','CZ',50.088,14.428,'U Obecního domu 1, 110 00 Praha 1','BOOKER_DEMAND EU Prague mid HOSPITALITY',v_hosp)
  ) AS t(
    display_name, legal_name, country, website_url, website_domain, email, phone, whatsapp,
    base_label, city, region, country_code, lat, lng, formatted_address, note, service_type_id
  )
  LOOP
    IF EXISTS (
      SELECT 1 FROM organizations o WHERE o.archived_at IS NULL AND (
        (lower(o.display_name) = lower(r.display_name) AND o.legal_country_code = r.country)
        OR (r.email IS NOT NULL AND lower(coalesce(o.primary_email, '')) = lower(r.email)
            AND o.notes_public LIKE 'BOOKER_DEMAND%')
      )
    ) THEN
      skipped := skipped + 1;
      CONTINUE;
    END IF;

    INSERT INTO organizations (
      display_name, legal_name, legal_country_code, legal_city, legal_region,
      website_url, website_domain, primary_email, primary_phone_e164, primary_whatsapp_e164,
      notes_public, is_test, created_by_user_id
    ) VALUES (
      r.display_name, r.legal_name, r.country, r.city, r.region,
      r.website_url, r.website_domain, r.email, r.phone, COALESCE(r.whatsapp, r.phone),
      r.note, false, v_admin
    ) RETURNING id INTO v_org;

    INSERT INTO organization_capabilities (organization_id, capability)
    VALUES (v_org, 'BUYER') ON CONFLICT DO NOTHING;
    INSERT INTO partnerships (organization_id, relationship_status, status_changed_at)
    VALUES (v_org, 'LEAD', now());
    INSERT INTO offerings (organization_id, service_type_id, operational_status)
    VALUES (v_org, r.service_type_id, 'UNKNOWN');
    INSERT INTO organization_locations (
      organization_id, label, location_kind, city, region, country_code, lat, lng, formatted_address, is_primary
    ) VALUES (v_org, r.base_label, 'OPS_BASE', r.city, r.region, r.country_code, r.lat, r.lng, r.formatted_address, true);
    INSERT INTO organization_contacts (
      organization_id, full_name, contact_type, title, email, phone_e164, is_primary
    ) VALUES (
      v_org, 'Guest / Concierge desk', 'Other', 'Bookings desk', r.email, r.phone, true
    );
    inserted := inserted + 1;
  END LOOP;
  RAISE NOTICE 'UK+EU mid bookers: inserted=% skipped=%', inserted, skipped;
END $$;
