-- VL Bookers R2: London HOSPITALITY hotels only (mid-upper / boutique)
-- UK bookers = London only; leave existing CONCIERGE as-is

DO $$
DECLARE
  v_hosp uuid := '8724134a-2249-4d87-83aa-167db279aab8';
  v_admin uuid := 'b3105232-0857-4eed-b022-d8147683c059';
  r record;
  v_org uuid;
  inserted int := 0;
  skipped int := 0;
BEGIN
  FOR r IN SELECT * FROM (VALUES
    -- Kensington / South Kensington / Earl's Court
    ('Milestone Hotel Kensington Desk','The Milestone Hotel','GB','https://www.milestonehotel.com/',NULL,'reservations@milestonehotel.com','+442079173000',NULL,'Kensington Court','London','England','GB',51.501,-0.188,'1 Kensington Court, London W8 5DL','BOOKER_DEMAND UK London hotel HOSPITALITY Kensington',v_hosp),
    ('Baglioni Kensington Desk','Baglioni Hotel London','GB','https://www.baglionihotels.com/london',NULL,'reservations.london@baglionihotels.com','+442073688888',NULL,'Hyde Park Gate','London','England','GB',51.501,-0.183,'60 Hyde Park Gate, London SW7 5BB','BOOKER_DEMAND UK London hotel HOSPITALITY Kensington',v_hosp),
    ('Copthorne Tara Kensington Desk','Copthorne Tara Hotel London Kensington','GB','https://www.millenniumhotels.com/en/london/copthorne-tara-hotel-london-kensington/',NULL,'reservations.tara@millenniumhotels.co.uk','+442079377211',NULL,'Scarsdale Place','London','England','GB',51.499,-0.195,'Scarsdale Place, London W8 5SY','BOOKER_DEMAND UK London hotel HOSPITALITY Kensington',v_hosp),
    ('Kensington Hotel London Desk','The Kensington Hotel','GB','https://www.doylecollection.com/hotels/the-kensington-hotel',NULL,'kensington@doylecollection.com','+442075893000',NULL,'Queen''s Gate','London','England','GB',51.497,-0.181,'109-113 Queen''s Gate, London SW7 5LR','BOOKER_DEMAND UK London hotel HOSPITALITY South Kensington',v_hosp),
    ('Levin Hotel Knightsbridge Desk','The Levin Hotel','GB','https://www.thelevinhotel.co.uk/',NULL,'reservations@thelevinhotel.co.uk','+442075898333',NULL,'Knightsbridge','London','England','GB',51.501,-0.162,'28 Basil Street, London SW3 1AS','BOOKER_DEMAND UK London hotel HOSPITALITY Knightsbridge',v_hosp),
    ('Egerton House Knightsbridge Desk','Egerton House Hotel','GB','https://www.egertonhousehotel.com/',NULL,'reservations@egertonhousehotel.com','+442075893888',NULL,'Egerton Terrace','London','England','GB',51.496,-0.168,'17-19 Egerton Terrace, London SW3 2BU','BOOKER_DEMAND UK London hotel HOSPITALITY Knightsbridge',v_hosp),
    ('Rembrandt Hotel Kensington Desk','The Rembrandt','GB','https://www.sarova-rembrandthotel.com/',NULL,'reservations@sarova-rembrandthotel.com','+442075898100',NULL,'Thurloe Place','London','England','GB',51.495,-0.172,'11 Thurloe Place, London SW7 2RS','BOOKER_DEMAND UK London hotel HOSPITALITY South Kensington',v_hosp),
    ('Ampersand Hotel South Kensington Desk','The Ampersand Hotel','GB','https://www.ampersandhotel.com/',NULL,'reservations@ampersandhotel.com','+442075895895',NULL,'Harrington Road','London','England','GB',51.494,-0.176,'10 Harrington Road, London SW7 3ER','BOOKER_DEMAND UK London hotel HOSPITALITY South Kensington',v_hosp),
    ('Gallery Hotel Kensington Desk','The Gallery Hotel','GB','https://www.ehg.com/hotels/europe/united-kingdom/london/the-gallery',NULL,'reservations@thegalleryhotellondon.com','+442075894505',NULL,'Queen''s Gate Terrace','London','England','GB',51.497,-0.185,'8-10 Queen''s Gate Terrace, London SW7 5PH','BOOKER_DEMAND UK London hotel HOSPITALITY Kensington',v_hosp),
    ('Park International Kensington Desk','Park International Hotel','GB','https://www.parkinternationalhotel.com/',NULL,'reservations@parkinternationalhotel.com','+442073707474',NULL,'Cromwell Road','London','England','GB',51.494,-0.189,'117-125 Cromwell Road, London SW7 4DU','BOOKER_DEMAND UK London hotel HOSPITALITY Kensington',v_hosp),

    -- Chelsea / Belgravia
    ('myhotel Chelsea Desk','myhotel Chelsea','GB','https://www.myhotels.com/chelsea',NULL,'chelsea@myhotels.com','+442072225500',NULL,'Sloane Gardens','London','England','GB',51.492,-0.156,'35 Ixworth Place, London SW3 3QX','BOOKER_DEMAND UK London hotel HOSPITALITY Chelsea',v_hosp),
    ('San Domenico House Chelsea Desk','San Domenico House','GB','https://www.sandomenicohouse.com/',NULL,'reservations@sandomenicohouse.com','+442075811888',NULL,'Draycott Place','London','England','GB',51.492,-0.159,'29-31 Draycott Place, London SW3 2SH','BOOKER_DEMAND UK London hotel HOSPITALITY Chelsea',v_hosp),
    ('Sydney House Chelsea Desk','Sydney House Chelsea','GB','https://www.sydneyhousechelsea.co.uk/',NULL,'reservations@sydneyhousechelsea.co.uk','+442075899333',NULL,'Sydney Street','London','England','GB',51.488,-0.171,'9-11 Sydney Street, London SW3 6PU','BOOKER_DEMAND UK London hotel HOSPITALITY Chelsea',v_hosp),
    ('Sloane Square Hotel Desk','Sloane Square Hotel','GB','https://www.sloanesquarehotel.co.uk/',NULL,'reservations@sloanesquarehotel.co.uk','+442089688811',NULL,'Sloane Square','London','England','GB',51.492,-0.157,'7-12 Sloane Square, London SW1W 8EG','BOOKER_DEMAND UK London hotel HOSPITALITY Chelsea',v_hosp),
    ('Goring Belgravia Desk','The Goring','GB','https://www.thegoring.com/',NULL,'reservations@thegoring.com','+442073969000',NULL,'Beeston Place','London','England','GB',51.498,-0.145,'15 Beeston Place, London SW1W 0JW','BOOKER_DEMAND UK London hotel HOSPITALITY Belgravia',v_hosp),
    ('Berkeley Knightsbridge Desk','The Berkeley','GB','https://www.the-berkeley.co.uk/',NULL,'reservations@the-berkeley.co.uk','+442072354000',NULL,'Wilton Place','London','England','GB',51.502,-0.155,'Wilton Place, London SW1X 7RL','BOOKER_DEMAND UK London hotel HOSPITALITY Knightsbridge',v_hosp),

    -- Marylebone / Fitzrovia
    ('Chiltern Firehouse Marylebone Desk','Chiltern Firehouse','GB','https://www.chilternfirehouse.com/',NULL,'reservations@chilternfirehouse.com','+442070730000',NULL,'Chiltern Street','London','England','GB',51.519,-0.155,'1 Chiltern Street, London W1U 7PA','BOOKER_DEMAND UK London hotel HOSPITALITY Marylebone',v_hosp),
    ('Montagu Place Marylebone Desk','Hotel Montagu Place','GB','https://www.montaguplace.co.uk/',NULL,'reservations@montaguplace.co.uk','+442074862211',NULL,'Montagu Place','London','England','GB',51.520,-0.157,'2 Montagu Place, London W1H 2ER','BOOKER_DEMAND UK London hotel HOSPITALITY Marylebone',v_hosp),
    ('Durrants Hotel Marylebone Desk','Durrants Hotel','GB','https://www.durrantshotel.co.uk/',NULL,'enquiries@durrantshotel.co.uk','+442079358131',NULL,'George Street','London','England','GB',51.517,-0.152,'26-32 George Street, London W1H 5BJ','BOOKER_DEMAND UK London hotel HOSPITALITY Marylebone',v_hosp),
    ('Hyde Park Townhouse Marylebone Desk','Hyde Park Townhouse','GB','https://www.hydeparktownhouse.com/',NULL,'reservations@hydeparktownhouse.com','+442074023300',NULL,'Sussex Place','London','England','GB',51.514,-0.170,'4 Sussex Place, London W2 2TP','BOOKER_DEMAND UK London hotel HOSPITALITY Marylebone',v_hosp),
    ('Mandeville Hotel Marylebone Desk','The Mandeville Hotel','GB','https://www.mandeville.co.uk/',NULL,'info@mandeville.co.uk','+442079351444',NULL,'Mandeville Place','London','England','GB',51.516,-0.150,'Mandeville Place, London W1U 2BE','BOOKER_DEMAND UK London hotel HOSPITALITY Marylebone',v_hosp),
    ('Flemings Mayfair Desk','Flemings Mayfair','GB','https://www.flemings-mayfair.co.uk/',NULL,'reservations@flemings.co.uk','+442074992000',NULL,'Half Moon Street','London','England','GB',51.507,-0.144,'13 Half Moon Street, London W1J 7BH','BOOKER_DEMAND UK London hotel HOSPITALITY Mayfair',v_hosp),
    ('Brown''s Hotel Mayfair Desk','Brown''s Hotel','GB','https://www.roccofortehotels.com/hotels-and-resorts/browns-hotel/',NULL,'reservations.browns@roccofortehotels.com','+442074936020',NULL,'Albemarle Street','London','England','GB',51.509,-0.142,'33 Albemarle Street, London W1S 4BP','BOOKER_DEMAND UK London hotel HOSPITALITY Mayfair',v_hosp),
    ('Chesterfield Mayfair Desk','The Chesterfield Mayfair','GB','https://www.chesterfieldmayfair.com/',NULL,'reservations@chesterfieldmayfair.com','+442074912622',NULL,'Charles Street','London','England','GB',51.508,-0.148,'35 Charles Street, London W1J 5EB','BOOKER_DEMAND UK London hotel HOSPITALITY Mayfair',v_hosp),

    -- Bloomsbury / Holborn
    ('St Giles Hotel Bloomsbury Desk','St Giles London','GB','https://www.stgiles.com/hotels/st-giles-london',NULL,'reservations@stgiles.com','+442073000600',NULL,'Bedford Avenue','London','England','GB',51.517,-0.130,'Bedford Avenue, London WC1B 3GH','BOOKER_DEMAND UK London hotel HOSPITALITY Bloomsbury',v_hosp),
    ('Hoxton Holborn Desk','The Hoxton Holborn','GB','https://thehoxton.com/london/holborn/',NULL,'holborn@thehoxton.com','+442076614000',NULL,'High Holborn','London','England','GB',51.517,-0.120,'199-206 High Holborn, London WC1V 7BD','BOOKER_DEMAND UK London hotel HOSPITALITY Bloomsbury',v_hosp),
    ('Montcalm Bloomsbury Desk','The Montcalm London Bloomsbury','GB','https://www.montcalm.co.uk/bloomsbury/',NULL,'reservations.bloomsbury@montcalm.co.uk','+442076366000',NULL,'Gower Street','London','England','GB',51.522,-0.132,'52-54 Gower Street, London WC1E 6EB','BOOKER_DEMAND UK London hotel HOSPITALITY Bloomsbury',v_hosp),
    ('Imperial Hotel Bloomsbury Desk','Imperial London Hotels','GB','https://www.imperialhotels.co.uk/',NULL,'reservations@imperialhotels.co.uk','+442072783233',NULL,'Russell Square','London','England','GB',51.522,-0.125,'61-66 Russell Square, London WC1B 5BB','BOOKER_DEMAND UK London hotel HOSPITALITY Bloomsbury',v_hosp),
    ('Thistle Bloomsbury Park Desk','Thistle Bloomsbury Park','GB','https://www.thistle.com/en/hotels/london/bloomsbury-park',NULL,'bloomsburypark@thistle.co.uk','+442074363233',NULL,'Bedford Way','London','England','GB',51.523,-0.128,'126 Southampton Row, London WC1B 5AD','BOOKER_DEMAND UK London hotel HOSPITALITY Bloomsbury',v_hosp),
    ('Club Quarters Bloomsbury Desk','Club Quarters Hotel Bloomsbury','GB','https://clubquartershotels.com/locations/london-bloomsbury',NULL,'bloomsbury@clubquarters.com','+442075809000',NULL,'Gower Street','London','England','GB',51.521,-0.132,'61-68 Great Russell Street, London WC1B 3BL','BOOKER_DEMAND UK London hotel HOSPITALITY Bloomsbury',v_hosp),
    ('Academy Hotel Bloomsbury Desk','The Academy','GB','https://www.theacademyhotel.co.uk/',NULL,'reservations@theacademyhotel.co.uk','+442076313015',NULL,'Gower Street','London','England','GB',51.522,-0.132,'21 Gower Street, London WC1E 6HG','BOOKER_DEMAND UK London hotel HOSPITALITY Bloomsbury',v_hosp),

    -- Soho / Covent Garden / Westminster
    ('Ham Yard Hotel Soho Desk','Ham Yard Hotel','GB','https://www.firmdalehotels.com/hotels/ham-yard-hotel/',NULL,'reservations@hamyardhotel.com','+442036433000',NULL,'Ham Yard','London','England','GB',51.511,-0.134,'1 Ham Yard, London W1D 7DT','BOOKER_DEMAND UK London hotel HOSPITALITY Soho',v_hosp),
    ('Soho Hotel Desk','The Soho Hotel','GB','https://www.firmdalehotels.com/hotels/the-soho-hotel/',NULL,'reservations@sohohotel.com','+442075598000',NULL,'Richmond Mews','London','England','GB',51.514,-0.135,'4 Richmond Mews, London W1D 3DH','BOOKER_DEMAND UK London hotel HOSPITALITY Soho',v_hosp),
    ('Dean Street Townhouse Desk','Dean Street Townhouse','GB','https://www.deanstreettownhouse.com/',NULL,'reservations@deanstreettownhouse.com','+442074343180',NULL,'Dean Street','London','England','GB',51.513,-0.132,'69-71 Dean Street, London W1D 3SE','BOOKER_DEMAND UK London hotel HOSPITALITY Soho',v_hosp),
    ('W London Leicester Square Desk','W London','GB','https://www.marriott.com/en-us/hotels/lonwh-w-london',NULL,'wlondon.reservations@whotels.com','+442077547000',NULL,'Leicester Square','London','England','GB',51.511,-0.130,'10 Wardour Street, London W1D 6QF','BOOKER_DEMAND UK London hotel HOSPITALITY Soho',v_hosp),
    ('ME London Aldwych Desk','ME London','GB','https://www.melia.com/en/hotels/united-kingdom/london/me-london',NULL,'melondon@melia.com','+442073955400',NULL,'Aldwych','London','England','GB',51.512,-0.118,'336-337 Strand, London WC2R 1HA','BOOKER_DEMAND UK London hotel HOSPITALITY Covent Garden',v_hosp),
    ('One Aldwych Desk','One Aldwych','GB','https://www.onealdwych.com/',NULL,'reservations@onealdwych.com','+442073000100',NULL,'Aldwych','London','England','GB',51.512,-0.117,'1 Aldwych, London WC2B 4BZ','BOOKER_DEMAND UK London hotel HOSPITALITY Covent Garden',v_hosp),
    ('St Martins Lane Hotel Desk','St Martins Lane','GB','https://www.morganshotelgroup.com/st-martins-lane',NULL,'reservations@stmartinslane.com','+442073000550',NULL,'St Martin''s Lane','London','England','GB',51.511,-0.127,'45 St Martin''s Lane, London WC2N 4HX','BOOKER_DEMAND UK London hotel HOSPITALITY Covent Garden',v_hosp),
    ('Indigo London Covent Garden Desk','Hotel Indigo London Covent Garden','GB','https://www.ihg.com/hotelindigo/hotels/gb/en/london/lonwc/hoteldetail',NULL,'reservations@indigocoventgarden.com','+442073798888',NULL,'Drury Lane','London','England','GB',51.514,-0.123,'51-54 Drury Lane, London WC2B 5LA','BOOKER_DEMAND UK London hotel HOSPITALITY Covent Garden',v_hosp),
    ('Middle Eight Covent Garden Desk','Middle Eight','GB','https://www.middleeight.com/',NULL,'reservations@middleeight.com','+442072400000',NULL,'Endell Street','London','England','GB',51.515,-0.125,'78-86 Endell Street, London WC2H 9DJ','BOOKER_DEMAND UK London hotel HOSPITALITY Covent Garden',v_hosp),
    ('Waldorf Hilton Aldwych Desk','The Waldorf Hilton','GB','https://www.hilton.com/en/hotels/lonwahw-the-waldorf-hilton-london/',NULL,'reservations.waldorf@hilton.com','+442078363400',NULL,'Aldwych','London','England','GB',51.513,-0.118,'Aldwych, London WC2B 4DD','BOOKER_DEMAND UK London hotel HOSPITALITY Covent Garden',v_hosp),
    ('Conrad London St James Desk','Conrad London St James','GB','https://www.hilton.com/en/hotels/lonjcci-conrad-london-st-james/',NULL,'londonstjames.info@conradhotels.com','+442083005000',NULL,'Broadway','London','England','GB',51.498,-0.133,'22-28 Broadway, London SW1H 0BH','BOOKER_DEMAND UK London hotel HOSPITALITY Westminster',v_hosp),
    ('St Ermin''s Hotel Westminster Desk','St Ermin''s Hotel','GB','https://www.sterminshotel.co.uk/',NULL,'reservations@sterminshotel.co.uk','+442072226111',NULL,'Caxton Street','London','England','GB',51.499,-0.134,'2 Caxton Street, London SW1H 0QW','BOOKER_DEMAND UK London hotel HOSPITALITY Westminster',v_hosp),
    ('Park Plaza Westminster Bridge Desk','Park Plaza Westminster Bridge','GB','https://www.parkplazawestminsterbridge.com/',NULL,'reservations@ppwb.co.uk','+442077663000',NULL,'Westminster Bridge Road','London','England','GB',51.501,-0.117,'200 Westminster Bridge Road, London SE1 7UT','BOOKER_DEMAND UK London hotel HOSPITALITY Westminster',v_hosp),
    ('Corinthia London Desk','Corinthia London','GB','https://www.corinthia.com/london/',NULL,'reservations.london@corinthia.com','+442079302000',NULL,'Whitehall Place','London','England','GB',51.506,-0.124,'Whitehall Place, London SW1A 2BD','BOOKER_DEMAND UK London hotel HOSPITALITY Westminster',v_hosp),
    ('Rubens at the Palace Desk','The Rubens at the Palace','GB','https://www.rubenshotel.com/',NULL,'reservations@rubenshotel.com','+442078346600',NULL,'Buckingham Palace Road','London','England','GB',51.498,-0.145,'39 Buckingham Palace Road, London SW1W 0PS','BOOKER_DEMAND UK London hotel HOSPITALITY Westminster',v_hosp),
    ('Royal Horseguards Hotel Desk','The Royal Horseguards','GB','https://www.guoman.com/the-royal-horseguards',NULL,'reservations@guoman.co.uk','+442078393400',NULL,'Whitehall Court','London','England','GB',51.506,-0.124,'2 Whitehall Court, London SW1A 2EJ','BOOKER_DEMAND UK London hotel HOSPITALITY Westminster',v_hosp),

    -- City / Shoreditch / Clerkenwell
    ('Andaz London Liverpool Street Desk','Andaz London Liverpool Street','GB','https://www.hyatt.com/andaz/lonaz-andaz-london-liverpool-street',NULL,'london.liverpoolstreet@andaz.com','+442079610000',NULL,'Liverpool Street','London','England','GB',51.517,-0.081,'40 Liverpool Street, London EC2M 7QN','BOOKER_DEMAND UK London hotel HOSPITALITY City',v_hosp),
    ('Threadneedles City Desk','Threadneedles','GB','https://www.hotelthreadneedles.co.uk/',NULL,'reservations@hotelthreadneedles.co.uk','+442076583000',NULL,'Threadneedle Street','London','England','GB',51.514,-0.087,'5 Threadneedle Street, London EC2R 8AY','BOOKER_DEMAND UK London hotel HOSPITALITY City',v_hosp),
    ('Apex City of London Desk','Apex City of London Hotel','GB','https://www.apexhotels.co.uk/london/apex-city-of-london-hotel/',NULL,'cityoflondon@apexhotels.co.uk','+442076941000',NULL,'Seething Lane','London','England','GB',51.511,-0.079,'1 Seething Lane, London EC3N 4AX','BOOKER_DEMAND UK London hotel HOSPITALITY City',v_hosp),
    ('Apex London Wall Desk','Apex London Wall Hotel','GB','https://www.apexhotels.co.uk/london/apex-london-wall-hotel/',NULL,'londonwall@apexhotels.co.uk','+442075623700',NULL,'London Wall','London','England','GB',51.517,-0.090,'7-9 Copthall Avenue, London EC2R 7NJ','BOOKER_DEMAND UK London hotel HOSPITALITY City',v_hosp),
    ('Vintry & Mercer City Desk','Vintry & Mercer','GB','https://www.vintryandmercer.com/',NULL,'reservations@vintryandmercer.com','+442039087700',NULL,'Garlick Hill','London','England','GB',51.511,-0.093,'19-20 Garlick Hill, London EC4V 2AU','BOOKER_DEMAND UK London hotel HOSPITALITY City',v_hosp),
    ('Cheval Three Quays Desk','Cheval Three Quays','GB','https://www.chevalcollection.com/cheval-three-quays/',NULL,'threequays@chevalresidences.com','+442074813239',NULL,'Lower Thames Street','London','England','GB',51.509,-0.080,'40 Lower Thames Street, London EC3R 6AG','BOOKER_DEMAND UK London hotel HOSPITALITY City',v_hosp),
    ('Nobu Hotel Shoreditch Desk','Nobu Hotel Shoreditch','GB','https://www.nobuhotelshoreditch.com/',NULL,'reservations@nobuhotelshoreditch.com','+442076835000',NULL,'Worship Street','London','England','GB',51.524,-0.083,'10-50 Worship Street, London EC2A 2BH','BOOKER_DEMAND UK London hotel HOSPITALITY Shoreditch',v_hosp),
    ('Ace Hotel Shoreditch Desk','Ace Hotel London Shoreditch','GB','https://www.acehotel.com/london/',NULL,'londreservations@acehotel.com','+442076134200',NULL,'Shoreditch High Street','London','England','GB',51.526,-0.078,'100 Shoreditch High Street, London E1 6JQ','BOOKER_DEMAND UK London hotel HOSPITALITY Shoreditch',v_hosp),
    ('Qbic London City Desk','Qbic Hotel London City','GB','https://qbichotels.com/london-city/',NULL,'londoncity@qbichotels.com','+442030261600',NULL,'Whitechapel Road','London','England','GB',51.518,-0.061,'42 Adler Street, London E1 1EE','BOOKER_DEMAND UK London hotel HOSPITALITY Shoreditch',v_hosp),
    ('CitizenM Tower of London Desk','citizenM Tower of London','GB','https://www.citizenm.com/hotels/europe/london/tower-of-london-hotel',NULL,'toweroflondon@citizenm.com','+442035194000',NULL,'Tower Hill','London','England','GB',51.510,-0.076,'40 Trinity Square, London EC3N 4DJ','BOOKER_DEMAND UK London hotel HOSPITALITY City',v_hosp),
    ('Zetter Clerkenwell Desk','The Zetter Clerkenwell','GB','https://www.thezetter.com/clerkenwell',NULL,'reservations@thezetter.com','+442073246444',NULL,'St John''s Square','London','England','GB',51.523,-0.103,'86-88 Clerkenwell Road, London EC1M 5RJ','BOOKER_DEMAND UK London hotel HOSPITALITY Clerkenwell',v_hosp),
    ('Zetter Townhouse Clerkenwell Desk','The Zetter Townhouse Clerkenwell','GB','https://www.thezetter.com/clerkenwell-townhouse',NULL,'townhouse@thezetter.com','+442073246266',NULL,'St John''s Square','London','England','GB',51.523,-0.103,'49-50 St John''s Square, London EC1V 4JJ','BOOKER_DEMAND UK London hotel HOSPITALITY Clerkenwell',v_hosp),
    ('Rookery Hotel Smithfield Desk','The Rookery','GB','https://www.rookeryhotel.com/',NULL,'reservations@rookeryhotel.com','+442073390000',NULL,'Peter''s Lane','London','England','GB',51.520,-0.102,'12 Peter''s Lane, London EC1M 6DS','BOOKER_DEMAND UK London hotel HOSPITALITY Clerkenwell',v_hosp),

    -- South Bank / Waterloo / London Bridge
    ('Shangri-La The Shard Desk','Shangri-La The Shard','GB','https://www.shangri-la.com/london/shangrila/',NULL,'sltl@shangri-la.com','+442072345800',NULL,'London Bridge Street','London','England','GB',51.504,-0.086,'31 St Thomas Street, London SE1 9QU','BOOKER_DEMAND UK London hotel HOSPITALITY South Bank',v_hosp),
    ('London Bridge Hotel Desk','London Bridge Hotel','GB','https://www.londonbridgehotel.com/',NULL,'reservations@londonbridgehotel.com','+442078551200',NULL,'London Bridge','London','England','GB',51.505,-0.087,'8-18 London Bridge Street, London SE1 9SG','BOOKER_DEMAND UK London hotel HOSPITALITY South Bank',v_hosp),
    ('Bermondsey Square Hotel Desk','Bermondsey Square Hotel','GB','https://www.bermondseysquarehotel.co.uk/',NULL,'reservations@bermondseysquarehotel.co.uk','+442073785000',NULL,'Bermondsey Square','London','England','GB',51.498,-0.081,'Bermondsey Square, London SE1 3UN','BOOKER_DEMAND UK London hotel HOSPITALITY South Bank',v_hosp),
    ('Hotel Indigo London Tower Hill Desk','Hotel Indigo London Tower Hill','GB','https://www.ihg.com/hotelindigo/hotels/gb/en/london/lonth/hoteldetail',NULL,'reservations@indigotowerhill.com','+442072640000',NULL,'Minories','London','England','GB',51.511,-0.075,'142 Minories, London EC3N 1NT','BOOKER_DEMAND UK London hotel HOSPITALITY South Bank',v_hosp),
    ('Native Bankside Desk','Native Bankside','GB','https://nativeplaces.com/property/bankside/',NULL,'bankside@nativeplaces.com','+442039988000',NULL,'Southwark','London','England','GB',51.506,-0.098,'52 Southwark Street, London SE1 1UN','BOOKER_DEMAND UK London hotel HOSPITALITY South Bank',v_hosp),
    ('Park Plaza London Riverbank Desk','Park Plaza London Riverbank','GB','https://www.parkplaza.com/london-hotel/gb-london/pp_riverbank',NULL,'reservations@pplr.co.uk','+442077663000',NULL,'Albert Embankment','London','England','GB',51.489,-0.122,'18 Albert Embankment, London SE1 7TJ','BOOKER_DEMAND UK London hotel HOSPITALITY South Bank',v_hosp),
    ('Novotel London Waterloo Desk','Novotel London Waterloo','GB','https://all.accor.com/hotel/5309/index.en.shtml',NULL,'h5309@accor.com','+442077911433',NULL,'Lambeth Road','London','England','GB',51.498,-0.113,'113 Lambeth Road, London SE1 7LS','BOOKER_DEMAND UK London hotel HOSPITALITY South Bank',v_hosp),

    -- Canary Wharf / Docklands
    ('Hilton London Canary Wharf Desk','Hilton London Canary Wharf','GB','https://www.hilton.com/en/hotels/loncwhi-hilton-london-canary-wharf/',NULL,'reservations.canarywharf@hilton.com','+442030102000',NULL,'Marsh Wall','London','England','GB',51.503,-0.019,'South Quay, Marsh Wall, London E14 9SH','BOOKER_DEMAND UK London hotel HOSPITALITY Canary Wharf',v_hosp),
    ('Marriott West India Quay Desk','London Marriott Hotel West India Quay','GB','https://www.marriott.com/en-us/hotels/lonwi-london-marriott-hotel-west-india-quay',NULL,'mhrs.lonwi.reservation@marriott.com','+442075110000',NULL,'West India Quay','London','England','GB',51.507,-0.022,'22 Hertsmere Road, London E14 4ED','BOOKER_DEMAND UK London hotel HOSPITALITY Canary Wharf',v_hosp),
    ('Crowne Plaza London Docklands Desk','Crowne Plaza London - Docklands','GB','https://www.ihg.com/crowneplaza/hotels/gb/en/london/loncp/hoteldetail',NULL,'reservations@cplondondocklands.com','+442070908000',NULL,'Royal Victoria Dock','London','England','GB',51.508,0.023,'Western Gateway, Royal Victoria Dock, London E16 1AL','BOOKER_DEMAND UK London hotel HOSPITALITY Canary Wharf',v_hosp),
    ('DoubleTree Tower of London Desk','DoubleTree by Hilton London Tower of London','GB','https://www.hilton.com/en/hotels/lontldi-doubletree-by-hilton-london-tower-of-london/',NULL,'reservations.toweroflondon@hilton.com','+442077090000',NULL,'Tower Gateway','London','England','GB',51.510,-0.073,'7 Pepys Street, London EC3N 4AF','BOOKER_DEMAND UK London hotel HOSPITALITY Docklands',v_hosp),
    ('Guoman Tower Hotel Desk','The Tower Hotel','GB','https://www.guoman.com/the-tower',NULL,'reservations@towerhotel.co.uk','+442074810000',NULL,'St Katharine''s Way','London','England','GB',51.507,-0.074,'St Katharine''s Way, London E1W 1LD','BOOKER_DEMAND UK London hotel HOSPITALITY Docklands',v_hosp),
    ('Leonardo Royal London Docklands Desk','Leonardo Royal Hotel London Docklands','GB','https://www.leonardo-hotels.com/london/leonardo-royal-hotel-london-docklands',NULL,'info.docklands@leonardo-hotels.com','+442075150000',NULL,'Docklands','London','England','GB',51.507,-0.018,'Marsh Wall, London E14 9SH','BOOKER_DEMAND UK London hotel HOSPITALITY Docklands',v_hosp),
    ('Good Hotel London Desk','Good Hotel London','GB','https://www.goodhotel.co.uk/',NULL,'london@goodhotel.co.uk','+442037001555',NULL,'Royal Victoria Dock','London','England','GB',51.506,0.030,'Royal Victoria Dock, London E16 1AG','BOOKER_DEMAND UK London hotel HOSPITALITY Docklands',v_hosp),

    -- Islington / King''s Cross / Camden
    ('CitizenM King''s Cross Desk','citizenM London King''s Cross','GB','https://www.citizenm.com/hotels/europe/london/kings-cross-hotel',NULL,'kingscross@citizenm.com','+442033246000',NULL,'King''s Cross','London','England','GB',51.530,-0.122,'6-12 Euston Road, London N1C 4HX','BOOKER_DEMAND UK London hotel HOSPITALITY Islington',v_hosp),
    ('St Pancras Renaissance Desk','St Pancras Renaissance Hotel','GB','https://www.marriott.com/en-us/hotels/lonpr-st-pancras-renaissance-hotel-london',NULL,'reservations.stpancras@renaissancehotels.com','+442078400000',NULL,'Euston Road','London','England','GB',51.530,-0.125,'Euston Road, London NW1 2AR','BOOKER_DEMAND UK London hotel HOSPITALITY King''s Cross',v_hosp),
    ('Great Northern Hotel Desk','Great Northern Hotel','GB','https://www.gnhlondon.com/',NULL,'reservations@gnhlondon.com','+442033876000',NULL,'King''s Cross','London','England','GB',51.531,-0.124,'King''s Cross St Pancras Station, London N1C 4TB','BOOKER_DEMAND UK London hotel HOSPITALITY King''s Cross',v_hosp),
    ('Pullman London St Pancras Desk','Pullman London St Pancras','GB','https://all.accor.com/hotel/7367/index.en.shtml',NULL,'h7367@accor.com','+442076668000',NULL,'Euston Road','London','England','GB',51.529,-0.129,'100-110 Euston Road, London NW1 2AJ','BOOKER_DEMAND UK London hotel HOSPITALITY King''s Cross',v_hosp),
    ('Hilton London Euston Desk','Hilton London Euston','GB','https://www.hilton.com/en/hotels/loneuhi-hilton-london-euston/',NULL,'reservations.euston@hilton.com','+442076311222',NULL,'Euston Road','London','England','GB',51.528,-0.132,'17-18 Upper Woburn Place, London WC1H 0HT','BOOKER_DEMAND UK London hotel HOSPITALITY Bloomsbury',v_hosp),
    ('Malmaison London Desk','Malmaison London','GB','https://www.malmaison.com/locations/london/',NULL,'london@malmaison.com','+442070123000',NULL,'Charterhouse Square','London','England','GB',51.521,-0.099,'18-21 Charterhouse Square, London EC1M 6AH','BOOKER_DEMAND UK London hotel HOSPITALITY Islington',v_hosp),
    ('Hilton London Angel Islington Desk','Hilton London Angel Islington','GB','https://www.hilton.com/en/hotels/lonaihi-hilton-london-angel-islington/',NULL,'reservations.angelislington@hilton.com','+442071902000',NULL,'Upper Street','London','England','GB',51.535,-0.104,'53 Upper Street, London N1 0UY','BOOKER_DEMAND UK London hotel HOSPITALITY Islington',v_hosp),
    ('Courtyard London Islington Desk','Courtyard by Marriott London City Islington','GB','https://www.marriott.com/en-us/hotels/loncy-courtyard-london-city-islington',NULL,'mhrs.loncy.reservation@marriott.com','+442071328000',NULL,'City Road','London','England','GB',51.531,-0.096,'4-12 City Road, London EC1Y 2AA','BOOKER_DEMAND UK London hotel HOSPITALITY Islington',v_hosp),

    -- Greenwich / Blackheath
    ('InterContinental London O2 Desk','InterContinental London - The O2','GB','https://www.ihg.com/intercontinental/hotels/gb/en/london/lonha/hoteldetail',NULL,'reservations@iclondon-theo2.com','+442070000000',NULL,'Peninsula Square','London','England','GB',51.503,0.004,'1 Waterview Drive, London SE10 0TW','BOOKER_DEMAND UK London hotel HOSPITALITY Greenwich',v_hosp),
    ('DoubleTree Greenwich Desk','DoubleTree by Hilton London Greenwich','GB','https://www.hilton.com/en/hotels/longwdi-doubletree-by-hilton-london-greenwich/',NULL,'reservations.greenwich@hilton.com','+442083160000',NULL,'Tunnel Avenue','London','England','GB',51.493,0.004,'165 Tunnel Avenue, London SE10 0PJ','BOOKER_DEMAND UK London hotel HOSPITALITY Greenwich',v_hosp),
    ('Novotel Greenwich Desk','Novotel London Greenwich','GB','https://all.accor.com/hotel/1152/index.en.shtml',NULL,'h1152@accor.com','+442083058000',NULL,'Greenwich High Road','London','England','GB',51.477,-0.010,'173-185 Greenwich High Road, London SE10 8JA','BOOKER_DEMAND UK London hotel HOSPITALITY Greenwich',v_hosp),
    ('Devonport House Greenwich Desk','Devonport House','GB','https://www.guoman.com/devonport-house',NULL,'reservations@devonporthouse.co.uk','+442078293000',NULL,'King William Walk','London','England','GB',51.478,-0.005,'King William Walk, London SE10 9JW','BOOKER_DEMAND UK London hotel HOSPITALITY Greenwich',v_hosp),

    -- Richmond / Kew / Twickenham
    ('Petersham Hotel Richmond Desk','The Petersham Hotel','GB','https://www.petershamhotel.co.uk/',NULL,'enquiries@petershamhotel.co.uk','+442089394171',NULL,'Nightingale Lane','London','England','GB',51.451,-0.301,'Nightingale Lane, Richmond TW10 6UZ','BOOKER_DEMAND UK London hotel HOSPITALITY Richmond',v_hosp),
    ('Richmond Hill Hotel Desk','Richmond Hill Hotel','GB','https://www.richmondhill-hotel.co.uk/',NULL,'reservations@richmondhill-hotel.co.uk','+442089402241',NULL,'Richmond Hill','London','England','GB',51.454,-0.300,'144-150 Richmond Hill, Richmond TW10 6RW','BOOKER_DEMAND UK London hotel HOSPITALITY Richmond',v_hosp),
    ('Bingham Riverhouse Richmond Desk','Bingham Riverhouse','GB','https://www.binghamriverhouse.com/',NULL,'info@binghamriverhouse.com','+442089408686',NULL,'Petersham Road','London','England','GB',51.452,-0.305,'61-63 Petersham Road, Richmond TW10 6UT','BOOKER_DEMAND UK London hotel HOSPITALITY Richmond',v_hosp),
    ('Lensbury Teddington Desk','The Lensbury','GB','https://www.lensbury.com/',NULL,'reservations@lensbury.com','+442086160000',NULL,'Broom Road','London','England','GB',51.424,-0.318,'Broom Road, Teddington TW11 9NU','BOOKER_DEMAND UK London hotel HOSPITALITY Richmond',v_hosp),
    ('Hilton London Syon Park Desk','Hilton London Syon Park','GB','https://www.hilton.com/en/hotels/lonsyhi-hilton-london-syon-park/',NULL,'reservations.syonpark@hilton.com','+442078760000',NULL,'Syon Park','London','England','GB',51.477,-0.312,'Syon Park, Brentford TW8 8JF','BOOKER_DEMAND UK London hotel HOSPITALITY Richmond',v_hosp),

    -- Hampstead / Primrose Hill / Swiss Cottage
    ('Hampstead Britannia Desk','Britannia Hampstead','GB','https://www.britanniahotels.com/hotels/london/hampstead',NULL,'hampstead@britanniahotels.com','+442077946000',NULL,'Primrose Hill Road','London','England','GB',51.543,-0.160,'Hampstead Road, London NW3 6LS','BOOKER_DEMAND UK London hotel HOSPITALITY Hampstead',v_hosp),
    ('La Gaffe Hampstead Desk','La Gaffe','GB','https://www.lagaffe.co.uk/',NULL,'info@lagaffe.co.uk','+442074357100',NULL,'Heath Street','London','England','GB',51.556,-0.178,'107-111 Heath Street, London NW3 6SS','BOOKER_DEMAND UK London hotel HOSPITALITY Hampstead',v_hosp),
    ('Swiss Cottage Hotel Desk','Swiss Cottage Hotel','GB','https://www.swisscottagehotel.co.uk/',NULL,'reservations@swisscottagehotel.co.uk','+442077225000',NULL,'Adamson Road','London','England','GB',51.543,-0.174,'4 Adamson Road, London NW3 3HP','BOOKER_DEMAND UK London hotel HOSPITALITY Hampstead',v_hosp),
    ('Sanderson Hotel Fitzrovia Desk','Sanderson London','GB','https://www.morganshotelgroup.com/sanderson',NULL,'reservations@sandersonlondon.com','+442073000140',NULL,'Berners Street','London','England','GB',51.517,-0.137,'50 Berners Street, London W1T 3NG','BOOKER_DEMAND UK London hotel HOSPITALITY Fitzrovia',v_hosp),
    ('Middlesex House Fitzrovia Desk','The Middlesex','GB','https://www.edwardian.com/hotels/london/middlesex',NULL,'reservations@middlesexhotel.com','+442074364040',NULL,'Great Russell Street','London','England','GB',51.517,-0.130,'20-21 Tottenham Court Road, London W1T 1BJ','BOOKER_DEMAND UK London hotel HOSPITALITY Fitzrovia',v_hosp),

    -- Extra mid-upper coverage (Paddington / Bayswater / Victoria / Pimlico)
    ('Grand Royale Hyde Park Desk','Grand Royale London Hyde Park','GB','https://www.grandroyalehydepark.com/',NULL,'reservations@grandroyalehydepark.com','+442074027999',NULL,'Inverness Terrace','London','England','GB',51.512,-0.187,'1-9 Inverness Terrace, London W2 3JP','BOOKER_DEMAND UK London hotel HOSPITALITY Bayswater',v_hosp),
    ('Thistle Kensington Gardens Desk','Thistle Kensington Gardens','GB','https://www.thistle.com/en/hotels/london/kensington-gardens',NULL,'kensingtongardens@thistle.co.uk','+442079372222',NULL,'Bayswater Road','London','England','GB',51.511,-0.183,'100 Bayswater Road, London W2 3HL','BOOKER_DEMAND UK London hotel HOSPITALITY Bayswater',v_hosp),
    ('Lancaster London Desk','Lancaster London','GB','https://www.lancasterlondon.com/',NULL,'reservations@lancasterlondon.com','+442074167000',NULL,'Lancaster Terrace','London','England','GB',51.513,-0.176,'Lancaster Terrace, London W2 2TY','BOOKER_DEMAND UK London hotel HOSPITALITY Paddington',v_hosp),
    ('Hilton London Metropole Desk','Hilton London Metropole','GB','https://www.hilton.com/en/hotels/lonmethi-hilton-london-metropole/',NULL,'reservations.metropole@hilton.com','+442074024000',NULL,'Edgware Road','London','England','GB',51.520,-0.170,'225 Edgware Road, London W2 1JU','BOOKER_DEMAND UK London hotel HOSPITALITY Paddington',v_hosp),
    ('Hilton London Paddington Desk','Hilton London Paddington','GB','https://www.hilton.com/en/hotels/lonpadi-hilton-london-paddington/',NULL,'reservations.paddington@hilton.com','+442078500500',NULL,'Praed Street','London','England','GB',51.516,-0.176,'146 Praed Street, London W2 1EE','BOOKER_DEMAND UK London hotel HOSPITALITY Paddington',v_hosp),
    ('Grosvenor Hotel Victoria Desk','The Grosvenor Hotel','GB','https://www.guoman.com/the-grosvenor',NULL,'reservations@grosvenor-london.co.uk','+442078346636',NULL,'Buckingham Palace Road','London','England','GB',51.495,-0.145,'101 Buckingham Palace Road, London SW1W 0SJ','BOOKER_DEMAND UK London hotel HOSPITALITY Westminster',v_hosp),
    ('Taj 51 Buckingham Gate Desk','Taj 51 Buckingham Gate','GB','https://www.tajhotels.com/en-in/taj/taj-51-buckingham-gate-suites-and-residences-london/',NULL,'reservations.london@tajhotels.com','+442077660000',NULL,'Buckingham Gate','London','England','GB',51.499,-0.138,'51 Buckingham Gate, London SW1E 6AF','BOOKER_DEMAND UK London hotel HOSPITALITY Westminster',v_hosp),
    ('Jumeirah Lowndes Hotel Desk','Jumeirah Lowndes Hotel','GB','https://www.jumeirah.com/en/stay/london/jumeirah-lowndes-hotel',NULL,'jlhinfo@jumeirah.com','+442078231234',NULL,'Lowndes Street','London','England','GB',51.499,-0.155,'21 Lowndes Street, London SW1X 9ES','BOOKER_DEMAND UK London hotel HOSPITALITY Belgravia',v_hosp),
    ('Hotel Cafe Royal Desk','Hotel Cafe Royal','GB','https://www.hotelcaferoyal.com/',NULL,'reservations@hotelcaferoyal.com','+442074067000',NULL,'Regent Street','London','England','GB',51.510,-0.136,'68 Regent Street, London W1B 4DY','BOOKER_DEMAND UK London hotel HOSPITALITY Soho',v_hosp),
    ('Edition London Desk','London Edition','GB','https://www.editionhotels.com/london/',NULL,'reservations.london@editionhotels.com','+442077884000',NULL,'Berners Street','London','England','GB',51.517,-0.137,'10 Berners Street, London W1T 3NP','BOOKER_DEMAND UK London hotel HOSPITALITY Fitzrovia',v_hosp),
    ('Cadogan Hotel Chelsea Desk','The Cadogan','GB','https://www.thecadogan.com/',NULL,'reservations@thecadogan.com','+442073073333',NULL,'Sloane Street','London','England','GB',51.494,-0.158,'75 Sloane Street, London SW1X 9SG','BOOKER_DEMAND UK London hotel HOSPITALITY Chelsea',v_hosp),
    ('Mondrian Shoreditch Desk','Mondrian Shoreditch','GB','https://www.sbe.com/hotels/mondrian/shoreditch',NULL,'reservations.shoreditch@mondrianhotels.com','+442076139900',NULL,'Curtain Road','London','England','GB',51.525,-0.080,'45 Curtain Road, London EC2A 3PT','BOOKER_DEMAND UK London hotel HOSPITALITY Shoreditch',v_hosp),
    ('Treehouse London Desk','Treehouse Hotel London','GB','https://www.treehousehotels.com/london',NULL,'london@treehousehotels.com','+442074860000',NULL,'Marylebone','London','England','GB',51.518,-0.145,'10 Portman Square, London W1H 6AZ','BOOKER_DEMAND UK London hotel HOSPITALITY Marylebone',v_hosp),
    ('Montcalm Marble Arch Desk','The Montcalm London Marble Arch','GB','https://www.montcalm.co.uk/marble-arch/',NULL,'reservations@montcalm.co.uk','+442074029888',NULL,'Great Cumberland Place','London','England','GB',51.515,-0.160,'2 Wallenberg Place, London W1H 7TN','BOOKER_DEMAND UK London hotel HOSPITALITY Marylebone',v_hosp),
    ('London Marriott Grosvenor Square Desk','London Marriott Hotel Grosvenor Square','GB','https://www.marriott.com/en-us/hotels/longs-london-marriott-hotel-grosvenor-square',NULL,'mhrs.longs.reservation@marriott.com','+442074935000',NULL,'Grosvenor Square','London','England','GB',51.512,-0.150,'Grosvenor Square, London W1K 6JP','BOOKER_DEMAND UK London hotel HOSPITALITY Mayfair',v_hosp),
    ('InterContinental Park Lane Desk','InterContinental London Park Lane','GB','https://www.ihg.com/intercontinental/hotels/gb/en/london/lonha/hoteldetail',NULL,'london.parklane@ihg.com','+442074095000',NULL,'Park Lane','London','England','GB',51.505,-0.151,'One Hamilton Place, London W1J 7QY','BOOKER_DEMAND UK London hotel HOSPITALITY Mayfair',v_hosp),
    ('JW Marriott Grosvenor House Desk','JW Marriott Grosvenor House','GB','https://www.marriott.com/en-us/hotels/lonjw-jw-marriott-grosvenor-house-london',NULL,'mhrs.lonjw.reservation@marriott.com','+442074996366',NULL,'Park Lane','London','England','GB',51.510,-0.152,'86-90 Park Lane, London W1K 7TN','BOOKER_DEMAND UK London hotel HOSPITALITY Mayfair',v_hosp),
    ('Dorchester Hotel Desk','The Dorchester','GB','https://www.dorchestercollection.com/london/the-dorchester/',NULL,'reservations@dorchesterhotel.com','+442076298888',NULL,'Park Lane','London','England','GB',51.507,-0.152,'53 Park Lane, London W1K 1QA','BOOKER_DEMAND UK London hotel HOSPITALITY Mayfair',v_hosp),
    ('45 Park Lane Desk','45 Park Lane','GB','https://www.dorchestercollection.com/london/45-park-lane/',NULL,'reservations@45parklane.com','+442074935454',NULL,'Park Lane','London','England','GB',51.509,-0.152,'45 Park Lane, London W1K 1PN','BOOKER_DEMAND UK London hotel HOSPITALITY Mayfair',v_hosp),
    ('Hotel 41 Buckingham Gate Desk','Hotel 41','GB','https://www.41hotel.com/',NULL,'reservations@41hotel.com','+442073000046',NULL,'Buckingham Gate','London','England','GB',51.499,-0.140,'41 Buckingham Palace Road, London SW1W 0PS','BOOKER_DEMAND UK London hotel HOSPITALITY Westminster',v_hosp),
    ('Athenaeum Hotel Desk','The Athenaeum Hotel & Residences','GB','https://www.athenaeumhotel.com/',NULL,'info@athenaeumhotel.com','+442074993464',NULL,'Piccadilly','London','England','GB',51.505,-0.146,'116 Piccadilly, London W1J 7BJ','BOOKER_DEMAND UK London hotel HOSPITALITY Mayfair',v_hosp),
    ('Stafford London Desk','The Stafford London','GB','https://www.thestaffordlondon.com/',NULL,'reservations@thestaffordhotel.co.uk','+442074933011',NULL,'St James''s Place','London','England','GB',51.506,-0.140,'16-18 St James''s Place, London SW1A 1NJ','BOOKER_DEMAND UK London hotel HOSPITALITY Westminster',v_hosp),
    ('Dukes London Desk','Dukes London','GB','https://www.dukeshotel.com/',NULL,'bookings@dukeshotel.com','+442074914840',NULL,'St James''s Place','London','England','GB',51.506,-0.140,'35 St James''s Place, London SW1A 1NY','BOOKER_DEMAND UK London hotel HOSPITALITY Westminster',v_hosp)
  ) AS t(
    display_name, legal_name, country, website_url, website_domain, email, phone, whatsapp,
    base_label, city, region, country_code, lat, lng, formatted_address, note, service_type_id
  )
  LOOP
    IF EXISTS (
      SELECT 1 FROM organizations o WHERE o.archived_at IS NULL AND (
        (lower(o.display_name) = lower(r.display_name) AND o.legal_country_code = r.country)
        OR (r.email IS NOT NULL AND lower(coalesce(o.primary_email, '')) = lower(r.email)
            AND o.notes_public LIKE 'BOOKER_DEMAND%')
      )
    ) THEN
      skipped := skipped + 1;
      CONTINUE;
    END IF;

    INSERT INTO organizations (
      display_name, legal_name, legal_country_code, legal_city, legal_region,
      website_url, website_domain, primary_email, primary_phone_e164, primary_whatsapp_e164,
      notes_public, is_test, created_by_user_id
    ) VALUES (
      r.display_name, r.legal_name, r.country, r.city, r.region,
      r.website_url, r.website_domain, r.email, r.phone, COALESCE(r.whatsapp, r.phone),
      r.note, false, v_admin
    ) RETURNING id INTO v_org;

    INSERT INTO organization_capabilities (organization_id, capability)
    VALUES (v_org, 'BUYER') ON CONFLICT DO NOTHING;
    INSERT INTO partnerships (organization_id, relationship_status, status_changed_at)
    VALUES (v_org, 'LEAD', now());
    INSERT INTO offerings (organization_id, service_type_id, operational_status)
    VALUES (v_org, r.service_type_id, 'UNKNOWN');
    INSERT INTO organization_locations (
      organization_id, label, location_kind, city, region, country_code, lat, lng, formatted_address, is_primary
    ) VALUES (v_org, r.base_label, 'OPS_BASE', r.city, r.region, r.country_code, r.lat, r.lng, r.formatted_address, true);
    INSERT INTO organization_contacts (
      organization_id, full_name, contact_type, title, email, phone_e164, is_primary
    ) VALUES (
      v_org, 'Guest / Concierge desk', 'Other', 'Bookings desk', r.email, r.phone, true
    );
    inserted := inserted + 1;
  END LOOP;
  RAISE NOTICE 'London hotels bookers R2: inserted=% skipped=%', inserted, skipped;
END $$;
